import { expect, test, type Page } from '@playwright/test'
import { readFile } from 'node:fs/promises'

async function addText(page: Page, text: string, x: number, y: number) {
  await page.getByRole('button', { name: 'Текст', exact: true }).click()
  await page.getByRole('button', { name: 'Добавить в центр', exact: true }).click()
  await page.getByRole('textbox', { name: 'Текст аннотации', exact: true }).fill(text)
  const position = page.locator('details.annotation-position').filter({ has: page.getByText('Положение и размер', { exact: true }) })
  if (!(await position.evaluate((node) => node.hasAttribute('open')))) await position.locator('summary').click()
  for (const [name, value] of [['X, px', x], ['Y, px', y], ['Ширина, px', 100]] as const) {
    await position.getByRole('spinbutton', { name, exact: true }).fill(String(value))
    await position.getByRole('spinbutton', { name, exact: true }).press('Tab')
  }
}

test('annotation guides align neighbors, show equal gaps, bypass with Shift and stay out of exports', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/editor')
  await page.locator('.upload-card input').setInputFiles({ name: 'guides.csv', mimeType: 'text/csv', buffer: Buffer.from('Год,Значение\n2020,20\n2021,35\n2022,50') })
  await page.getByRole('button', { name: /Выбрать график/ }).click()
  await page.getByRole('button', { name: 'Настроить оформление →' }).click()
  await page.getByRole('tab', { name: 'Аннотации и акценты', exact: true }).click()
  await addText(page, 'Первый', 100, 220)
  await addText(page, 'Второй', 400, 220)
  await addText(page, 'Третий', 600, 400)
  const selected = page.locator('.canvas-annotation.selected')
  const state = () => selected.evaluate((node) => ({ x: Number.parseFloat((node as HTMLElement).style.left), y: Number.parseFloat((node as HTMLElement).style.top) }))
  const shell = page.locator('.chart-canvas-shell')
  const scale = await shell.evaluate((node) => node.getBoundingClientRect().width / (node as HTMLElement).offsetWidth)
  const start = (await selected.locator('.annotation-content').boundingBox())!
  const from = { x: start.x + start.width / 2, y: start.y + start.height / 2 }
  await page.mouse.move(from.x, from.y)
  await page.mouse.down()
  await page.mouse.move(from.x + (253 - 600) * scale, from.y + (223 - 400) * scale, { steps: 5 })
  await expect.poll(state).toEqual({ x: 250, y: 220 })
  await expect(selected.locator('.annotation-resize').first()).toBeHidden()
  await expect(selected.locator('.annotation-resize').last()).toBeHidden()
  await expect(page.locator('.annotation-alignment-guides [data-guide-kind="gap"] text')).toHaveText(['50 px', '50 px'])
  await shell.screenshot({ path: '/tmp/viiiz-annotation-alignment.png' })
  await page.keyboard.down('Shift')
  await page.mouse.move(from.x + (254 - 600) * scale, from.y + (224 - 400) * scale)
  await expect.poll(async () => Math.round((await state()).x)).toBe(254)
  await expect(page.locator('.annotation-alignment-guides')).toHaveCount(0)
  await page.keyboard.up('Shift')
  await page.mouse.move(from.x + (253 - 600) * scale, from.y + (223 - 400) * scale)
  await expect.poll(state).toEqual({ x: 250, y: 220 })
  await page.mouse.up()
  await expect(page.locator('.annotation-alignment-guides')).toHaveCount(0)
  await expect(selected.locator('.annotation-resize').first()).toBeVisible()
  await expect(selected.locator('.annotation-resize').last()).toBeVisible()

  const resize = (await page.getByRole('button', { name: 'Ширина аннотации: правый край', exact: true }).boundingBox())!
  await page.mouse.move(resize.x + resize.width / 2, resize.y + resize.height / 2)
  await page.mouse.down()
  await page.mouse.move(resize.x + resize.width / 2 + 47 * scale, resize.y + resize.height / 2)
  await expect(selected.locator('.annotation-resize').first()).toBeVisible()
  await expect(selected.locator('.annotation-resize').last()).toBeVisible()
  await expect.poll(() => selected.evaluate((node) => Number.parseFloat((node as HTMLElement).style.width))).toBe(150)
  await expect(page.locator('.annotation-alignment-guides')).toHaveCount(1)
  await page.keyboard.press('Escape')
  await page.mouse.up()
  await expect.poll(() => selected.evaluate((node) => Number.parseFloat((node as HTMLElement).style.width))).toBe(100)
  await expect(page.locator('.annotation-alignment-guides')).toHaveCount(0)
  await page.getByRole('button', { name: 'Область', exact: true }).click()
  await page.getByRole('button', { name: 'Добавить в центр', exact: true }).click()
  const position = page.locator('details.annotation-position').filter({ has: page.getByText('Положение и размер', { exact: true }) })
  if (!(await position.evaluate((node) => node.hasAttribute('open')))) await position.locator('summary').click()
  for (const [name, value] of [['X, px', 100], ['Y, px', 100], ['Ширина, px', 140], ['Высота, px', 80]] as const) {
    await position.getByRole('spinbutton', { name, exact: true }).fill(String(value))
    await position.getByRole('spinbutton', { name, exact: true }).press('Tab')
  }
  const center = await shell.evaluate((node) => ({ x: (node as HTMLElement).offsetWidth / 2 - 70, y: (node as HTMLElement).offsetHeight / 2 - 40 }))
  const area = page.locator('.decoration-overlay rect.decoration-selection')
  const areaBox = (await area.boundingBox())!
  await page.mouse.move(areaBox.x + areaBox.width / 2, areaBox.y + areaBox.height / 2)
  await page.mouse.down()
  await page.mouse.move(areaBox.x + areaBox.width / 2 + (center.x + 3 - 100) * scale, areaBox.y + areaBox.height / 2 + (center.y + 3 - 100) * scale, { steps: 5 })
  await expect.poll(async () => Number(await area.getAttribute('x'))).toBeCloseTo(center.x, 1)
  await expect.poll(async () => Number(await area.getAttribute('y'))).toBeCloseTo(center.y, 1)
  await expect(page.locator('.annotation-alignment-guides [data-guide-kind="alignment"]')).toHaveCount(2)
  await page.mouse.up()
  await expect(page.locator('.annotation-alignment-guides')).toHaveCount(0)
  await page.locator('.export-menu > summary').click()
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Скачать SVG', exact: true }).click()
  const svg = await readFile((await (await download).path())!, 'utf8')
  expect(svg).not.toContain('annotation-alignment-guides')
  expect(svg).not.toContain('50 px')
})
