import { expect, test, type Page } from '@playwright/test'
import { readFile, writeFile } from 'node:fs/promises'

async function openEditor(page: Page, line = false) {
  await page.goto('/editor')
  await page.locator('.upload-card input').setInputFiles({ name: 'annotation.csv', mimeType: 'text/csv', buffer: Buffer.from('Год,Значение\n2020,20\n2021,35\n2022,50') })
  await page.getByRole('button', { name: /Выбрать график/ }).click()
  if (line) await page.getByRole('button', { name: 'Линия', exact: true }).click()
  await page.getByRole('button', { name: 'Настроить оформление →' }).click()
  await page.getByRole('tab', { name: 'Аннотации и акценты', exact: true }).click()
}
async function exportSvg(page: Page) {
  await expect(page.locator('.chart-canvas-shell').first()).toHaveAttribute('data-render-status', 'settled')
  await page.locator('.export-menu > summary').click()
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Скачать SVG' }).click()
  const svg = await readFile((await (await download).path())!, 'utf8')
  await page.locator('.export-menu > summary').click()
  return svg
}

function expectArrowShaft(exported: number[], attachment: number[]) {
  exported.slice(0, 6).forEach((value, index) => expect(value).toBeCloseTo(attachment[index], 0))
  // The visible shaft stops at the head's base; the attachment remains at the tip.
  const tipX = attachment[6], tipY = attachment[7]
  const angle = Math.atan2(tipY - attachment[5], tipX - attachment[4])
  const inset = 8 * Math.cos(Math.PI / 6)
  expect(exported[6]).toBeCloseTo(tipX - inset * Math.cos(angle), 0)
  expect(exported[7]).toBeCloseTo(tipY - inset * Math.sin(angle), 0)
}

test('inserts currency and unit symbols into editable affixes on both axes and value labels', async ({ page }) => {
  await openEditor(page)
  await page.getByRole('tab', { name: 'Оси и шкалы', exact: true }).click()
  await page.locator('.number-format-settings > summary').click()
  const groups = page.locator('.number-affix-group')
  const y = groups.nth(0)
  await y.getByRole('combobox', { name: 'Добавить символ: префикс', exact: true }).selectOption('€')
  await expect(y.getByRole('textbox', { name: 'Префикс', exact: true })).toHaveValue('€')
  await y.getByRole('textbox', { name: 'Префикс', exact: true }).fill('≈ ')
  await y.getByRole('combobox', { name: 'Добавить символ: префикс', exact: true }).selectOption('€')
  await expect(y.getByRole('textbox', { name: 'Префикс', exact: true })).toHaveValue('≈ €')
  await groups.nth(1).getByRole('combobox', { name: 'Добавить символ: суффикс', exact: true }).selectOption('°')
  await expect(groups.nth(1).getByRole('textbox', { name: 'Суффикс', exact: true })).toHaveValue('°')
  await groups.nth(2).getByRole('checkbox', { name: 'Как на оси Y' }).focus()
  await page.keyboard.press('Space')
  await groups.nth(2).getByRole('combobox', { name: 'Добавить символ: суффикс', exact: true }).selectOption('%')
  await expect(page.locator('.number-format-preview')).toContainText('%')
  await page.screenshot({ path: '/tmp/viiiz-affix-symbols.png', fullPage: true })
  const svg = await exportSvg(page)
  expect(svg).toContain('≈ €')
})

test('quiet text controls move directly, resize from slim edges and keep editing accessible', async ({ page }) => {
  await openEditor(page)
  await page.getByRole('button', { name: 'Текст', exact: true }).click()
  await page.getByRole('button', { name: 'Добавить в центр', exact: true }).click()
  await page.getByRole('textbox', { name: 'Текст аннотации', exact: true }).fill('Пояснение к графику')
  const annotation = page.locator('.canvas-annotation.selected')
  await expect(annotation.locator('.annotation-drag-handle')).toHaveCount(0)
  const outsideHandles = await annotation.evaluate((element) => {
    const frame = element.getBoundingClientRect()
    return [...element.querySelectorAll<HTMLElement>('.annotation-resize')].map((handle) => {
      const box = handle.getBoundingClientRect(), mark = getComputedStyle(handle, '::after')
      return { outside: box.right < frame.left || box.left > frame.right, width: Number.parseFloat(mark.width), height: Number.parseFloat(mark.height) }
    })
  })
  expect(outsideHandles).toHaveLength(2)
  outsideHandles.forEach((handle) => { expect(handle.outside).toBe(true); expect(handle.width).toBeGreaterThanOrEqual(3); expect(handle.height).toBeGreaterThanOrEqual(18) })
  const move = page.getByRole('button', { name: 'Переместить аннотацию', exact: true })
  const position = () => annotation.evaluate((element) => [Number.parseFloat((element as HTMLElement).style.left), Number.parseFloat((element as HTMLElement).style.top)])
  const original = await position()
  await move.focus()
  await move.press('Shift+ArrowDown')
  await expect.poll(position).toEqual([original[0], original[1] + 10])
  const content = annotation.locator('.annotation-content')
  const box = (await content.boundingBox())!
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2)
  await page.mouse.down()
  await page.mouse.move(box.x + box.width / 2 + 20, box.y + box.height / 2 + 15, { steps: 4 })
  await page.mouse.up()
  await expect.poll(async () => (await position())[0]).toBeGreaterThan(original[0])
  await content.dblclick()
  await expect(annotation).toHaveClass(/editing/)
  await content.fill('Редактируем без перемещения')
  await expect(page.getByRole('textbox', { name: 'Текст аннотации', exact: true })).toHaveText('Редактируем без перемещения')
  await page.screenshot({ path: '/tmp/viiiz-quiet-text-controls.png', fullPage: true })
})

test('text frames auto-size vertically and attached arrows follow wrapping and line breaks', async ({ page }) => {
  await openEditor(page)
  await page.getByRole('button', { name: 'Текст', exact: true }).click()
  await page.getByRole('button', { name: 'Добавить в центр', exact: true }).click()
  await page.getByRole('textbox', { name: 'Название в списке' }).fill('Заметка')
  const editor = page.getByRole('textbox', { name: 'Текст аннотации', exact: true })
  const annotation = page.locator('.canvas-annotation')
  const dimensions = () => annotation.evaluate((element) => ({ width: Number.parseFloat((element as HTMLElement).style.width), height: (element as HTMLElement).offsetHeight, x: Number.parseFloat((element as HTMLElement).style.left), y: Number.parseFloat((element as HTMLElement).style.top) }))
  await editor.fill('Рост')
  const single = await dimensions()
  expect(single.height).toBeLessThan(30)
  await expect(annotation.locator('.annotation-content')).toHaveCSS('padding', '2px')
  await editor.fill('Первая строка\nВторая строка\nТретья строка')
  await expect.poll(async () => (await dimensions()).height).toBeGreaterThan(single.height * 2)
  await editor.fill('Рост')
  await expect.poll(async () => (await dimensions()).height).toBe(single.height)
  await editor.fill('Длинное пояснение к графику, которое переносится при изменении ширины рамки')
  const wide = await dimensions()
  const handle = (await page.getByRole('button', { name: 'Ширина аннотации: правый край' }).boundingBox())!
  await page.mouse.move(handle.x + handle.width / 2, handle.y + handle.height / 2)
  await page.mouse.down()
  await page.mouse.move(handle.x + handle.width / 2 - 60, handle.y + handle.height / 2 + 25, { steps: 4 })
  await page.mouse.up()
  const narrow = await dimensions()
  expect(narrow.width).toBeLessThan(wide.width)
  expect(narrow.height).toBeGreaterThan(wide.height)
  expect(narrow.y).toBe(wide.y)
  await page.getByRole('button', { name: 'Добавить стрелку к тексту', exact: true }).click()
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: 'Выбрать точку у текста', exact: true }).click()
  await page.locator('.annotation-placement-overlay').getByRole('button', { name: 'Заметка · Снизу', exact: true }).click()
  const path = page.locator('.decoration-overlay path.decoration-selection')
  const start = async () => (await path.getAttribute('d'))!.match(/-?\d+(?:\.\d+)?/g)!.map(Number).slice(0, 2)
  await expect.poll(async () => (await start())[0]).toBeCloseTo(narrow.x + narrow.width / 2, 1)
  await expect.poll(async () => (await start())[1]).toBe(narrow.y + narrow.height + 1)
  await page.locator('.annotation-object-select').first().click()
  await editor.fill('Строка 1\nСтрока 2\nСтрока 3\nСтрока 4\nСтрока 5')
  const multiline = await dimensions()
  await page.locator('.annotation-object-select').last().click()
  await expect.poll(async () => (await start())[0]).toBeCloseTo(multiline.x + multiline.width / 2, 1)
  await expect.poll(async () => (await start())[1]).toBe(multiline.y + multiline.height + 1)
  await page.locator('.annotation-object-select').first().click()
  await page.screenshot({ path: '/tmp/viiiz-annotation-auto-height.png', fullPage: true })
  const svg = await exportSvg(page)
  const positions = await page.evaluate((source) => [...new DOMParser().parseFromString(source, 'image/svg+xml').querySelectorAll('g[data-annotation-id] [data-text-layer=foreground] text')].map((element) => ({ x: Number(element.getAttribute('x')), text: element.textContent })), svg)
  expect(positions.map(({ text }) => text)).toEqual(['Строка 1', 'Строка 2', 'Строка 3', 'Строка 4', 'Строка 5'])
  positions.forEach(({ x }) => expect(x).toBe(multiline.x + 3))
})

test('text can be placed, edited from both surfaces, locked, hidden and restored for export', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await openEditor(page)
  await expect(page.locator('.annotation-empty')).toBeVisible()
  await page.getByRole('button', { name: 'Текст', exact: true }).click()
  await page.locator('.annotation-placement-overlay').click({ position: { x: 180, y: 150 } })
  await expect(page.locator('.annotation-objects li')).toHaveCount(1)
  await page.getByRole('textbox', { name: 'Текст аннотации', exact: true }).fill('Начало роста')
  await expect(page.locator('.canvas-annotation.selected .annotation-content')).toHaveText('Начало роста')
  await page.locator('.canvas-annotation.selected .annotation-content').dblclick()
  await page.locator('.canvas-annotation.selected .annotation-content').fill('Пик роста')
  await expect(page.getByRole('textbox', { name: 'Текст аннотации', exact: true })).toHaveText('Пик роста')
  await page.getByRole('spinbutton', { name: 'Размер, px', exact: true }).fill('24')
  await page.getByRole('spinbutton', { name: 'Размер, px', exact: true }).press('Tab')
  await expect(page.locator('.canvas-annotation.selected')).toHaveCSS('font-size', '24px')
  await expect(page.locator('.annotation-position')).not.toHaveAttribute('open', '')
  await page.getByRole('button', { name: 'Заблокировать: Пик роста', exact: true }).click()
  await expect(page.locator('.canvas-annotation.selected')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Удалить объект', exact: true })).toBeDisabled()
  await expect(page.getByRole('textbox', { name: 'Текст аннотации', exact: true })).toHaveAttribute('contenteditable', 'false')
  expect(await exportSvg(page)).toContain('Пик роста')
  await page.getByRole('button', { name: 'Скрыть: Пик роста', exact: true }).click()
  await expect(page.locator('.canvas-annotation')).toHaveCount(0)
  expect(await exportSvg(page)).not.toContain('Пик роста')
  await page.getByRole('button', { name: 'Показать: Пик роста', exact: true }).click()
  await page.getByRole('button', { name: 'Разблокировать: Пик роста', exact: true }).click()
  await page.getByRole('button', { name: 'Дублировать объект', exact: true }).click()
  await expect(page.locator('.annotation-objects li')).toHaveCount(2)
  await page.getByRole('button', { name: 'Удалить объект', exact: true }).click()
  await expect(page.locator('.annotation-objects li')).toHaveCount(1)
  await page.locator('.annotation-object-select').first().click()
  await page.screenshot({ path: '/tmp/viiiz-annotations-text.png', fullPage: true })
  expect(errors).toEqual([])
})

test('draws and configures areas and arrows, cancels placement and retains objects across tabs', async ({ page }) => {
  await openEditor(page)
  await page.getByRole('button', { name: 'Линия', exact: true }).click()
  await page.keyboard.press('Escape')
  await expect(page.locator('.annotation-placement-overlay')).toHaveCount(0)
  await expect(page.locator('.annotation-objects li')).toHaveCount(0)
  await page.getByRole('button', { name: 'Область', exact: true }).click()
  const overlay = await page.locator('.annotation-placement-overlay').boundingBox()
  if (!overlay) throw new Error('No placement overlay')
  await page.mouse.move(overlay.x + 120, overlay.y + 100)
  await page.mouse.down()
  await page.mouse.move(overlay.x + 220, overlay.y + 190)
  await page.mouse.up()
  await expect(page.locator('.annotation-objects li')).toHaveCount(1)
  await expect(page.getByRole('spinbutton', { name: 'Граница, px', exact: true })).toHaveValue('0')
  await expect(page.locator('.decoration-overlay rect.decoration-selection')).toHaveAttribute('fill', 'transparent')
  const area = page.locator('.decoration-overlay rect.decoration-selection')
  const beforeMove = await area.evaluate((element) => ['x', 'y', 'width', 'height'].map((attribute) => Number(element.getAttribute(attribute))))
  const areaBox = await area.boundingBox()
  if (!areaBox) throw new Error('No selected area')
  await page.mouse.move(areaBox.x + areaBox.width / 2, areaBox.y + areaBox.height / 2)
  await page.mouse.down()
  await page.mouse.move(areaBox.x + areaBox.width / 2 + 24, areaBox.y + areaBox.height / 2 + 18, { steps: 4 })
  await page.mouse.up()
  await expect.poll(async () => Number(await area.getAttribute('x'))).toBeGreaterThan(beforeMove[0])
  await expect.poll(async () => Number(await area.getAttribute('y'))).toBeGreaterThan(beforeMove[1])
  expect([Number(await area.getAttribute('width')), Number(await area.getAttribute('height'))]).toEqual(beforeMove.slice(2))
  await page.getByRole('textbox', { name: 'Название в списке' }).fill('Период роста')
  await page.getByRole('spinbutton', { name: 'Прозрачность, %' }).fill('70')
  await page.getByRole('spinbutton', { name: 'Прозрачность, %' }).press('Tab')
  await page.screenshot({ path: '/tmp/viiiz-quiet-area-controls.png', fullPage: true })
  await page.getByRole('button', { name: 'Стрелка', exact: true }).click()
  await page.getByRole('button', { name: 'Добавить в центр', exact: true }).click()
  await expect(page.locator('.annotation-objects li')).toHaveCount(2)
  await expect(page.getByRole('spinbutton', { name: 'Прозрачность, %' })).toHaveValue('0')
  await page.getByRole('spinbutton', { name: 'Толщина, px', exact: true }).fill('12')
  await page.getByRole('spinbutton', { name: 'Толщина, px', exact: true }).press('Tab')
  await page.getByRole('combobox', { name: 'Форма', exact: true }).selectOption('curved-line')
  await page.getByRole('combobox', { name: 'Стиль линии', exact: true }).selectOption('dashed')
  await page.getByRole('combobox', { name: 'Наконечники', exact: true }).selectOption('both')
  await expect(page.locator('.decoration-overlay path.decoration-selection')).toHaveAttribute('stroke', 'transparent')
  await page.getByRole('button', { name: 'Дублировать объект', exact: true }).click()
  await expect(page.locator('.annotation-objects li')).toHaveCount(3)
  await page.getByRole('button', { name: 'Удалить объект', exact: true }).click()
  await page.getByRole('tab', { name: 'Текст', exact: true }).click()
  await page.getByRole('tab', { name: 'Аннотации и акценты', exact: true }).click()
  await expect(page.locator('.annotation-objects li')).toHaveCount(2)
  expect(await exportSvg(page)).toContain('stroke-dasharray')
  await page.locator('.annotation-object-select').last().click()
  await page.screenshot({ path: '/tmp/viiiz-annotations-arrow.png', fullPage: true })
})

test('annotations belong to the selected panel in a composition', async ({ page }) => {
  await page.goto('/editor')
  await page.getByRole('button', { name: 'Группы респондентов', exact: true }).click()
  await page.getByRole('button', { name: 'Графики', exact: true }).click()
  await page.getByRole('tab', { name: 'Аннотации и акценты', exact: true }).click()
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollHeight - window.innerHeight)).toBeLessThanOrEqual(0)
  await page.getByRole('button', { name: 'Текст', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Текст', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: 'Добавить в центр', exact: true }).click()
  await page.getByRole('textbox', { name: 'Текст аннотации', exact: true }).fill('Важное наблюдение')
  await page.locator('.multiples-panel-name').nth(1).click()
  await expect(page.locator('.annotation-objects li')).toHaveCount(0)
  await page.locator('.multiples-panel-name').first().click()
  await expect(page.locator('.annotation-objects li')).toHaveCount(1)
  const svg = await exportSvg(page)
  await writeFile('/tmp/viiiz-annotation-composition.svg', svg)
  const text = await page.evaluate((source) => [...new DOMParser().parseFromString(source, 'image/svg+xml').querySelectorAll('text')].map((element) => element.textContent).join(''), svg)
  expect(text).toContain('Важное наблюдение')
})

for (const line of [false, true]) test(`attached curves follow text and data on ${line ? 'lines' : 'bars'}`, async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await openEditor(page, line)
  await page.getByRole('button', { name: 'Текст', exact: true }).click()
  await page.getByRole('button', { name: 'Добавить в центр', exact: true }).click()
  await page.getByRole('textbox', { name: 'Текст аннотации', exact: true }).fill('Рост')
  await page.getByRole('button', { name: 'Стрелка', exact: true }).click()
  await page.getByRole('button', { name: 'Добавить в центр', exact: true }).click()
  await page.getByRole('combobox', { name: 'Форма', exact: true }).selectOption('curved-line')
  await page.getByRole('button', { name: 'Выбрать точку у текста', exact: true }).click()
  await expect(page.locator('.annotation-placement-overlay [role=button]')).toHaveCount(8)
  await page.locator('.annotation-placement-overlay').getByRole('button', { name: 'Рост · Справа', exact: true }).click()
  await page.getByRole('button', { name: 'Выбрать точку на графике' }).click()
  const target = page.locator('.annotation-placement-overlay [role=button]').last()
  const point = target.locator('.annotation-anchor-dot')
  await expect(page.locator('.annotation-placement-overlay [role=button]')).toHaveCount(3)
  const end = [Number(await point.getAttribute('cx')), Number(await point.getAttribute('cy'))]
  await target.click()
  await expect(page.locator('.annotation-placement-overlay')).toHaveCount(0)
  await expect(page.getByRole('combobox', { name: /Конец: точка графика|Начало: прикрепить к тексту/ })).toHaveCount(0)
  const path = page.locator('.decoration-overlay path.decoration-selection')
  const coordinates = async () => (await path.getAttribute('d'))!.match(/-?\d+(?:\.\d+)?/g)!.map(Number)
  await expect.poll(async () => (await coordinates()).slice(-2)).toEqual(end)
  const before = await coordinates()
  await page.getByRole('combobox', { name: 'Форма изгиба' }).selectOption('horizontal')
  await expect(page.locator('.decoration-overlay .decoration-handle')).toHaveCount(2)
  await expect.poll(async () => (await coordinates())[3]).toBe(before[1])
  await page.locator('.annotation-object-select').first().click()
  await page.locator('.annotation-position summary').last().click()
  await page.getByRole('spinbutton', { name: 'X, px', exact: true }).fill('100')
  await page.getByRole('spinbutton', { name: 'X, px', exact: true }).press('Tab')
  await page.locator('.annotation-object-select').last().click()
  await expect.poll(async () => (await coordinates())[0]).toBe(341)
  expect((await coordinates()).slice(-2)).toEqual(end)
  await page.getByRole('tab', { name: 'Оси и шкалы', exact: true }).click()
  await page.locator('.axis-scale-settings > summary').click()
  await page.locator('.axis-scale-settings').getByRole('spinbutton', { name: 'Максимум', exact: true }).last().fill('100')
  await page.locator('.axis-scale-settings').getByRole('spinbutton', { name: 'Максимум', exact: true }).last().press('Tab')
  await page.getByRole('tab', { name: 'Аннотации и акценты', exact: true }).click()
  await expect.poll(async () => (await coordinates()).at(-1)!).toBeGreaterThan(end[1])
  const rescaled = (await coordinates()).slice(-2)
  await page.getByRole('button', { name: 'Отвязать от текста', exact: true }).click()
  await page.getByRole('button', { name: 'Отвязать от графика', exact: true }).click()
  await expect(page.locator('.decoration-overlay .decoration-handle')).toHaveCount(4)
  const unlinked = await coordinates()
  expect(unlinked.slice(-2)).toEqual(rescaled)
  await page.screenshot({ path: `/tmp/viiiz-attached-${line ? 'line' : 'bar'}.png`, fullPage: true })
  const svg = await exportSvg(page)
  const exported = await page.evaluate((source) => [...new DOMParser().parseFromString(source, 'image/svg+xml').querySelectorAll('path')].find((node) => node.getAttribute('stroke') === '#4f4b59' && node.getAttribute('d')?.includes('C'))?.getAttribute('d'), svg)
  expect(exported).toBeTruthy()
  const exportedCoordinates = exported!.match(/-?\d+(?:\.\d+)?/g)!.map(Number)
  expectArrowShaft(exportedCoordinates, unlinked)
  expect(errors).toEqual([])
})

test('exports mixed formatting without breaking words at style boundaries', async ({ page }) => {
  await openEditor(page)
  await page.getByRole('button', { name: 'Текст', exact: true }).click()
  await page.getByRole('button', { name: 'Добавить в центр', exact: true }).click()
  const editor = page.getByRole('textbox', { name: 'Текст аннотации', exact: true })
  await editor.evaluate((element) => {
    element.innerHTML = '<span style="color:#ff3333;font-size:28px;font-family:Georgia,serif">Т</span><b style="color:#ff3333;font-size:28px">екст</b> <span style="font-style:italic;color:#1677a6">аннотации</span><br><span style="background-color:#f5e8b0"><b>Разные стили</b></span>'
    element.dispatchEvent(new InputEvent('input', { bubbles: true, inputType: 'insertText' }))
  })
  const canvas = page.locator('.canvas-annotation.selected')
  await expect(canvas.locator('.annotation-halo')).toHaveAttribute('aria-hidden', 'true')
  await expect(canvas.locator('.annotation-foreground span').first()).toHaveCSS('-webkit-text-stroke-width', '0px')
  await expect(canvas.locator('.annotation-halo text').first()).toHaveAttribute('stroke-width', '6')
  await expect(canvas.locator('.annotation-halo text').first()).toHaveAttribute('stroke-linejoin', 'round')
  const alignedLayers = await canvas.evaluate((element) => {
    const positions = (selector: string) => {
      const walker = document.createTreeWalker(element.querySelector(selector)!, NodeFilter.SHOW_TEXT)
      const rectangles: number[][] = []
      while (walker.nextNode()) {
        if (!walker.currentNode.textContent?.trim()) continue
        const range = document.createRange(); range.selectNodeContents(walker.currentNode)
        rectangles.push(...[...range.getClientRects()].map((rect) => [rect.x, rect.y, rect.width, rect.height]))
      }
      return rectangles
    }
    return { foreground: positions('.annotation-foreground'), halo: positions('.annotation-halo [data-text-layer="outline"]') }
  })
  expect(alignedLayers.halo).toHaveLength(alignedLayers.foreground.length - 1)
  alignedLayers.halo.forEach((rect, index) => {
    expect(rect[0]).toBeCloseTo(alignedLayers.foreground[index][0], 1)
    expect(rect[2]).toBeCloseTo(alignedLayers.foreground[index][2], 1)
    // SVG glyph boxes and HTML inline boxes have slightly different vertical metrics.
    expect(Math.abs(rect[1] - alignedLayers.foreground[index][1])).toBeLessThan(1)
  })
  await page.screenshot({ path: '/tmp/viiiz-mixed-annotation-editor.png', fullPage: true })
  const svg = await exportSvg(page)
  const layers = await page.evaluate((source) => {
    const group = new DOMParser().parseFromString(source, 'image/svg+xml').querySelector('g[data-annotation-id]')!
    return { order: [...group.children].map((layer) => layer.getAttribute('data-text-layer')), outlines: group.querySelectorAll('[data-text-layer=outline] text[stroke-width]').length, foregroundStroke: group.querySelectorAll('[data-text-layer=foreground] [stroke-width]').length }
  }, svg)
  expect(layers.order).toEqual(['background', 'outline', 'highlight', 'foreground'])
  expect(layers.outlines).toBeGreaterThan(0)
  expect(layers.foregroundStroke).toBe(0)
  await writeFile('/tmp/viiiz-rich-annotation.svg', svg)
  const parts = await page.evaluate((source) => {
    const group = new DOMParser().parseFromString(source, 'image/svg+xml').querySelector('g[data-annotation-id]')!
    return { text: [...group.querySelectorAll('[data-text-layer=foreground] text')].map((node) => node.textContent).join(''), nodes: [...group.querySelectorAll('[data-text-layer=foreground] text')].map((node) => ({ text: node.textContent, x: Number(node.getAttribute('x')), y: Number(node.getAttribute('y')), family: node.getAttribute('font-family'), color: node.getAttribute('fill'), weight: node.getAttribute('font-weight'), italic: node.getAttribute('font-style') })), backgrounds: group.querySelectorAll('rect').length }
  }, svg)
  expect(parts.text).toBe('Текст аннотацииРазные стили')
  expect(parts.nodes[0].family).toContain('Georgia')
  expect(parts.nodes[0].color).toBe('rgb(255, 51, 51)')
  expect(parts.nodes[1].weight).toBe('700')
  expect(parts.nodes[1].x).toBeGreaterThan(parts.nodes[0].x)
  expect(parts.nodes[1].y).toBeCloseTo(parts.nodes[0].y, 0)
  expect(parts.nodes.some((node) => node.italic === 'italic')).toBe(true)
  expect(parts.backgrounds).toBeGreaterThan(0)
  await page.locator('.export-menu > summary').click()
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Скачать PNG' }).click()
  const png = await download
  expect(png.suggestedFilename()).toMatch(/\.png$/)
  await png.saveAs('/tmp/viiiz-rich-annotation.png')
})

test('creates a connector from text, repicks its anchors on canvas and cancels without changes', async ({ page }) => {
  await openEditor(page, true)
  await page.getByRole('button', { name: 'Текст', exact: true }).click()
  await page.getByRole('button', { name: 'Добавить в центр', exact: true }).click()
  await page.getByRole('textbox', { name: 'Текст аннотации', exact: true }).fill('Важная точка')
  await page.getByRole('button', { name: 'Добавить стрелку к тексту', exact: true }).click()
  await expect(page.locator('.annotation-objects li')).toHaveCount(2)
  await expect(page.locator('.annotation-placement-overlay [role=button]')).toHaveCount(3)
  await page.locator('.annotation-placement-overlay [role=button]').last().click()
  const path = page.locator('.decoration-overlay path.decoration-selection')
  const before = await path.getAttribute('d')
  await page.locator('.decoration-overlay').getByRole('button', { name: 'Изменить точку у текста', exact: true }).click()
  await expect(page.locator('.annotation-placement-overlay [role=button]')).toHaveCount(8)
  await page.screenshot({ path: '/tmp/viiiz-text-anchor-picker.png', fullPage: true })
  await page.locator('.annotation-placement-overlay').getByRole('button', { name: 'Важная точка · Справа снизу', exact: true }).focus()
  await page.keyboard.press('Enter')
  await expect(page.locator('.annotation-placement-overlay')).toHaveCount(0)
  await expect(path).not.toHaveAttribute('d', before!)
  const attached = await path.getAttribute('d')
  await page.getByRole('button', { name: 'Выбрать точку у текста', exact: true }).click()
  await page.keyboard.press('Escape')
  await expect(page.locator('.annotation-placement-overlay')).toHaveCount(0)
  await expect(path).toHaveAttribute('d', attached!)
  await page.locator('.decoration-overlay').getByRole('button', { name: 'Изменить точку на графике', exact: true }).click()
  await page.getByRole('button', { name: 'Отменить выбор точки', exact: true }).click()
  await expect(page.locator('.annotation-placement-overlay')).toHaveCount(0)
  await expect(path).toHaveAttribute('d', attached!)
  await page.getByRole('button', { name: 'Выбрать точку у текста', exact: true }).click()
  await page.getByRole('button', { name: 'Заблокировать: Изогнутая линия', exact: true }).click()
  await expect(page.locator('.annotation-placement-overlay')).toHaveCount(0)
  await page.getByRole('button', { name: 'Разблокировать: Изогнутая линия', exact: true }).click()
  await expect(path).toHaveAttribute('d', attached!)
  await page.locator('.annotation-object-select').first().click()
  await page.locator('.annotation-position summary').last().click()
  await page.getByRole('spinbutton', { name: 'Ширина, px', exact: true }).fill('300')
  await page.getByRole('spinbutton', { name: 'Ширина, px', exact: true }).press('Tab')
  await page.locator('.annotation-object-select').last().click()
  await expect.poll(async () => (await path.getAttribute('d'))!.match(/-?\d+(?:\.\d+)?/g)!.map(Number)[0]).toBe(681)
  await page.getByRole('button', { name: 'Выбрать точку у текста', exact: true }).click()
  await page.getByRole('tab', { name: 'Текст', exact: true }).click()
  await expect(page.locator('.annotation-placement-overlay')).toHaveCount(0)
  expect(await exportSvg(page)).toContain('Важная точка')
})

test('drags curve controls and snaps either endpoint to text or data with cancel and free placement', async ({ page }) => {
  await openEditor(page, true)
  await page.getByRole('button', { name: 'Текст', exact: true }).click()
  await page.getByRole('button', { name: 'Добавить в центр', exact: true }).click()
  await page.getByRole('textbox', { name: 'Текст аннотации', exact: true }).fill('Пик')
  await page.getByRole('button', { name: 'Добавить стрелку к тексту', exact: true }).click()
  await page.keyboard.press('Escape')
  const overlay = page.locator('.decoration-overlay')
  const path = overlay.locator('path.decoration-selection')
  const coordinates = async () => (await path.getAttribute('d'))!.match(/-?\d+(?:\.\d+)?/g)!.map(Number)
  const screen = async (x: number, y: number) => {
    const bounds = (await overlay.boundingBox())!
    const dimensions = (await overlay.getAttribute('viewBox'))!.split(' ').map(Number)
    return { x: bounds.x + x * bounds.width / dimensions[2], y: bounds.y + y * bounds.height / dimensions[3] }
  }
  const dragTo = async (mode: string, x: number, y: number, release = true) => {
    const handle = overlay.locator(`[data-drag-mode="${mode}"]`)
    const point = handle.locator('circle').last()
    const from = await screen(Number(await point.getAttribute('cx')), Number(await point.getAttribute('cy')))
    const to = await screen(x, y)
    await page.mouse.move(from.x, from.y); await page.mouse.down(); await page.mouse.move(to.x, to.y, { steps: 5 })
    if (release) await page.mouse.up()
  }
  const initial = await coordinates()
  await dragTo('control-first', initial[2] - 70, initial[3] - 60)
  const first = await coordinates()
  expect(first[2]).toBeCloseTo(initial[2] - 70, 0)
  expect(first[3]).toBeCloseTo(initial[3] - 60, 0)
  expect(first.slice(-2)).toEqual(initial.slice(-2))
  await dragTo('control-second', first[4] + 60, first[5] - 30)
  expect((await coordinates())[4]).toBeCloseTo(first[4] + 60, 0)

  await page.getByRole('button', { name: 'Выбрать точку на графике', exact: true }).click()
  const points = await page.locator('.annotation-placement-overlay .annotation-anchor-dot').evaluateAll((elements) => elements.map((element) => [Number(element.getAttribute('cx')), Number(element.getAttribute('cy'))]))
  await page.keyboard.press('Escape')
  // Offset the pointer slightly: snapping should still land precisely on data.
  await dragTo('end', points[2][0] + 10, points[2][1] + 8, false)
  await expect(overlay.locator('.decoration-snap-target.active')).toHaveCount(1)
  await page.screenshot({ path: '/tmp/viiiz-arrow-snap-preview.png', fullPage: true })
  await page.mouse.up()
  expect((await coordinates()).slice(-2)).toEqual(points[2])
  await expect(overlay.locator('[data-drag-mode=end]')).toHaveClass('decoration-attached-anchor')

  // Reverse the usual attachment order: start on data, end on text.
  await dragTo('start', points[0][0], points[0][1])
  expect((await coordinates()).slice(0, 2)).toEqual(points[0])
  await dragTo('end', 500, 300, false)
  const textTarget = overlay.locator('[data-snap-key^="text:"][data-snap-key$=":3"]')
  const textPoint = [Number(await textTarget.getAttribute('cx')), Number(await textTarget.getAttribute('cy'))]
  const target = await screen(textPoint[0], textPoint[1])
  await page.mouse.move(target.x, target.y, { steps: 5 })
  await expect(textTarget).toHaveClass(/active/)
  await page.mouse.up()
  expect((await coordinates()).slice(-2)).toEqual(textPoint)
  await overlay.locator('[data-drag-mode=end]').focus()
  await page.keyboard.press('Enter')
  await page.locator('.annotation-placement-overlay').getByRole('button', { name: 'Пик · Слева', exact: true }).click()
  expect((await coordinates()).slice(0, 2)).toEqual(points[0])
  expect((await coordinates()).slice(-2)).toEqual(textPoint)
  await expect(page.locator('.annotation-anchor-value')).toContainText(['2020', 'Пик'])

  await page.locator('.annotation-object-select').first().click()
  const grip = (await page.locator('.canvas-annotation.selected .annotation-content').boundingBox())!
  await page.mouse.move(grip.x + grip.width / 2, grip.y + grip.height / 2)
  await page.mouse.down(); await page.mouse.move(grip.x + grip.width / 2 + 30, grip.y + grip.height / 2 + 20); await page.mouse.up()
  await page.locator('.annotation-object-select').last().click()
  const moved = await coordinates()
  expect(moved.slice(0, 2)).toEqual(points[0])
  expect(moved[6]).toBeGreaterThan(textPoint[0])
  expect(moved[7]).toBeGreaterThan(textPoint[1])

  await dragTo('end', points[1][0], points[1][1], false)
  await expect(overlay.locator('.decoration-snap-target.active')).toHaveCount(1)
  await page.keyboard.press('Escape'); await page.mouse.up()
  expect(await coordinates()).toEqual(moved)
  await expect(overlay.locator('.decoration-snap-preview')).toHaveCount(0)

  await page.keyboard.down('Shift')
  await dragTo('end', points[1][0] + 7, points[1][1], false)
  await expect(overlay.locator('.decoration-snap-target.active')).toHaveCount(0)
  await page.mouse.up(); await page.keyboard.up('Shift')
  await expect(overlay.locator('[data-drag-mode=end]')).toHaveClass(/decoration-handle-group/)
  expect((await coordinates())[6]).toBeCloseTo(points[1][0] + 7, 0)
  const final = await coordinates()
  const svg = await exportSvg(page)
  const exported = await page.evaluate((source) => [...new DOMParser().parseFromString(source, 'image/svg+xml').querySelectorAll('path')].find((node) => node.getAttribute('d')?.includes('C') && node.getAttribute('stroke-width') === '1.5')?.getAttribute('d'), svg)
  expect(exported).toBeTruthy()
  expectArrowShaft(exported!.match(/-?\d+(?:\.\d+)?/g)!.map(Number), final)
})
