import { expect, test } from '@playwright/test'
import { readFile } from 'node:fs/promises'

test('bump starts without left labels and can switch to smooth lines', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/editor')
  await page.getByRole('button', { name: 'Места команд в Кубке конструкторов F1 — 2021–2025', exact: true }).click()
  await page.getByRole('button', { name: /Выбрать график/ }).click()
  await page.getByRole('button', { name: 'Настроить оформление →' }).click()
  const canvas = page.locator('.chart-canvas-shell')
  await expect(canvas).toHaveAttribute('data-render-status', 'settled')
  const settings = page.locator('details.line-variant-settings')
  if (!(await settings.evaluate((node) => node.hasAttribute('open')))) await settings.locator('summary').click()
  const start = page.getByRole('checkbox', { name: 'Названия в начале линий', exact: true })
  await expect(start).not.toBeChecked()
  const paths = canvas.locator('svg path[fill="none"]')
  const curves = () => paths.evaluateAll((nodes) => nodes.filter((node) => /C/.test(node.getAttribute('d') ?? '')).length)
  expect(await curves()).toBe(0)
  await page.getByRole('checkbox', { name: 'Плавные линии', exact: true }).press('Space')
  await expect.poll(curves).toBeGreaterThan(0)
  await start.press('Space')
  await expect(start).toBeChecked()
  await expect(canvas).toHaveAttribute('data-render-status', 'settled')
  await page.screenshot({ path: '/tmp/viiiz-bump-smooth.png' })
})

test('smooth bump keeps curve geometry in SVG export', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.route('**/src/main.tsx', (route) => route.fulfill({ contentType: 'text/javascript', body: '' }))
  await page.goto('/editor')
  await page.evaluate(async () => {
    await import('/src/index.css')
    await import('/src/App.css')
    const { renderConfig } = await import('/src/test-fixtures/chartAudit.browser.tsx')
    renderConfig('bump', { xField: 'year', yField: 'A', yFields: ['A', 'B', 'C'], bumpMode: 'rank', bumpSmooth: true, showDirectLabels: true, showValues: false }, { name: 'Ranks', columns: ['year', 'A', 'B', 'C'], rows: [{ year: '2020', A: 1, B: 2, C: 3 }, { year: '2021', A: 2, B: 3, C: 1 }, { year: '2022', A: 3, B: 1, C: 2 }, { year: '2023', A: 1, B: 2, C: 3 }] })
  })
  const canvas = page.locator('#chart-audit-host .chart-canvas-shell')
  await expect(canvas).toHaveAttribute('data-render-status', 'settled')
  const paths = await canvas.locator('svg path').evaluateAll((nodes) => nodes.map((node) => node.getAttribute('d')).sort())
  expect(paths.some((path) => path?.includes('C'))).toBe(true)
  const download = page.waitForEvent('download')
  await page.evaluate(async () => (await import('/src/test-fixtures/chartAudit.browser.tsx')).exportSvg())
  const svg = await readFile((await (await download).path())!, 'utf8')
  const exported = await page.evaluate((svg) => [...new DOMParser().parseFromString(svg, 'image/svg+xml').querySelectorAll('path')].map((node) => node.getAttribute('d')).sort(), svg)
  expect(exported.filter((path) => path?.includes('C'))).toEqual(paths.filter((path) => path?.includes('C')))
})
