import { expect, test } from '@playwright/test'
import { readFile } from 'node:fs/promises'

test('bump demo ranks values, labels both ends, selects series and exports', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto('/editor')
  await page.getByRole('button', { name: 'Динамика рейтинга', exact: true }).click()
  await page.getByRole('button', { name: /Выбрать график/ }).click()
  await expect(page.getByRole('button', { name: 'Динамика рейтинга', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('combobox', { name: 'Данные рейтинга', exact: true })).toHaveValue('value')
  await page.getByRole('button', { name: 'Настроить оформление →' }).click()
  const canvas = page.locator('.chart-canvas-shell[data-plot-kind="line"]')
  await expect(canvas).toHaveAttribute('data-render-status', 'settled')
  const north = canvas.locator('svg text').filter({ hasText: /^Север$/ })
  await expect(north).toHaveCount(2)
  const first = await north.first().boundingBox()
  const last = await north.last().boundingBox()
  expect(first && last).toBeTruthy()
  expect(Math.abs(first!.x - last!.x)).toBeGreaterThan(100)
  await page.screenshot({ path: '/tmp/viiiz-bump-editor.png', fullPage: true })
  await page.locator('details.line-variant-settings > summary').click()
  await page.getByRole('combobox', { name: 'Первое место', exact: true }).selectOption('asc')
  await expect.poll(async () => (await north.first().boundingBox())?.y ?? 0).toBeGreaterThan(first!.y + 100)
  await expect(canvas).toHaveAttribute('data-render-status', 'settled')
  await page.getByRole('checkbox', { name: 'Названия в начале линий' }).press('Space')
  await expect(north).toHaveCount(1)
  await page.getByRole('checkbox', { name: 'Названия в начале линий' }).press('Space')
  await expect(north).toHaveCount(2)
  await page.locator('details.series-settings > summary').click()
  await page.getByRole('button', { name: 'Север', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Снять выделение', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Снять выделение', exact: true }).click()
  await page.locator('.export-menu > summary').click()
  const svgDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Скачать SVG' }).click()
  const svg = await readFile((await (await svgDownload).path())!, 'utf8')
  expect(svg).toContain('Север')
  expect(svg).toContain('Вектор')
  const pngDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Скачать PNG' }).click()
  expect((await readFile((await (await pngDownload).path())!)).subarray(1, 4).toString()).toBe('PNG')
  expect(errors).toEqual([])
})

test('bump accepts supplied places in a long table', async ({ page }) => {
  await page.goto('/editor')
  await page.locator('.upload-card input').setInputFiles({ name: 'places.csv', mimeType: 'text/csv', buffer: Buffer.from('Период,Участник,Место\n2024,А,2\n2024,Б,1\n2025,А,1\n2025,Б,2') })
  await page.getByRole('button', { name: /Выбрать график/ }).click()
  await page.getByRole('button', { name: 'Динамика рейтинга', exact: true }).click()
  await page.getByRole('combobox', { name: 'Участник', exact: true }).selectOption('Участник')
  await page.getByRole('combobox', { name: 'Данные рейтинга', exact: true }).selectOption('rank')
  await page.getByRole('button', { name: 'Настроить оформление →' }).click()
  const canvas = page.locator('.chart-canvas-shell[data-plot-kind="line"]')
  await expect(canvas).toHaveAttribute('data-render-status', 'settled')
  await expect(canvas.locator('svg text').filter({ hasText: /^А$/ })).toHaveCount(2)
  await expect(canvas.locator('svg text').filter({ hasText: /^Б$/ })).toHaveCount(2)
})
