import { expect, test } from '@playwright/test'
import { readFile } from 'node:fs/promises'

const openCanvas = async (page: import('@playwright/test').Page) => {
  await page.getByRole('tab', { name: 'Холст', exact: true }).click()
  await page.locator('.canvas-settings > summary').click()
}

test('canvas theme changes text and background, survives resizing, and exports in both themes', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto('/editor')
  await page.getByRole('button', { name: 'Топ стран', exact: true }).click()
  await page.getByRole('button', { name: /Выбрать график/ }).click()
  await page.getByRole('button', { name: 'Круговая', exact: true }).click()
  await page.getByRole('button', { name: 'Настроить оформление →' }).click()
  await openCanvas(page)
  const theme = page.getByRole('checkbox', { name: 'Тёмная тема холста', exact: true })
  await expect(theme).not.toBeChecked()
  await page.getByText('Тёмная тема холста', { exact: true }).click()
  await expect(theme).toBeChecked()
  await expect(page.locator('.chart-canvas svg rect[fill="#151922"]').first()).toBeVisible()
  await expect(page.locator('.chart-canvas svg text[fill="#f4f4f5"]').first()).toBeVisible()
  await page.getByRole('button', { name: /^16:9/ }).click()
  await expect(page.locator('.chart-canvas svg text[fill="#b7bbc5"]').first()).toBeVisible()
  await page.getByRole('button', { name: 'Сбросить', exact: true }).click()
  await expect(page.locator('.chart-canvas svg rect[fill="#151922"]').first()).toBeVisible()
  await expect(page.locator('.chart-canvas svg text').filter({ hasText: /%$/ })).toHaveCount(10)
  await page.waitForTimeout(300)
  await page.screenshot({ path: '/tmp/viiiz-dark-canvas.png', fullPage: true })
  await page.locator('.export-menu > summary').click()
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Скачать SVG' }).click()
  const content = await readFile((await (await download).path())!, 'utf8')
  expect(content).toContain('#151922')
  expect(content).toContain('#f4f4f5')
  await page.locator('.export-menu > summary').click()
  await page.getByText('Тёмная тема холста', { exact: true }).click()
  await expect(theme).not.toBeChecked()
  await expect(page.locator('.chart-canvas svg rect[fill="#ffffff"]').first()).toBeVisible()
  await expect(page.locator('.chart-canvas svg text[fill="#2b2b2b"]').first()).toBeVisible()
  await page.getByRole('button', { name: 'Отменить', exact: true }).click()
  await expect(theme).toBeChecked()
  await expect(page.locator('.chart-canvas svg rect[fill="#151922"]').first()).toBeVisible()
  expect(errors).toEqual([])
})

test('composition theme changes all panels and common text together', async ({ page }) => {
  await page.goto('/editor')
  await page.getByRole('button', { name: 'Группы респондентов', exact: true }).click()
  const canvas = page.locator('.canvas-settings')
  await canvas.locator(':scope > summary').click()
  const theme = page.getByRole('checkbox', { name: 'Тёмная тема холста', exact: true })
  await expect(theme).toBeChecked()
  await page.getByText('Тёмная тема холста', { exact: true }).click()
  await expect(page.locator('.multiples-paper')).toHaveCSS('background-color', 'rgb(255, 255, 255)')
  await page.getByText('Тёмная тема холста', { exact: true }).click()
  await expect(page.locator('.multiples-paper')).toHaveCSS('background-color', 'rgb(21, 25, 34)')
  await expect(page.locator('[data-composition-text=title] .canvas-rich-text-display')).toHaveCSS('color', 'rgb(244, 244, 245)')
  for (const chart of await page.locator('.multiples-cell svg').all()) {
    await expect(chart.locator('rect[fill="#151922"]').first()).toBeVisible()
    await expect(chart.locator('text[fill="#f4f4f5"]').first()).toBeVisible()
  }
  await page.locator('.export-menu > summary').click()
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Скачать SVG' }).click()
  const content = await readFile((await (await download).path())!, 'utf8')
  expect(content).toContain('#151922')
  expect(content).toContain('#f4f4f5')
})
