import { expect, test, type Page } from '@playwright/test'
import { readFile } from 'node:fs/promises'

async function openEditor(page: Page) {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/editor')
  await page.getByRole('button', { name: 'Загрузка', exact: true }).click()
  await page.locator('.upload-card input').setInputFiles({ name: 'private-data.csv', mimeType: 'text/csv', buffer: Buffer.from('Secret year,Secret revenue\n2020,20\n2021,35\n2022,50') })
  await page.getByRole('button', { name: /Выбрать график/ }).click()
  await page.getByRole('button', { name: 'Настроить оформление →' }).click()
}
async function chooseOwn(page: Page, name: string) {
  await page.getByRole('button', { name: 'Шаблоны', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await expect(dialog.getByText('Открываем хранилище…')).toHaveCount(0)
  await dialog.getByRole('tab', { name: 'Мои', exact: true }).click()
  await dialog.getByRole('button', { name, exact: true }).click()
  return dialog
}

test('creates, persists, previews, applies, undoes, updates and exchanges personal templates', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await openEditor(page)
  await page.getByRole('button', { name: 'Шаблоны', exact: true }).click()
  let dialog = page.getByRole('dialog')
  await expect(dialog.getByRole('button', { name: 'Сохранить текущее оформление…' })).toBeEnabled()
  await dialog.getByRole('button', { name: 'Сохранить текущее оформление…' }).click()
  await dialog.getByRole('textbox', { name: 'Название шаблона' }).fill('Отчёт команды')
  await expect(dialog.getByRole('checkbox')).toHaveCount(1)
  await expect(dialog.getByRole('checkbox', { name: 'Сохранить также размер холста' })).not.toBeChecked()
  await expect(dialog.locator('.template-chart-preview .chart-canvas-shell')).toHaveAttribute('data-render-status', 'settled')
  await dialog.screenshot({ path: '/tmp/viiiz-template-create.png' })
  await dialog.getByRole('button', { name: 'Создать шаблон', exact: true }).click()
  await expect(dialog.getByRole('status')).toContainText('Шаблон сохранён')
  await dialog.getByRole('button', { name: 'Закрыть шаблоны' }).click()
  await page.reload()
  await openEditor(page)
  dialog = await chooseOwn(page, 'Отчёт команды')
  await dialog.locator('.template-menu summary').click()
  const download = page.waitForEvent('download')
  await dialog.getByRole('button', { name: 'Скачать', exact: true }).click()
  const file = await readFile((await (await download).path())!, 'utf8')
  expect(file).not.toContain('Secret')
  expect(JSON.parse(file)).toMatchObject({ version: 1, name: 'Отчёт команды', includeSize: false })
  await dialog.getByRole('button', { name: 'Закрыть шаблоны' }).click()

  await page.getByRole('button', { name: 'Шаблоны', exact: true }).click()
  dialog = page.getByRole('dialog')
  const before = await page.locator('.stage .chart-canvas-shell').innerText()
  await dialog.getByRole('button', { name: 'Для презентации', exact: true }).click()
  expect(await page.locator('.stage .chart-canvas-shell').innerText()).toBe(before)
  await expect(dialog.locator('.template-chart-preview .chart-canvas-shell')).toHaveAttribute('data-render-status', 'settled')
  await dialog.getByRole('button', { name: 'Применить', exact: true }).click()
  await expect(page.locator('.stage .chart-canvas-shell')).toContainText('20')
  await page.getByRole('button', { name: 'Отменить', exact: true }).click()
  await expect.poll(() => page.locator('.stage .chart-canvas-shell').innerText()).toBe(before)

  dialog = await chooseOwn(page, 'Отчёт команды')
  await dialog.locator('.template-menu summary').click()
  await dialog.getByRole('button', { name: 'Переименовать', exact: true }).click()
  await dialog.getByRole('textbox', { name: 'Название шаблона' }).fill('Обновлённый отчёт')
  await dialog.getByRole('button', { name: 'Сохранить название' }).click()
  await expect(dialog.getByRole('button', { name: 'Обновлённый отчёт', exact: true })).toBeVisible()
  await dialog.locator('.template-menu summary').click()
  await dialog.getByRole('button', { name: 'Обновить из текущего графика…' }).click()
  await expect(dialog.locator('.template-comparison svg')).toHaveCount(2)
  await dialog.getByRole('checkbox', { name: 'Сохранить также размер холста' }).check()
  await dialog.getByRole('button', { name: 'Обновить шаблон', exact: true }).click()
  await expect(dialog.getByRole('checkbox', { name: /Применить также размер холста/ })).toBeChecked()
  await dialog.screenshot({ path: '/tmp/viiiz-template-library.png' })
  await dialog.getByLabel('Файл шаблона').setInputFiles({ name: 'style.viiiz-template', mimeType: 'application/json', buffer: Buffer.from(file) })
  await expect(dialog.getByRole('button', { name: 'Отчёт команды', exact: true })).toBeVisible()
  await dialog.locator('.template-menu summary').click()
  await dialog.getByRole('button', { name: 'Удалить…' }).click()
  await dialog.getByRole('button', { name: 'Удалить шаблон', exact: true }).click()
  await expect(dialog.getByRole('button', { name: 'Отчёт команды', exact: true })).toHaveCount(0)
  expect(errors).toEqual([])
})

test('rejects invalid imports and keeps the library usable on narrow screens', async ({ page }) => {
  await openEditor(page)
  await page.getByRole('button', { name: 'Шаблоны', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByRole('tab', { name: 'Готовые', exact: true }).focus()
  await page.keyboard.press('ArrowRight')
  await expect(dialog.getByRole('tab', { name: 'Мои', exact: true })).toBeFocused()
  await expect(dialog.getByRole('button', { name: 'Создать первый шаблон' })).toBeVisible()
  await page.keyboard.press('ArrowLeft')
  await dialog.getByLabel('Файл шаблона').setInputFiles({ name: 'wrong.json', mimeType: 'application/json', buffer: Buffer.from('{"version":99}') })
  await expect(dialog.getByRole('alert')).toContainText('Не удалось открыть файл')
  await page.setViewportSize({ width: 600, height: 900 })
  await dialog.screenshot({ path: '/tmp/viiiz-template-mobile.png' })
  expect(await dialog.evaluate((node) => node.scrollWidth <= node.clientWidth)).toBe(true)
  await page.keyboard.press('Escape')
  await expect(dialog).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Шаблоны', exact: true })).toBeFocused()
})

test('offers a downloadable template when browser storage is unavailable', async ({ page }) => {
  await page.addInitScript(() => { Object.defineProperty(window, 'indexedDB', { value: { open() { throw new Error('Storage unavailable') } } }) })
  await openEditor(page)
  await page.getByRole('button', { name: 'Шаблоны', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await expect(dialog.getByRole('alert')).toContainText('Не удалось открыть хранилище')
  await dialog.getByRole('button', { name: 'Сохранить текущее оформление…' }).click()
  await dialog.getByRole('button', { name: 'Создать шаблон', exact: true }).click()
  await expect(dialog.getByRole('alert')).toContainText('Не удалось сохранить шаблон')
  const download = page.waitForEvent('download')
  await dialog.getByRole('button', { name: 'Скачать файл шаблона', exact: true }).click()
  const file = await readFile((await (await download).path())!, 'utf8')
  expect(JSON.parse(file)).toMatchObject({ format: 'viiiz-style-template', version: 1 })
})
