import { expect, test } from '@playwright/test'
import { readFile } from 'node:fs/promises'

test('captures mixed chart templates, previews the grid, applies to either scope and updates from the shortcut', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/editor')
  await page.locator('.upload-card input').setInputFiles({ name: 'private.csv', mimeType: 'text/csv', buffer: Buffer.from('Private year,Private value\n2020,20\n2021,35\n2022,50') })
  await page.getByRole('button', { name: /Выбрать график/ }).click()
  await page.getByRole('button', { name: 'Сетка графиков', exact: true }).click()
  await page.getByRole('button', { name: '3 колонки, 1 ряд', exact: true }).click()
  await page.getByRole('button', { name: 'Добавить график в ячейку 1' }).click()
  await page.getByRole('button', { name: 'Столбцы', exact: true }).click()
  await page.getByRole('button', { name: 'Добавить график в ячейку 2' }).click()
  await page.getByRole('button', { name: 'Линия', exact: true }).click()
  await page.getByRole('button', { name: /Настроить оформление/ }).click()
  await page.getByRole('button', { name: 'Вся композиция', exact: true }).click()
  const stage = page.locator('.stage')
  const panels = stage.locator('.multiples-cell.filled .chart-canvas-shell')
  const sizes = () => stage.locator('.multiples-cell.filled').evaluateAll((cells) => cells.map((cell) => {
    const title = [...cell.querySelectorAll('svg text')].find((node) => /^График [12]$/.test(node.textContent ?? ''))!
    return Number.parseFloat(getComputedStyle(title).fontSize)
  }))
  const original = await sizes()
  await page.getByRole('button', { name: 'Шаблоны', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await expect(dialog.getByRole('combobox', { name: 'Применить к' })).toHaveValue('composition')
  await expect(dialog.locator('.template-chart-preview .multiples-cell.filled')).toHaveCount(2)
  await dialog.getByRole('button', { name: 'Сохранить текущее оформление…' }).click()
  await dialog.getByRole('textbox', { name: 'Название шаблона' }).fill('Сетка отчёта')
  await dialog.getByRole('button', { name: 'Создать шаблон', exact: true }).click()
  await expect(dialog.getByRole('button', { name: 'Сетка отчёта', exact: true }).locator('[data-thumbnail-kind="bar"]')).toHaveCount(1)
  await expect(dialog.getByRole('button', { name: 'Сетка отчёта', exact: true }).locator('[data-thumbnail-kind="line"]')).toHaveCount(1)
  await dialog.screenshot({ path: '/tmp/viiiz-composition-template.png' })
  await dialog.locator('.template-menu summary').click()
  const download = page.waitForEvent('download')
  await dialog.getByRole('button', { name: 'Скачать', exact: true }).click()
  const saved = await readFile((await (await download).path())!, 'utf8')
  expect(saved).not.toContain('Private')
  expect(JSON.parse(saved).variants.map((variant: { sourceKind: string }) => variant.sourceKind)).toEqual(['bar', 'line'])
  await dialog.getByRole('tab', { name: 'Готовые', exact: true }).click()
  await dialog.getByRole('button', { name: 'Для презентации', exact: true }).click()
  expect(await sizes()).toEqual(original)
  await dialog.getByRole('button', { name: 'Применить', exact: true }).click()
  await expect.poll(sizes).toEqual([48, 48])
  await expect(panels.nth(0)).toHaveAttribute('data-chart-kind', 'bar')
  await expect(panels.nth(1)).toHaveAttribute('data-chart-kind', 'line')
  await expect(stage.locator('.multiples-cell')).toHaveCount(3)
  await page.getByRole('button', { name: 'Отменить', exact: true }).click()
  await expect.poll(sizes).toEqual(original)

  await page.getByRole('button', { name: 'Шаблоны', exact: true }).click()
  await dialog.getByRole('tab', { name: 'Мои', exact: true }).click()
  await dialog.getByRole('button', { name: 'Сетка отчёта', exact: true }).click()
  await dialog.getByRole('button', { name: 'Применить', exact: true }).click()
  await expect(page.locator('.template-applied')).toContainText('Сетка отчёта')
  await page.getByRole('button', { name: /Выбрать график 1:/ }).click()
  await page.getByRole('button', { name: 'Шаблоны', exact: true }).click()
  await expect(dialog.getByRole('combobox', { name: 'Применить к' })).toHaveValue('chart')
  await dialog.getByRole('button', { name: 'Для презентации', exact: true }).click()
  await dialog.getByRole('button', { name: 'Применить', exact: true }).click()
  await expect.poll(sizes).toEqual([48, original[1]])
  await page.getByRole('button', { name: 'Отменить', exact: true }).click()
  await expect.poll(sizes).toEqual(original)
  await page.getByRole('button', { name: 'Вся композиция', exact: true }).click()
  await page.getByText('Общий стиль всей композиции', { exact: true }).click()
  await page.getByRole('combobox', { name: 'Шрифт всех надписей', exact: true }).selectOption('Georgia, serif')
  await expect(page.locator('.template-applied')).toContainText('Оформление изменено')
  await page.getByRole('button', { name: 'Обновить из текущего оформления', exact: true }).click()
  await expect(dialog).toHaveAccessibleName('Обновить шаблон')
  await expect(dialog.getByRole('combobox', { name: 'Обновить из' })).toHaveValue('composition')
  await dialog.getByRole('button', { name: 'Обновить шаблон', exact: true }).click()
  await dialog.getByRole('button', { name: 'Закрыть шаблоны' }).click()
  await expect(page.locator('.template-applied')).not.toContainText('Оформление изменено')
  const template = await page.evaluate(async () => (await (await import('/src/features/chart-templates/storage.ts')).loadTemplates()).find((item) => item.name === 'Сетка отчёта'))
  expect(template?.style.titleText?.fontFamily).toBe('Georgia, serif')
  expect(template?.variants?.every((variant) => variant.style.titleText?.fontFamily === 'Georgia, serif')).toBe(true)
  await page.locator('.export-menu > summary').click()
  const exportDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Скачать SVG', exact: true }).click()
  const svg = await readFile((await (await exportDownload).path())!, 'utf8')
  expect(svg).toContain('График 1')
  expect(svg).toContain('График 2')
  expect(svg).toContain('Georgia')
  expect(errors).toEqual([])
})
