import { expect, test } from '@playwright/test'
import { readFile } from 'node:fs/promises'

test('connected scatter exposes independent X, Y and connection order in the editor', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/editor')
  await page.locator('.upload-card input').setInputFiles({ name: 'trajectory.csv', mimeType: 'text/csv', buffer: Buffer.from('x,y,order\n3,4,4\n1,2,1\n4,2,3\n1,5,2') })
  await page.getByRole('button', { name: /Выбрать график/ }).click()
  await page.getByRole('region', { name: 'Связи', exact: true }).getByRole('button', { name: 'Соединённая диаграмма рассеивания', exact: true }).click()
  await expect(page.getByRole('combobox', { name: 'X / горизонтальная ось', exact: true })).toHaveValue('x')
  await page.getByRole('combobox', { name: 'Порядок точек', exact: true }).selectOption('order')
  await page.getByRole('combobox', { name: 'Направление порядка', exact: true }).selectOption('desc')
  await page.getByRole('button', { name: 'Настроить оформление →' }).click()
  await expect(page.locator('.chart-canvas-shell')).toHaveAttribute('data-render-status', 'settled')
  await page.locator('summary').filter({ hasText: 'Точки и зависимости' }).click()
  await expect(page.getByRole('combobox', { name: 'Порядок точек', exact: true })).toHaveValue('order')
  await expect(page.getByRole('combobox', { name: 'Направление порядка', exact: true })).toHaveValue('desc')
  await page.getByRole('combobox', { name: 'Тип соединений', exact: true }).selectOption('dashed')
  await page.getByRole('checkbox', { name: 'Соединять через пропуски', exact: true }).press('Space')
  await expect(page.locator('.chart-canvas-shell')).toHaveAttribute('data-render-status', 'settled')
  await expect(page.locator('.chart-canvas svg path[stroke-dasharray]')).not.toHaveCount(0)
})

for (const connect of [false, true]) test(`connected scatter renders separate ordered paths with gaps=${!connect} and exports matching geometry`, async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.route('**/src/main.tsx', (route) => route.fulfill({ contentType: 'text/javascript', body: '' }))
  await page.goto('/editor')
  await page.evaluate(async (connect) => {
    await import('/src/index.css')
    await import('/src/App.css')
    const { renderConfig } = await import('/src/test-fixtures/chartAudit.browser.tsx')
    renderConfig('connected-scatter', { xField: 'x', yField: 'y', yFields: ['y'], scatterColorField: 'group', scatterOrderField: 'order', scatterConnectionWidth: 3, scatterConnectionOpacity: .8, missingMode: connect ? 'connect' : 'gap', showLegend: true, showValues: true, scatterLabelField: 'order', palette: ['#0072b2', '#e69f00'] }, { name: 'Trajectory', columns: ['x', 'y', 'order', 'group'], rows: [{ x: 3, y: 4, order: 4, group: 'A' }, { x: 1, y: 2, order: 1, group: 'A' }, { x: 4, y: 2, order: 3, group: 'A' }, { x: 1, y: 5, order: 2, group: 'A' }, { x: null, y: 3, order: 2.5, group: 'A' }, { x: 6, y: 1, order: 1, group: 'B' }, { x: 5, y: 3, order: 2, group: 'B' }] })
  }, connect)
  const canvas = page.locator('#chart-audit-host .chart-canvas-shell')
  await expect(canvas).toHaveAttribute('data-render-status', 'settled')
  const lines = canvas.locator('svg path[stroke-width="3"][fill="none"]')
  await expect(lines).toHaveCount(2)
  const paths = await lines.evaluateAll((nodes) => nodes.map((node) => node.getAttribute('d')!))
  expect(paths[0].match(/M/g)).toHaveLength(connect ? 1 : 2)
  expect(paths[1].match(/M/g)).toHaveLength(1)
  // The connection doubles back in X rather than sorting the scatter's X coordinates.
  const xs = [...paths[0].matchAll(/[ML]\s*([-\d.e]+)[ ,]+[-\d.e]+/gi)].map((match) => Number(match[1]))
  expect(xs).toHaveLength(4)
  expect(xs[0]).toBeCloseTo(xs[1])
  expect(xs[2]).toBeGreaterThan(xs[3])
  const marker = canvas.locator('svg path[fill="#0072b2"]').last()
  await marker.hover()
  await page.mouse.move(1, 1)
  await expect.poll(() => lines.evaluateAll((nodes) => nodes.map((node) => node.getAttribute('d')))).toEqual(paths)
  const bounds = await page.evaluate(async () => (await import('/src/test-fixtures/chartAudit.browser.tsx')).textBounds())
  expect(bounds.filter((item) => item.outside)).toEqual([])
  await page.screenshot({ path: `/tmp/viiiz-connected-scatter-${connect}.png` })
  const preview = await canvas.locator('svg path').evaluateAll((nodes) => nodes.map((node) => node.getAttribute('d')).sort())
  let download = page.waitForEvent('download')
  await page.evaluate(async () => (await import('/src/test-fixtures/chartAudit.browser.tsx')).exportSvg())
  const svg = await readFile((await (await download).path())!, 'utf8')
  const exported = await page.evaluate((svg) => [...new DOMParser().parseFromString(svg, 'image/svg+xml').querySelectorAll('path')].map((node) => node.getAttribute('d')).sort(), svg)
  expect(exported).toEqual(preview)
  download = page.waitForEvent('download')
  await page.evaluate(async () => (await import('/src/test-fixtures/chartAudit.browser.tsx')).exportPng())
  expect((await readFile((await (await download).path())!)).subarray(0, 8).toString('hex')).toBe('89504e470d0a1a0a')
  expect(errors).toEqual([])
})
