import { expect, test } from '@playwright/test'

test('demo dates open as editable calendar dates and keep date axes after saving', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/editor')
  await page.getByRole('button', { name: /^Временной ряд$/ }).click()
  const cell = page.locator('.review-table tbody tr').first().locator('td').nth(6)
  await expect(cell).toHaveText('01.01.1990')
  await cell.dblclick()
  const input = page.getByRole('textbox', { name: 'Изменить year, строка 1' })
  await expect(input).toHaveValue('01.01.1990')
  await expect(input).toHaveAttribute('placeholder', 'ДД.ММ.ГГГГ')
  await input.fill('02.02.2000')
  await input.press('Escape')
  await expect(cell).toHaveText('01.01.1990')
  await cell.dblclick()
  await input.fill('01.01.1989')
  await input.press('Enter')
  await expect(cell).toHaveText('01.01.1989')
  await cell.dblclick()
  await expect(input).toHaveValue('01.01.1989')
  await input.press('Enter')
  await page.getByRole('button', { name: /Выбрать график/ }).click()
  await page.getByRole('button', { name: /^Столбцы$/ }).click()
  await page.getByRole('combobox', { name: 'Период / ось X', exact: true }).selectOption('year')
  await expect(page.locator('.chart-canvas-shell')).toHaveAttribute('data-render-status', 'settled')
  await expect(page.locator('.chart-canvas svg')).not.toContainText(/GMT|стандартное время|Mon Jan/)
  await expect(page.locator('.chart-canvas svg text').filter({ hasText: /^1995$/ })).toHaveCount(1)
})

test('import date mask does not prevent edits in day.month.year format', async ({ page }) => {
  await page.goto('/editor')
  await page.locator('.upload-card input').setInputFiles({ name: 'dates.csv', mimeType: 'text/csv', buffer: Buffer.from('date,value\n1990-01-01,10\n1991-01-01,20\n1992-01-01,30') })
  await page.locator('.date-format-button').click()
  await page.getByRole('button', { name: 'YYYY-MM-DD', exact: true }).click()
  await page.getByRole('button', { name: /Применить/ }).click()
  const cell = page.locator('.review-table tbody tr').first().locator('td').nth(1)
  await cell.dblclick()
  const input = page.getByRole('textbox', { name: 'Изменить date, строка 1' })
  await expect(input).toHaveValue('01.01.1990')
  await input.fill('01.02.2000')
  await input.press('Enter')
  await expect(cell).toHaveText('01.02.2000')
  await expect(page.locator('.column-inspector .type-pill, .column-inspector .inspector-heading')).toContainText('Дата')
  await cell.dblclick()
  await expect(input).toHaveValue('01.02.2000')
  await input.press('Escape')
})
