import { expect, test, type Locator, type Page } from '@playwright/test'
import { readFile } from 'node:fs/promises'

const escaped = (value: string) => value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
const setCheckbox = async (checkbox: Locator, selected: boolean) => {
  if (await checkbox.isChecked() !== selected) await checkbox.press('Space')
}

async function failOnRuntimeErrors(page: Page) {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  page.on('console', (message) => {
    if (message.type() === 'error' || message.type() === 'warning' && message.text().includes("Can't get DOM width or height")) errors.push(message.text())
  })
  return () => expect(errors).toEqual([])
}

async function loadDemo(page: Page) {
  await page.goto('/editor')
  await page.getByRole('button', { name: /^Временной ряд$/ }).click()
  await expect(page.getByRole('heading', { name: 'Проверьте данные' })).toBeVisible()
  await page.getByRole('button', { name: /Выбрать график/ }).click()
  await expect(page.getByRole('heading', { name: 'Тип графика' })).toBeVisible()
}

async function expectRenderedChart(page: Page) {
  const svg = page.locator('.canvas-paper svg').first()
  await expect(svg).toBeVisible()
  const box = await svg.boundingBox()
  expect(box?.width).toBeGreaterThan(200)
  expect(box?.height).toBeGreaterThan(150)
}

async function openExport(page: Page) {
  await page.locator('.export-menu > summary').click()
}

test('selected columns can be deleted and restored from history', async ({ page }) => {
  await page.goto('/editor')
  await page.getByRole('button', { name: /^Временной ряд$/ }).click()
  const headers = page.locator('th.column-head')
  await expect(headers.first()).toBeVisible()
  const initialCount = await headers.count()
  const column = (await headers.nth(1).locator('.column-title strong').textContent())!.trim()
  await setCheckbox(page.getByRole('checkbox', { name: `Выбрать столбец ${column}` }), true)
  await page.getByRole('button', { name: 'Удалить столбцы (1)' }).click()
  await expect(headers).toHaveCount(initialCount - 1)
  await expect(page.getByText('Удалено столбцов: 1', { exact: true }).last()).toBeVisible()
  await page.getByRole('button', { name: 'Отменить' }).click()
  await expect(headers).toHaveCount(initialCount)
})

test('editor opens demo data, renders charts and exposes export actions', async ({ page }) => {
  const assertNoErrors = await failOnRuntimeErrors(page)
  await loadDemo(page)

  await page.getByRole('button', { name: /^Столбцы$/ }).click()
  await page.getByRole('button', { name: /Настроить оформление/ }).click()
  await openExport(page)
  await expect(page.getByRole('button', { name: 'Скачать PNG' })).toBeVisible()
  await expectRenderedChart(page)

  const svgDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Скачать SVG' }).click()
  const svg = await svgDownload
  await expect(svg.suggestedFilename()).toMatch(/\.svg$/)
  expect(await readFile(await svg.path()!, 'utf8')).toContain('@font-face')
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Скачать PNG' }).click()
  await expect((await download).suggestedFilename()).toMatch(/\.png$/)

  assertNoErrors()
})

test('waterfall renders cumulative steps, total and semantic controls', async ({ page }) => {
  const assertNoErrors = await failOnRuntimeErrors(page)
  await loadDemo(page)
  await page.getByRole('button', { name: 'Waterfall', exact: true }).click()
  await expectRenderedChart(page)
  await expect(page.locator('.canvas-paper svg text').filter({ hasText: 'Итого' })).toBeVisible()
  await page.getByRole('button', { name: /Настроить оформление/ }).click()
  await page.locator('summary').filter({ hasText: /^Компоновка столбцов$/ }).click()
  await expect(page.getByRole('checkbox', { name: 'Показывать итоговый столбец' })).toBeChecked()
  await expect(page.getByLabel('Подпись итога')).toHaveValue('Итого')
  await expect(page.locator('.bar-settings label').filter({ hasText: /^Рост/ })).toBeVisible()
  await expect(page.locator('.bar-settings label').filter({ hasText: /^Снижение/ })).toBeVisible()
  await page.locator('summary').filter({ hasText: /^Подписи значений$/ }).click()
  await page.getByRole('checkbox', { name: 'Показывать подписи значений' }).press('Space')
  await page.getByLabel('Что показывать').selectOption('both')
  await page.locator('.waterfall-label-settings').getByLabel('Положение').selectOption('top')
  await page.getByLabel('Знаки изменений').selectOption('plus-minus')
  await expect(page.getByRole('checkbox', { name: 'Показывать значение итога' })).toBeChecked()
  const valueLabel = page.locator('.canvas-paper svg text').filter({ hasText: /\+\d/ }).first()
  await expect(valueLabel).toBeVisible()
  const svgBox = await page.locator('.canvas-paper svg').boundingBox()
  const outsideLabelBoxes = await page.locator('.canvas-paper svg text').filter({ hasText: /\+\d/ }).evaluateAll((labels) => labels.map((label) => label.getBoundingClientRect().toJSON()))
  expect(svgBox).not.toBeNull()
  expect(outsideLabelBoxes.every((box) => box.top >= svgBox!.y - 1 && box.right <= svgBox!.x + svgBox!.width + 1)).toBe(true)
  const labelBox = await valueLabel.boundingBox()
  expect(labelBox).not.toBeNull()
  await page.mouse.click(labelBox!.x + labelBox!.width / 2, labelBox!.y + labelBox!.height / 2)
  const individual = page.locator('.value-label-editor')
  await expect(individual).toBeVisible()
  await expect(page.locator('.canvas-paper svg path[stroke="#6956e8"]')).toBeVisible()
  await individual.locator('header button').click()
  const generalStyleSummary = page.locator('.value-label-settings .text-style-editor > summary').first()
  await expect(generalStyleSummary).toContainText('Aa')
  await expect(generalStyleSummary).not.toContainText('px')
  const greenBars = page.locator('.canvas-paper svg path[fill="#36a476"]')
  const selectedBar = (await Promise.all([...Array(await greenBars.count()).keys()].map((index) => greenBars.nth(index).boundingBox())))
    .filter((box): box is { x: number; y: number; width: number; height: number } => box != null && box.height > 2)
    .sort((a, b) => b.height - a.height)[0]
  expect(selectedBar).not.toBeNull()
  await page.mouse.click(selectedBar!.x + 2, selectedBar!.y + 2)
  const selectedElement = page.locator('.element-editor').filter({ hasText: 'Выбран элемент' })
  await expect(selectedElement).toBeVisible()
  await expect(individual).toBeHidden()
  await expect(selectedElement.locator('code').first()).toHaveText('#36a476')
  await expect(page.locator('.bar-selection-editor code').first()).toHaveText('#36a476')
  await expect(page.locator('.canvas-paper svg path[stroke="#6956e8"][stroke-width="2"]')).toHaveCount(0)
  const barOpacities = () => greenBars.evaluateAll((bars) => bars.map((bar) => Number(bar.getAttribute('opacity') ?? bar.getAttribute('fill-opacity') ?? '1')))
  await expect.poll(barOpacities).toContain(.62)
  await expect.poll(barOpacities).toContain(1)
  await selectedElement.locator('header button').click()
  const purpleBars = page.locator('.canvas-paper svg path[fill="#6956e8"]')
  const totalBar = (await Promise.all([...Array(await purpleBars.count()).keys()].map((index) => purpleBars.nth(index).boundingBox())))
    .filter((box): box is { x: number; y: number; width: number; height: number } => box != null && box.height > 2)
    .sort((a, b) => b.height - a.height)[0]
  expect(totalBar).not.toBeNull()
  await page.mouse.click(totalBar!.x + 2, totalBar!.y + 2)
  await expect(selectedElement.locator('code').first()).toHaveText('#6956e8')
  await expect(page.locator('.bar-selection-editor code').first()).toHaveText('#6956e8')
  await selectedElement.locator('header button').click()
  await page.locator('.waterfall-label-settings').getByLabel('Положение').selectOption('inside-center')
  const insideLabelBox = await valueLabel.boundingBox()
  expect(insideLabelBox).not.toBeNull()
  await page.mouse.click(insideLabelBox!.x + insideLabelBox!.width / 2, insideLabelBox!.y + insideLabelBox!.height / 2)
  await expect(individual).toBeVisible()
  await individual.getByLabel('Текст подписи').fill('Особый шаг')
  await individual.getByLabel('Положение').selectOption('top')
  await expect(individual.locator('.text-style-editor > summary')).toContainText('Aa')
  await expect(individual.locator('.text-style-editor > summary')).not.toContainText('px')
  await expect(page.locator('.canvas-paper svg text').filter({ hasText: 'Особый шаг' })).toBeVisible()
  assertNoErrors()
})

test('Butterfly mirrors two measures around a shared category axis', async ({ page }) => {
  const assertNoErrors = await failOnRuntimeErrors(page)
  await page.goto('/editor')
  await page.getByRole('button', { name: 'До → после' }).click()
  await page.getByRole('button', { name: /Выбрать график/ }).click()
  await page.getByRole('button', { name: 'Butterfly', exact: true }).click()
  await expectRenderedChart(page)
  await expect(page.getByRole('group', { name: 'Левая сторона' }).getByRole('checkbox', { name: 'before' })).toBeChecked()
  await expect(page.getByRole('group', { name: 'Правая сторона' }).getByRole('checkbox', { name: 'after' })).toBeChecked()

  const category = page.locator('.canvas-paper svg text').filter({ hasText: /^Север$/ }).first()
  const categoryBox = await category.boundingBox()
  expect(categoryBox).not.toBeNull()
  const center = categoryBox!.x + categoryBox!.width / 2
  const leftPaths = page.locator('.canvas-paper svg path[fill="#0072b2"]')
  const rightPaths = page.locator('.canvas-paper svg path[fill="#e69f00"]')
  const leftBar = (await Promise.all([...Array(await leftPaths.count()).keys()].map((index) => leftPaths.nth(index).boundingBox()))).filter((box): box is NonNullable<typeof box> => box != null && box.width > 20).sort((a, b) => b.width - a.width)[0]
  const rightBar = (await Promise.all([...Array(await rightPaths.count()).keys()].map((index) => rightPaths.nth(index).boundingBox()))).filter((box): box is NonNullable<typeof box> => box != null && box.width > 20).sort((a, b) => b.width - a.width)[0]
  expect(leftBar).toBeTruthy()
  expect(rightBar).toBeTruthy()
  expect(leftBar!.x + leftBar!.width).toBeLessThanOrEqual(categoryBox!.x + 1)
  expect(rightBar!.x).toBeGreaterThanOrEqual(categoryBox!.x + categoryBox!.width - 1)
  const zeroBoxes = (await Promise.all([...Array(await page.locator('.canvas-paper svg text').filter({ hasText: /^0$/ }).count()).keys()].map((index) => page.locator('.canvas-paper svg text').filter({ hasText: /^0$/ }).nth(index).boundingBox()))).filter((box): box is NonNullable<typeof box> => box != null)
  expect(zeroBoxes.some((box) => box.x + box.width / 2 < center)).toBe(true)
  expect(zeroBoxes.some((box) => box.x + box.width / 2 > center)).toBe(true)
  const paperBox = await page.locator('.canvas-paper svg').boundingBox()
  const hundredBoxes = (await page.locator('.canvas-paper svg text').filter({ hasText: /^100$/ }).evaluateAll((items) => items.map((item) => item.getBoundingClientRect().toJSON()))).sort((a, b) => a.left - b.left)
  const scale = paperBox!.width / 1000
  expect(hundredBoxes[0].left).toBeCloseTo(paperBox!.x + 32 * scale, 0)
  expect(hundredBoxes.at(-1)!.right).toBeCloseTo(paperBox!.x + paperBox!.width - 24 * scale, 0)

  await page.getByRole('button', { name: /Настроить оформление/ }).click()
  await page.locator('summary').filter({ hasText: /^Оси, шкалы и подписи$/ }).click()
  await expect(page.getByLabel('Положение категорий')).toHaveValue('center')
  await page.locator('summary').filter({ hasText: /^Подписи значений$/ }).click()
  await setCheckbox(page.getByRole('checkbox', { name: 'Показывать подписи значений' }), true)
  await expect(page.locator('.canvas-paper svg text').filter({ hasText: /^42$/ }).first()).toBeVisible()
  const selectedBarIndex = (await Promise.all([...Array(await leftPaths.count()).keys()].map(async (index) => ({ index, box: await leftPaths.nth(index).boundingBox() })))).filter((item) => item.box && item.box.width > 20).sort((a, b) => b.box!.width - a.box!.width)[0].index
  await leftPaths.nth(selectedBarIndex).click({ force: true })
  await expect(page.locator('.series-editor')).toBeVisible()
  const selectedBarAfterRender = (await Promise.all([...Array(await leftPaths.count()).keys()].map(async (index) => ({ index, box: await leftPaths.nth(index).boundingBox() })))).filter((item) => item.box && item.box.width > 20).sort((a, b) => b.box!.width - a.box!.width)[0].index
  await leftPaths.nth(selectedBarAfterRender).click({ force: true })
  await expect(page.locator('.element-editor').filter({ hasText: 'Выбран элемент' })).toBeVisible()
  await expect(page.locator('.bar-selection-editor code').first()).toHaveText('#0072b2')
  assertNoErrors()
})

test('business difficulties example opens as a hierarchical treemap', async ({ page }) => {
  const assertNoErrors = await failOnRuntimeErrors(page)
  await page.goto('/editor')
  await page.getByRole('button', { name: 'Трудности бизнеса' }).click()
  await expect(page.getByRole('heading', { name: 'Проверьте данные' })).toBeVisible()
  await expect(page.getByRole('columnheader', { name: /Категория/ })).toBeVisible()
  await expect(page.getByRole('columnheader', { name: /Трудность/ })).toBeVisible()
  await expect(page.getByRole('columnheader', { name: /Процент/ })).toBeVisible()
  await page.getByRole('button', { name: /Выбрать график/ }).click()
  await expect(page.getByRole('button', { name: 'Treemap' })).toHaveClass(/active/)
  const mapping = page.locator('.chart-data-section')
  await expect(mapping.locator('label').filter({ hasText: /^Категория/ }).first().locator('select')).toHaveValue('Категория')
  await expect(mapping.locator('label').filter({ hasText: /^Подкатегория/ }).locator('select')).toHaveValue('Трудность')
  await expect(mapping.locator('label').filter({ hasText: /^Значение/ }).locator('select')).toHaveValue('Процент')
  await expectRenderedChart(page)
  await expect(page.locator('.canvas-paper svg text').filter({ hasText: 'Трудности бизнеса' })).toBeVisible()
  await expect(page.locator('.canvas-paper svg text').filter({ hasText: 'Проблемы' }).first()).toBeVisible()
  await expect(page.locator('.canvas-paper svg text').filter({ hasText: 'Затрудняюсь' }).first()).toBeVisible()
  expect(await page.locator('.canvas-paper svg').evaluate((svg) => {
    const label = [...svg.querySelectorAll('text')].find((text) => text.textContent?.includes('Проблемы'))
    if (!label) return false
    const labelBox = label.getBoundingClientRect(), x = labelBox.left + labelBox.width / 2, y = labelBox.top + labelBox.height / 2
    return [...svg.querySelectorAll('path')].some((path) => {
      const fill = path.getAttribute('fill') ?? ''
      if (!fill || fill === 'none' || fill === '#ffffff' || fill.includes('0,0,0,0')) return false
      const box = path.getBoundingClientRect()
      return x >= box.left && x <= box.right && y >= box.top && y <= box.bottom
    })
  })).toBe(true)
  await page.getByRole('button', { name: /Настроить оформление/ }).click()
  await expect(page.getByText('Компоновка Treemap', { exact: true })).toBeVisible()
  await expect(page.getByRole('checkbox', { name: 'Показывать название категории' })).toBeChecked()
  await expect(page.getByRole('checkbox', { name: 'Показывать итог категории' })).toBeChecked()
  await expect(page.getByRole('checkbox', { name: 'Показывать название блока' })).toBeChecked()
  await expect(page.getByRole('checkbox', { name: 'Показывать значение блока' })).not.toBeChecked()
  await expect(page.locator('summary').filter({ hasText: 'Текст общих категорий' })).toHaveCount(1)
  await expect(page.locator('summary').filter({ hasText: 'Текст блоков' })).toHaveCount(1)
  const blockGap = page.locator('label').filter({ hasText: 'Промежуток между блоками внутри категории' }).locator('input')
  await blockGap.fill('2')
  await blockGap.press('Enter')
  await expect(blockGap).toHaveValue('2')
  const groupGap = page.locator('label').filter({ hasText: 'Промежуток между категориями' }).locator('input')
  await groupGap.fill('17')
  await groupGap.press('Enter')
  await expect(groupGap).toHaveValue('17')
  await expect(page.locator('.treemap-label-settings').filter({ hasText: /^Общие категории/ }).getByLabel('Положение подписи')).toHaveValue('top-left')
  const blockPosition = page.locator('.treemap-label-settings').filter({ hasText: /^Блоки/ }).getByLabel('Положение подписи')
  await blockPosition.selectOption('center')
  await expect(blockPosition).toHaveValue('center')
  const leafLabel = page.locator('.canvas-paper svg text').filter({ hasText: 'Мало или нет' }).first()
  await leafLabel.click({ force: true })
  await expect(page.getByText('Выбрана общая категория', { exact: true })).toBeVisible()
  await expect(page.locator('.element-editor label').filter({ hasText: 'Цвет категории' })).toBeVisible()
  await expect(page.locator('.element-editor').getByRole('checkbox', { name: 'Показывать значение' })).toBeVisible()
  await leafLabel.click({ force: true })
  await expect(page.getByText('Выбран блок', { exact: true })).toBeVisible()
  await expect(page.locator('.element-editor label').filter({ hasText: 'Цвет блока' })).toBeVisible()
  await expect(page.locator('.element-editor').getByLabel('Положение')).toBeVisible()
  await expect(page.locator('.element-editor summary').filter({ hasText: 'Стиль этой подписи' })).toBeVisible()
  assertNoErrors()
})

test('treemap categories show a drop preview and can move to any target', async ({ page }) => {
  const assertNoErrors = await failOnRuntimeErrors(page)
  await page.goto('/editor')
  await page.getByRole('button', { name: 'Трудности бизнеса' }).click()
  await page.getByRole('button', { name: /Выбрать график/ }).click()
  await expectRenderedChart(page)

  const source = page.locator('.canvas-paper svg text').filter({ hasText: /^Другое/ }).first()
  const target = page.locator('.canvas-paper svg text').filter({ hasText: /Сейчас у меня нет/ }).first()
  const before = await source.boundingBox()
  const targetBox = await target.boundingBox()
  expect(before).not.toBeNull()
  expect(targetBox).not.toBeNull()

  await page.mouse.move(before!.x + before!.width / 2, before!.y + before!.height / 2)
  await page.mouse.down()
  await page.mouse.move(targetBox!.x + targetBox!.width / 4, targetBox!.y + targetBox!.height / 2, { steps: 12 })
  await expect(page.locator('.treemap-drag-preview')).toHaveText('Другое')
  await expect(page.locator('.treemap-drop-indicator')).toBeVisible()
  await expect.poll(async () => (await source.boundingBox())?.x).not.toBe(before!.x)
  await page.mouse.up()
  await expect(page.locator('.treemap-drag-preview')).toHaveCount(0)
  await expect(page.locator('.treemap-drop-indicator')).toHaveCount(0)
  const movedX = (await source.boundingBox())!.x
  expect(movedX).not.toBe(before!.x)
  await page.locator('.canvas-floating-menu').getByRole('button', { name: 'Отменить' }).click()
  await expect.poll(async () => (await source.boundingBox())?.x).toBeCloseTo(before!.x, 0)
  await page.locator('.canvas-floating-menu').getByRole('button', { name: 'Повторить' }).click()
  await expect.poll(async () => (await source.boundingBox())?.x).toBeCloseTo(movedX, 0)
  assertNoErrors()
})

test('design history separates sorting from value-label settings', async ({ page }) => {
  const assertNoErrors = await failOnRuntimeErrors(page)
  await page.goto('/editor')
  await page.getByRole('button', { name: 'Топ стран' }).click()
  await page.getByRole('button', { name: /Выбрать график/ }).click()
  await page.getByRole('button', { name: 'Столбцы', exact: true }).click()
  await page.getByRole('button', { name: /Настроить оформление/ }).click()

  await page.locator('summary').filter({ hasText: /^Компоновка столбцов$/ }).click()
  const sorting = page.getByLabel('Сортировка категорий')
  await sorting.selectOption('value-desc')
  await page.locator('summary').filter({ hasText: /^Подписи значений$/ }).click()
  const showValues = page.getByRole('checkbox', { name: 'Показывать подписи значений' })
  await showValues.press('Space')
  await expect(showValues).toBeChecked()
  await expect(sorting).toHaveValue('value-desc')

  const history = page.locator('.canvas-floating-menu')
  await history.getByRole('button', { name: 'Отменить' }).click()
  await expect(showValues).not.toBeChecked()
  await expect(sorting).toHaveValue('value-desc')
  await history.getByRole('button', { name: 'Отменить' }).click()
  await expect(sorting).toHaveValue('none')
  await history.getByRole('button', { name: 'Повторить' }).click()
  await history.getByRole('button', { name: 'Повторить' }).click()
  await expect(sorting).toHaveValue('value-desc')
  await expect(showValues).toBeChecked()
  assertNoErrors()
})

test('number affixes support all ticks, edge-only ticks and chart-value overrides', async ({ page }) => {
  const assertNoErrors = await failOnRuntimeErrors(page)
  await page.goto('/editor')
  await page.getByRole('button', { name: /^\u0422\u043e\u043f \u0441\u0442\u0440\u0430\u043d$/ }).click()
  await page.getByRole('button', { name: /\u0412\u044b\u0431\u0440\u0430\u0442\u044c \u0433\u0440\u0430\u0444\u0438\u043a/ }).click()
  await page.getByRole('button', { name: /^\u0421\u0442\u043e\u043b\u0431\u0446\u044b$/ }).click()
  await page.getByLabel('\u041f\u0435\u0440\u0438\u043e\u0434 / \u043e\u0441\u044c X').selectOption('place')
  await page.getByRole('button', { name: /\u041d\u0430\u0441\u0442\u0440\u043e\u0438\u0442\u044c \u043e\u0444\u043e\u0440\u043c\u043b\u0435\u043d\u0438\u0435/ }).click()

  await page.locator('summary').filter({ hasText: /^\u0424\u043e\u0440\u043c\u0430\u0442 \u0447\u0438\u0441\u0435\u043b$/ }).click()
  const affixGroups = page.locator('.number-affix-group')
  await affixGroups.nth(0).getByLabel('\u041f\u0440\u0435\u0444\u0438\u043a\u0441').fill('\u20bd')
  await affixGroups.nth(0).getByLabel('\u0421\u0443\u0444\u0444\u0438\u043a\u0441').fill(' \u0442\u044b\u0441.')
  await affixGroups.nth(1).getByLabel('\u041f\u0440\u0435\u0444\u0438\u043a\u0441').fill('X:')
  await affixGroups.nth(1).getByLabel('\u0421\u0443\u0444\u0444\u0438\u043a\u0441').fill(' \u043b\u0435\u0442')
  await affixGroups.nth(1).getByLabel('\u0413\u0434\u0435 \u043f\u043e\u043a\u0430\u0437\u044b\u0432\u0430\u0442\u044c').selectOption('first')

  await expect(page.getByLabel('\u041f\u0440\u0435\u0434\u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440 \u0430\u0444\u0444\u0438\u043a\u0441\u043e\u0432')).toContainText('X:6 \u043b\u0435\u0442 \u00b7 12 \u00b7 18')
  const yTicks = page.locator('.canvas-paper svg text').filter({ hasText: /^\u20bd(?:0|10|20|30|40) \u0442\u044b\u0441\.$/ })
  await expect.poll(() => yTicks.count()).toBeGreaterThan(2)
  await affixGroups.nth(0).getByLabel('\u0413\u0434\u0435 \u043f\u043e\u043a\u0430\u0437\u044b\u0432\u0430\u0442\u044c').selectOption('last')
  await expect(yTicks).toHaveCount(1)
  await expect.poll(() => page.locator('.canvas-paper svg text').filter({ hasText: /^(0|10|20|30)$/ }).count()).toBeGreaterThan(3)
  const edgeTickBox = await yTicks.first().boundingBox()
  const gridLeft = await page.locator('.canvas-paper svg path').evaluateAll((paths) => Math.min(...paths.map((path) => path.getBoundingClientRect()).filter((box) => box.width > 200 && box.height < 3).map((box) => box.left)))
  expect(edgeTickBox!.x).toBeLessThan(gridLeft)
  expect(edgeTickBox!.x + edgeTickBox!.width).toBeGreaterThan(gridLeft + 8)
  await page.locator('summary').filter({ hasText: /^\u041e\u0441\u0438, \u0448\u043a\u0430\u043b\u044b \u0438 \u043f\u043e\u0434\u043f\u0438\u0441\u0438$/ }).click()
  await page.getByLabel('\u041f\u043e\u043b\u043e\u0436\u0435\u043d\u0438\u0435 \u043e\u0441\u0438 Y').selectOption('right')
  const rightEdgeTickBox = await yTicks.first().boundingBox()
  const gridRight = await page.locator('.canvas-paper svg path').evaluateAll((paths) => Math.max(...paths.map((path) => path.getBoundingClientRect()).filter((box) => box.width > 200 && box.height < 3).map((box) => box.right)))
  expect(rightEdgeTickBox!.x).toBeLessThan(gridRight - 8)
  expect(rightEdgeTickBox!.x + rightEdgeTickBox!.width).toBeGreaterThan(gridRight)
  await page.getByLabel('\u041f\u043e\u043b\u043e\u0436\u0435\u043d\u0438\u0435 \u043e\u0441\u0438 X').selectOption('top')
  const xEdgeTick = page.locator('.canvas-paper svg text').filter({ hasText: /^X:1 \u043b\u0435\u0442$/ }).first()
  const xEdgeTickBox = await xEdgeTick.boundingBox()
  const gridTop = await page.locator('.canvas-paper svg path').evaluateAll((paths) => Math.min(...paths.map((path) => path.getBoundingClientRect()).filter((box) => box.height > 100 && box.width < 3).map((box) => box.top)))
  expect(xEdgeTickBox!.y + xEdgeTickBox!.height).toBeLessThanOrEqual(gridTop + 2)
  expect(xEdgeTickBox!.width).toBeGreaterThan(30)
  await page.getByLabel('\u041f\u043e\u043b\u043e\u0436\u0435\u043d\u0438\u0435 \u043e\u0441\u0438 X').selectOption('bottom')
  await page.getByLabel('\u041f\u043e\u043b\u043e\u0436\u0435\u043d\u0438\u0435 \u043e\u0441\u0438 Y').selectOption('left')
  await page.locator('summary').filter({ hasText: /^\u0424\u043e\u0440\u043c\u0430\u0442 \u0447\u0438\u0441\u0435\u043b$/ }).click()
  await affixGroups.nth(0).getByLabel('\u0413\u0434\u0435 \u043f\u043e\u043a\u0430\u0437\u044b\u0432\u0430\u0442\u044c').selectOption('all')

  await page.locator('summary').filter({ hasText: /^\u041f\u043e\u0434\u043f\u0438\u0441\u0438 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0439$/ }).click()
  await setCheckbox(page.getByRole('checkbox', { name: '\u041f\u043e\u0434\u043f\u0438\u0441\u0438 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0439' }), true)
  await expect.poll(() => page.locator('.canvas-paper svg text').filter({ hasText: /^\u20bd\d+(?:,\d+)? \u0442\u044b\u0441\.$/ }).count()).toBeGreaterThan(8)

  await page.locator('summary').filter({ hasText: /^\u0424\u043e\u0440\u043c\u0430\u0442 \u0447\u0438\u0441\u0435\u043b$/ }).click()
  await setCheckbox(page.getByRole('checkbox', { name: '\u041a\u0430\u043a \u043d\u0430 \u043e\u0441\u0438 Y' }), false)
  await affixGroups.nth(2).getByLabel('\u041f\u0440\u0435\u0444\u0438\u043a\u0441').fill('\u2248')
  await affixGroups.nth(2).getByLabel('\u0421\u0443\u0444\u0444\u0438\u043a\u0441').fill(' \u0435\u0434.')
  await expect.poll(() => page.locator('.canvas-paper svg text').filter({ hasText: /^\u2248\d+(?:,\d+)? \u0435\u0434\.$/ }).count()).toBeGreaterThan(3)
  await expect.poll(() => yTicks.count()).toBeGreaterThan(2)
  assertNoErrors()
})

test('direct labels can be controlled per series and survive axis and orientation changes', async ({ page }) => {
  const assertNoErrors = await failOnRuntimeErrors(page)
  await page.goto('/editor')
  await page.getByRole('button', { name: /^\u0422\u043e\u043f \u0441\u0442\u0440\u0430\u043d$/ }).click()
  await page.getByRole('button', { name: /\u0412\u044b\u0431\u0440\u0430\u0442\u044c \u0433\u0440\u0430\u0444\u0438\u043a/ }).click()
  await page.getByRole('button', { name: /^\u0421\u0442\u043e\u043b\u0431\u0446\u044b$/ }).click()
  await page.getByRole('button', { name: /\u041d\u0430\u0441\u0442\u0440\u043e\u0438\u0442\u044c \u043e\u0444\u043e\u0440\u043c\u043b\u0435\u043d\u0438\u0435/ }).click()

  await page.locator('summary').filter({ hasText: /^\u041b\u0435\u0433\u0435\u043d\u0434\u0430$/ }).click()
  await page.getByRole('tab', { name: '\u0421\u043f\u0440\u0430\u0432\u0430 \u0443 \u0440\u044f\u0434\u043e\u0432' }).click()
  const seriesCard = page.locator('.series-label-card').first()
  const seriesName = (await seriesCard.locator('strong').textContent())!.trim()
  const seriesToggle = seriesCard.getByRole('checkbox')
  await expect(seriesToggle).toBeChecked()
  await setCheckbox(seriesToggle, false)
  await expect(seriesCard.getByLabel('\u041f\u043e\u0434\u043f\u0438\u0441\u044c')).toHaveCount(0)
  await setCheckbox(seriesToggle, true)
  await seriesCard.locator('summary').filter({ hasText: '\u0418\u043d\u0434\u0438\u0432\u0438\u0434\u0443\u0430\u043b\u044c\u043d\u044b\u0439 \u0441\u0442\u0438\u043b\u044c' }).click()
  await seriesCard.getByLabel('\u0420\u0430\u0437\u043c\u0435\u0440').fill('24')
  await expect(seriesCard.getByRole('button', { name: '\u0418\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u044c \u043e\u0431\u0449\u0438\u0439 \u0441\u0442\u0438\u043b\u044c' })).toBeVisible()

  await page.locator('summary').filter({ hasText: /^\u041e\u0441\u0438, \u0448\u043a\u0430\u043b\u044b \u0438 \u043f\u043e\u0434\u043f\u0438\u0441\u0438$/ }).click()
  await page.getByLabel('\u041f\u043e\u043b\u043e\u0436\u0435\u043d\u0438\u0435 \u043e\u0441\u0438 Y').selectOption('right')
  await page.locator('summary').filter({ hasText: /^\u041b\u0435\u0433\u0435\u043d\u0434\u0430$/ }).click()
  await expect(page.getByRole('tab', { name: '\u0421\u043b\u0435\u0432\u0430 \u0443 \u0440\u044f\u0434\u043e\u0432' })).toHaveAttribute('aria-selected', 'true')

  await page.getByRole('button', { name: '\u2190 \u0422\u0438\u043f \u0433\u0440\u0430\u0444\u0438\u043a\u0430' }).click()
  await page.getByRole('button', { name: /^\u041b\u0438\u043d\u0435\u0439\u0447\u0430\u0442\u0430\u044f$/ }).click()
  await page.getByRole('button', { name: /\u041d\u0430\u0441\u0442\u0440\u043e\u0438\u0442\u044c \u043e\u0444\u043e\u0440\u043c\u043b\u0435\u043d\u0438\u0435/ }).click()
  await page.locator('summary').filter({ hasText: /^\u041e\u0441\u0438, \u0448\u043a\u0430\u043b\u044b \u0438 \u043f\u043e\u0434\u043f\u0438\u0441\u0438$/ }).click()
  await page.getByLabel('\u041f\u043e\u043b\u043e\u0436\u0435\u043d\u0438\u0435 \u0433\u043e\u0440\u0438\u0437\u043e\u043d\u0442\u0430\u043b\u044c\u043d\u043e\u0439 \u043e\u0441\u0438 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0439').selectOption('top')
  await page.locator('summary').filter({ hasText: /^\u041b\u0435\u0433\u0435\u043d\u0434\u0430$/ }).click()
  await page.getByRole('tab', { name: '\u041d\u0430\u0434 \u0440\u044f\u0434\u0430\u043c\u0438' }).click()
  await expect(page.getByRole('tab', { name: '\u041d\u0430\u0434 \u0440\u044f\u0434\u0430\u043c\u0438' })).toHaveAttribute('aria-selected', 'true')
  await expect(seriesCard.getByRole('checkbox')).toBeChecked()
  const horizontalLabel = page.locator('.canvas-paper svg text').filter({ hasText: new RegExp(`^${escaped(seriesName)}$`) }).first()
  const horizontalLabelBox = await horizontalLabel.boundingBox()
  const topValueTicks = await page.locator('.canvas-paper svg text').filter({ hasText: /^(0|10|20|30|40)$/ }).evaluateAll((items) => items.map((item) => item.getBoundingClientRect().toJSON()))
  expect(Math.max(...topValueTicks.map((box) => box.bottom))).toBeLessThanOrEqual(horizontalLabelBox!.y + 2)
  await expectRenderedChart(page)
  assertNoErrors()
})

test('country chart spacing is configurable and hidden headers return space to the plot', async ({ page }) => {
  const assertNoErrors = await failOnRuntimeErrors(page)
  await page.goto('/editor')
  await page.getByRole('button', { name: /^Топ стран$/ }).click()
  await page.getByRole('button', { name: /Выбрать график/ }).click()
  await page.getByRole('button', { name: /^Столбцы$/ }).click()
  await page.getByRole('button', { name: /Настроить оформление/ }).click()

  await page.locator('summary').filter({ hasText: /^Оси, шкалы и подписи$/ }).click()
  await setCheckbox(page.getByRole('checkbox', { name: 'Заголовок оси X' }), true)
  const countryTitle = page.locator('.canvas-paper svg text').filter({ hasText: /^country$/ }).first()
  const countryLabels = page.locator('.canvas-paper svg text').filter({ hasText: /^(США|Китай|Германия|Япония|Индия|Великобритания|Франция|Италия|Канада|Бразилия)$/ })
  const [countryTitleBox, countryLabelBoxes] = await Promise.all([countryTitle.boundingBox(), countryLabels.evaluateAll((items) => items.map((item) => item.getBoundingClientRect().toJSON()))])
  expect(countryTitleBox!.y).toBeGreaterThan(Math.max(...countryLabelBoxes.map((box) => box.bottom)) + 6)

  await page.locator('summary').filter({ hasText: /^Отступы и расстояния$/ }).click()
  await expect(page.getByLabel('Схема расстояний на холсте')).toBeVisible()
  const topTick = page.locator('.canvas-paper svg text').filter({ hasText: /^40$/ }).first()
  const plotTop = () => topTick.boundingBox().then((box) => box?.y ?? 0)
  const initialTop = await plotTop()

  await page.getByLabel('Подзаголовок → График').fill('80')
  await expect.poll(plotTop).toBeGreaterThan(initialTop + 20)

  await page.locator('summary').filter({ hasText: /^Заголовок и подзаголовок$/ }).click()
  await setCheckbox(page.getByRole('checkbox', { name: 'Показывать подзаголовок' }), false)
  await page.locator('summary').filter({ hasText: /^Отступы и расстояния$/ }).click()
  await expect(page.getByLabel('Заголовок → График')).toBeVisible()
  await expect(page.getByLabel('Подзаголовок → График')).toHaveCount(0)

  await page.locator('summary').filter({ hasText: /^Заголовок и подзаголовок$/ }).click()
  await setCheckbox(page.getByRole('checkbox', { name: 'Показывать заголовок' }), false)
  await expect.poll(plotTop).toBeLessThan(initialTop)

  await page.locator('summary').filter({ hasText: /^Отступы и расстояния$/ }).click()
  const map = page.getByLabel('Схема расстояний на холсте')
  await expect(map.getByText('Заголовок', { exact: true })).toHaveCount(0)
  await expect(map.getByText('Подзаголовок', { exact: true })).toHaveCount(0)
  await expect(page.getByLabel(/→ График$/)).toHaveCount(0)
  assertNoErrors()
})

test('axis labels can be hidden and empty axis rails disappear from the spacing map', async ({ page }) => {
  const assertNoErrors = await failOnRuntimeErrors(page)
  await page.goto('/editor')
  await page.getByRole('button', { name: /^Топ стран$/ }).click()
  await page.getByRole('button', { name: /Выбрать график/ }).click()
  await page.getByRole('button', { name: /^Столбцы$/ }).click()
  await page.getByRole('button', { name: /Настроить оформление/ }).click()

  const axesSummary = page.locator('summary').filter({ hasText: /^Оси, шкалы и подписи$/ })
  const spacingSummary = page.locator('summary').filter({ hasText: /^Отступы и расстояния$/ })
  await spacingSummary.click()
  const map = page.getByLabel('Схема расстояний на холсте')
  const countryLabels = page.locator('.canvas-paper svg text').filter({ hasText: /^(США|Китай|Германия|Япония|Индия|Великобритания|Франция|Италия|Канада|Бразилия)$/ })
  await expect(countryLabels).not.toHaveCount(0)
  await expect(map.getByText('Ось X', { exact: true })).toBeVisible()
  await expect(page.getByLabel('График → Подписи оси X')).toBeVisible()

  await axesSummary.click()
  await setCheckbox(page.getByRole('checkbox', { name: 'Подписи оси X', exact: true }), false)
  await expect(countryLabels).toHaveCount(0)
  await setCheckbox(page.getByRole('checkbox', { name: 'Заголовок оси Y', exact: true }), false)
  await spacingSummary.click()
  await expect(map.getByText('Ось X', { exact: true })).toHaveCount(0)
  await expect(map.getByText('Ось Y', { exact: true })).toBeVisible()
  await expect(page.getByLabel('Подписи оси Y → график')).toBeVisible()

  await axesSummary.click()
  await setCheckbox(page.getByRole('checkbox', { name: 'Подписи оси Y', exact: true }), false)
  await expect(page.locator('.canvas-paper svg text').filter({ hasText: /^(0|10|20|30|40)$/ })).toHaveCount(0)
  await spacingSummary.click()
  await expect(map.getByText('Ось Y', { exact: true })).toHaveCount(0)
  await expect(map.getByText('График', { exact: true })).toBeVisible()
  assertNoErrors()
})

test('horizontal axis title clears date labels and stays centred on vertical charts', async ({ page }) => {
  await loadDemo(page)
  await page.getByRole('button', { name: /^Линия$/ }).click()
  await page.getByRole('button', { name: /Настроить оформление/ }).click()
  await page.locator('summary').filter({ hasText: /^Оси, шкалы и подписи$/ }).click()
  await setCheckbox(page.getByRole('checkbox', { name: 'Заголовок оси X' }), true)

  const axisTitle = page.locator('.canvas-paper svg text').filter({ hasText: /^day$/ }).first()
  const labels = page.locator('.canvas-paper svg text').filter({ hasText: /^\d{2}\.\d{2}\.\d{4}$/ })
  const comment = page.locator('.canvas-paper svg text').filter({ hasText: /^Комментарий к графику$/ }).first()
  await expect(axisTitle).toBeVisible()
  const [titleBox, commentBox, labelBoxes] = await Promise.all([axisTitle.boundingBox(), comment.boundingBox(), labels.evaluateAll((items) => items.map((item) => item.getBoundingClientRect().toJSON()))])
  const labelsBottom = Math.max(...labelBoxes.map((box) => box.bottom))
  const labelsLeft = Math.min(...labelBoxes.map((box) => box.left)), labelsRight = Math.max(...labelBoxes.map((box) => box.right))
  expect(titleBox!.y).toBeGreaterThan(labelsBottom + 6)
  expect(Math.abs(titleBox!.x + titleBox!.width / 2 - (labelsLeft + labelsRight) / 2)).toBeLessThan(12)
  expect(commentBox!.y).toBeGreaterThan(titleBox!.y + titleBox!.height + 6)
})

test('color and date pickers keep controls stable at white and inside the popover', async ({ page }) => {
  await loadDemo(page)
  await page.getByRole('button', { name: /^Линия$/ }).click()
  await page.getByRole('button', { name: /Настроить оформление/ }).click()

  await page.locator('summary').filter({ hasText: /^Палитра$/ }).click()
  await page.locator('.custom-palette .hero-color-trigger').first().click()
  const colorPopover = page.locator('.hero-color-popover')
  const swatches = colorPopover.locator('.hero-color-swatches button')
  const initialSwatches = await swatches.evaluateAll((items) => items.map((item) => item.getAttribute('aria-label')))
  await colorPopover.getByRole('button', { name: 'Цвет #ffffff' }).click()
  const hue = colorPopover.getByRole('slider', { name: /оттенок/ })
  const hueField = colorPopover.locator('.hero-color-fields input').first()
  const hueBefore = await hueField.inputValue()
  await hue.press('ArrowRight')
  await expect(hueField).not.toHaveValue(hueBefore)
  expect(await swatches.evaluateAll((items) => items.map((item) => item.getAttribute('aria-label')))).toEqual(initialSwatches)
  await page.keyboard.press('Escape')

  await page.locator('summary').filter({ hasText: /^Оси, шкалы и подписи$/ }).click()
  await page.locator('.axis-scale-fields .hero-date-trigger').first().click()
  const datePopover = page.locator('.hero-date-popover')
  const nextMonth = datePopover.locator('[data-slot=calendar-nav-button]').nth(1)
  const [popoverBox, nextBox] = await Promise.all([datePopover.boundingBox(), nextMonth.boundingBox()])
  expect(nextBox!.x + nextBox!.width).toBeLessThanOrEqual(popoverBox!.x + popoverBox!.width - 8)
  expect(nextBox!.x).toBeGreaterThan(popoverBox!.x)
})

test('color settings use compact aligned controls without dead space', async ({ page }) => {
  await loadDemo(page)
  await page.getByRole('button', { name: /^Столбцы$/ }).click()
  await page.getByRole('button', { name: /Настроить оформление/ }).click()

  await page.locator('summary').filter({ hasText: /^Холст$/ }).click()
  const backgroundRow = page.locator('.canvas-background-control')
  const [backgroundBox, backgroundColorBox, resetBox] = await Promise.all([
    backgroundRow.boundingBox(),
    backgroundRow.locator('.hero-color-control').boundingBox(),
    backgroundRow.getByRole('button', { name: 'Сбросить' }).boundingBox(),
  ])
  expect(backgroundBox!.height).toBe(40)
  expect(backgroundColorBox!.height).toBe(40)
  expect(resetBox!.height).toBe(40)
  expect(resetBox!.x).toBeGreaterThan(backgroundColorBox!.x + backgroundColorBox!.width)
  await expect(backgroundRow.locator('.hero-color-control')).toHaveCSS('border-radius', '12px')
  await expect(backgroundRow.getByRole('button', { name: 'Сбросить' })).toHaveCSS('border-radius', '12px')

  await page.locator('summary').filter({ hasText: /^Основное$/ }).click()
  const seriesColor = page.locator('.settings-group').filter({ has: page.locator('summary', { hasText: /^Основное$/ }) }).locator('.hero-color-control')
  await expect(seriesColor).toHaveCSS('height', '40px')
  await expect(seriesColor.locator('.hero-color-chevron')).toBeVisible()

  await page.locator('summary').filter({ hasText: /^Палитра$/ }).click()
  await page.locator('.palette-presets').getByRole('button', { name: 'Монохромная' }).click()
  const paletteItem = page.locator('.custom-palette > span').first()
  const [triggerBox, swatchBox, removeBox] = await Promise.all([
    paletteItem.locator('.hero-color-trigger').boundingBox(),
    paletteItem.locator('.color-swatch').boundingBox(),
    paletteItem.locator('.palette-remove').boundingBox(),
  ])
  expect(triggerBox!.width).toBe(36)
  expect(triggerBox!.height).toBe(36)
  expect(swatchBox!.width).toBe(26)
  expect(swatchBox!.height).toBe(26)
  expect(removeBox!.width).toBe(18)
  await expect(paletteItem.locator('.hero-color-trigger')).toHaveCSS('border-radius', '12px')
  await expect(paletteItem.locator('.color-swatch')).toHaveCSS('border-radius', '6px')
  await expect(page.locator('.palette-base-color')).toHaveCSS('height', '40px')
})

test('HeroUI checkboxes stay left-aligned and tabs keep their pill layout', async ({ page }) => {
  await loadDemo(page)
  await page.getByRole('button', { name: /^Столбцы$/ }).click()
  await page.getByRole('button', { name: /Настроить оформление/ }).click()

  await page.locator('summary').filter({ hasText: /^Заголовок и подзаголовок$/ }).click()
  const checkbox = page.getByRole('checkbox', { name: 'Показывать заголовок' })
  const checkboxContent = checkbox.locator('xpath=ancestor::label')
  const checkboxControl = checkboxContent.locator('.checkbox__control')
  await expect(checkbox.locator('xpath=ancestor::div[@data-slot="checkbox"]')).toHaveClass(/checkbox--primary/)
  await expect(checkboxContent.locator(':scope > .checkbox__control > .checkbox__indicator')).toHaveCount(1)
  const [contentBox, controlBox] = await Promise.all([checkboxContent.boundingBox(), checkboxControl.boundingBox()])
  expect(contentBox!.height).toBeLessThanOrEqual(36)
  expect(controlBox!.x).toBeLessThan(contentBox!.x + 24)
  await expect(checkboxControl).toHaveCSS('background-color', 'rgb(105, 86, 232)')
  await expect(checkboxControl).toHaveCSS('border-top-color', 'rgb(105, 86, 232)')
  const settingsPanel = page.locator('.settings-panel')
  const initialScroll = await settingsPanel.evaluate((element) => element.scrollTop)
  await checkbox.press('Space')
  expect(await settingsPanel.evaluate((element) => element.scrollTop)).toBe(initialScroll)
  await expect(checkboxControl).toHaveCSS('border-top-width', '1px')
  await expect(checkboxControl).toHaveCSS('border-top-color', 'rgb(170, 166, 178)')

  await page.locator('summary').filter({ hasText: /^Легенда$/ }).click()
  const tabs = page.locator('.settings-tabs.legend-mode')
  await expect(tabs.locator('.tabs__list-container')).toHaveCSS('border-radius', '20px')
  await expect(tabs.locator('.tabs__indicator')).toHaveCSS('border-radius', '24px')
  await expect(tabs.locator('.tabs__list-container__scroll-prev')).toBeHidden()
  await expect(tabs.locator('.tabs__list-container__scroll-next')).toBeHidden()
})

test('every chart type in the picker renders without runtime errors', async ({ page }) => {
  const assertNoErrors = await failOnRuntimeErrors(page)
  await loadDemo(page)

  const chartNames = await page.locator('.chart-choice-grid button b').allTextContents()
  for (const name of chartNames) {
    const button = page.locator('.chart-choice-grid button').filter({ has: page.locator('b').filter({ hasText: new RegExp(`^${escaped(name)}$`) }) })
    await button.scrollIntoViewIfNeeded()
    await button.click()
    await expectRenderedChart(page)
  }

  assertNoErrors()
})

test('native line, area, indexed and seasonal kinds transition across native and legacy charts', async ({ page }) => {
  test.setTimeout(90_000)
  await page.route('https://fonts.googleapis.com/**', (route) => route.fulfill({ contentType: 'text/css', body: '' }))
  const assertNoErrors = await failOnRuntimeErrors(page)
  await loadDemo(page)
  await page.getByLabel('Период / ось X').selectOption('month')
  await expect(page.getByLabel('Период / ось X')).toHaveValue('month')
  for (const name of ['Линия', 'Сравнение по годам', 'Линия', 'Индекс к дате', 'Столбцы', 'Индекс к дате', 'Область', 'Сравнение по годам', 'Наклонный график', 'Сравнение по годам']) {
    const svg = page.locator('.canvas-paper svg').first()
    const previousSvg = await svg.innerHTML().catch(() => '')
    const button = page.locator('.chart-choice-grid button').filter({ has: page.locator('b').filter({ hasText: new RegExp(`^${escaped(name)}$`) }) })
    await button.click()
    await expect(button).toHaveClass(/active/)
    await expect.poll(() => svg.innerHTML()).not.toBe(previousSvg)
    await expectRenderedChart(page)
  }
  await page.getByRole('button', { name: /Настроить оформление/ }).click()
  await page.locator('summary').filter({ hasText: /^Сравнение по годам$/ }).click()
  const accent = page.locator('.line-variant-settings').getByRole('checkbox').first()
  const accented = await accent.isChecked()
  await accent.press('Space')
  await page.getByRole('button', { name: 'Отменить', exact: true }).click()
  await expect(accent).toBeChecked({ checked: accented })
  await page.getByRole('button', { name: 'Повторить', exact: true }).click()
  await expect(accent).toBeChecked({ checked: !accented })
  await page.evaluate(() => new Promise<void>((resolve) => requestAnimationFrame(() => requestAnimationFrame(() => resolve()))))
  await expectRenderedChart(page)
  await openExport(page)
  const svgDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Скачать SVG' }).click()
  const svg = await svgDownload
  expect(await readFile(await svg.path()!, 'utf8')).toContain('<svg')
  const pngDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Скачать PNG' }).click()
  await expect((await pngDownload).suggestedFilename()).toMatch(/\.png$/)

  await page.getByRole('button', { name: '← Тип графика' }).click()
  await page.locator('.chart-choice-grid button').filter({ has: page.locator('b').filter({ hasText: /^Индекс к дате$/ }) }).click()
  await expectRenderedChart(page)
  await page.getByRole('button', { name: /Настроить оформление/ }).click()
  await openExport(page)
  const indexedSvg = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Скачать SVG' }).click()
  expect(await readFile(await (await indexedSvg).path()!, 'utf8')).toContain('<svg')
  const indexedPng = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Скачать PNG' }).click()
  await expect((await indexedPng).suggestedFilename()).toMatch(/\.png$/)
  assertNoErrors()
})

test('native Slope keeps position and presentation history and exports the resolved scene', async ({ page }) => {
  test.setTimeout(90_000)
  const assertNoErrors = await failOnRuntimeErrors(page)
  await page.route('https://fonts.googleapis.com/**', (route) => route.fulfill({ contentType: 'text/css', body: '' }))
  await loadDemo(page)
  await page.getByLabel('Период / ось X').selectOption('month')
  await setCheckbox(page.getByRole('checkbox', { name: 'orders', exact: true }), true)
  await page.locator('.chart-choice-grid button').filter({ has: page.locator('b').filter({ hasText: /^Наклонный график$/ }) }).click()
  await expectRenderedChart(page)

  const positions = page.getByRole('group', { name: 'Позиции по оси X' }).getByRole('button')
  await expect(positions.filter({ has: page.locator('[aria-hidden="true"]') })).toHaveCount(0)
  await expect(page.getByText('Выбрано: 2 из 2', { exact: true })).toBeVisible()
  const selected = positions.filter({ has: page.locator('span') }).filter({ hasText: '✓' })
  await selected.first().click()
  await expect(page.getByText('Выбрано: 1 из 2', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Отменить', exact: true }).click()
  await expect(page.getByText('Выбрано: 2 из 2', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Повторить', exact: true }).click()
  await expect(page.getByText('Выбрано: 1 из 2', { exact: true })).toBeVisible()
  await positions.filter({ hasNotText: '✓' }).first().click()
  await expect(page.getByText('Выбрано: 2 из 2', { exact: true })).toBeVisible()

  await page.getByRole('button', { name: /Настроить оформление/ }).click()
  await page.locator('.series-settings .series-name-button').filter({ hasText: /^revenue$/ }).click()
  const seriesEditor = page.locator('.series-editor')
  await seriesEditor.getByLabel('Тип линии').selectOption('dashed')
  await page.getByRole('button', { name: 'Отменить', exact: true }).click()
  await expect(seriesEditor.getByLabel('Тип линии')).toHaveValue('solid')
  await page.getByRole('button', { name: 'Повторить', exact: true }).click()
  await expect(seriesEditor.getByLabel('Тип линии')).toHaveValue('dashed')
  await seriesEditor.getByLabel('Форма').selectOption('diamond')
  await page.getByRole('button', { name: 'Отменить', exact: true }).click()
  await expect(seriesEditor.getByLabel('Форма')).toHaveValue('circle')
  await page.getByRole('button', { name: 'Повторить', exact: true }).click()
  await expect(seriesEditor.getByLabel('Форма')).toHaveValue('diamond')
  await page.getByRole('button', { name: 'Снять выделение' }).click()
  await page.locator('summary').filter({ hasText: /^Наклонный график$/ }).click()
  const values = page.getByRole('checkbox', { name: 'Подписывать значения' })
  const names = page.getByRole('checkbox', { name: 'Подписывать названия рядов справа' })
  const scale = page.getByRole('checkbox', { name: 'Показывать подписи шкалы Y' })
  await setCheckbox(values, false)
  await setCheckbox(names, false)
  await setCheckbox(scale, true)
  await expect(page.locator('.canvas-paper svg text').filter({ hasText: /^revenue$/ })).toHaveCount(0)
  await page.getByRole('button', { name: 'Отменить', exact: true }).click()
  await expect(scale).not.toBeChecked()
  await page.getByRole('button', { name: 'Повторить', exact: true }).click()
  await expect(scale).toBeChecked()

  await page.locator('summary').filter({ hasText: /^Оси, шкалы и подписи$/ }).click()
  await page.getByLabel('Положение оси X').selectOption('top')
  await expect(page.getByLabel('Положение оси X')).toHaveValue('top')
  await page.getByRole('button', { name: 'Отменить', exact: true }).click()
  await expect(page.getByLabel('Положение оси X')).toHaveValue('bottom')
  await page.getByRole('button', { name: 'Повторить', exact: true }).click()
  await expect(page.getByLabel('Положение оси X')).toHaveValue('top')

  await openExport(page)
  const svgDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Скачать SVG' }).click()
  const svg = await readFile(await (await svgDownload).path()!, 'utf8')
  expect(svg).toContain('<svg')
  expect(svg).not.toContain('__slope-guides__')
  const pngDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Скачать PNG' }).click()
  expect((await readFile(await (await pngDownload).path()!)).byteLength).toBeGreaterThan(1000)
  assertNoErrors()
})

test('Seasonal legend modes keep accent, ordinary items, and direct labels independent', async ({ page }) => {
  test.setTimeout(90_000)
  const assertNoErrors = await failOnRuntimeErrors(page)
  const assertSeasonalExport = async (included: string[], excluded: string[] = []) => {
    const exportMenu = page.locator('.export-menu')
    if (!(await exportMenu.evaluate((element) => (element as HTMLDetailsElement).open))) await openExport(page)
    const svgDownload = page.waitForEvent('download')
    await page.getByRole('button', { name: 'Скачать SVG' }).click()
    const svg = await readFile(await (await svgDownload).path()!, 'utf8')
    for (const label of included) expect(svg).toContain(label)
    for (const label of excluded) expect(svg).not.toContain(label)
    const pngDownload = page.waitForEvent('download')
    await page.getByRole('button', { name: 'Скачать PNG' }).click()
    expect((await readFile(await (await pngDownload).path()!)).byteLength).toBeGreaterThan(1000)
  }
  await page.route('https://fonts.googleapis.com/**', (route) => route.fulfill({ contentType: 'text/css', body: '' }))
  await loadDemo(page)
  await page.getByLabel('Период / ось X').selectOption('month')
  const seasonal = page.locator('.chart-choice-grid button').filter({ has: page.locator('b').filter({ hasText: /^Сравнение по годам$/ }) })
  const previousSvg = await page.locator('.canvas-paper svg').first().innerHTML()
  await seasonal.click()
  await expect.poll(() => page.locator('.canvas-paper svg').first().innerHTML()).not.toBe(previousSvg)
  await page.getByRole('button', { name: /Настроить оформление/ }).click()
  await page.locator('summary').filter({ hasText: /^Легенда$/ }).click()

  await page.getByText('Обычная', { exact: true }).click()
  const standardItems = page.locator('.legend-settings .legend-options:not(.direct-legend-options)')
  const currentCard = standardItems.locator('.series-label-card').first()
  const othersCard = standardItems.locator('.series-label-card').last()
  await expect(page.locator('.canvas-paper svg text').filter({ hasText: /^Остальные$/ })).toBeVisible()
  await assertSeasonalExport(['2024', 'Остальные'])
  await othersCard.getByLabel('Подпись').fill('Предыдущие годы')
  await currentCard.getByLabel('Подпись').fill('Текущий год')
  await expect(page.locator('.canvas-paper svg text').filter({ hasText: /^Предыдущие годы$/ })).toBeVisible()
  await expect(page.locator('.canvas-paper svg text').filter({ hasText: /^Текущий год$/ })).toBeVisible()
  await assertSeasonalExport(['Текущий год', 'Предыдущие годы'])

  await page.getByRole('button', { name: 'Отменить', exact: true }).click()
  await expect(currentCard.getByLabel('Подпись')).toHaveValue('')
  await page.getByRole('button', { name: 'Повторить', exact: true }).click()
  await expect(currentCard.getByLabel('Подпись')).toHaveValue('Текущий год')
  await setCheckbox(othersCard.getByRole('checkbox'), false)
  await expect(page.locator('.canvas-paper svg text').filter({ hasText: /^Предыдущие годы$/ })).toHaveCount(0)
  await page.getByRole('button', { name: 'Отменить', exact: true }).click()
  await expect(othersCard.getByRole('checkbox')).toBeChecked()
  await page.getByRole('button', { name: 'Повторить', exact: true }).click()
  await expect(othersCard.getByRole('checkbox')).not.toBeChecked()
  await assertSeasonalExport(['Текущий год'], ['Предыдущие годы'])

  await page.getByText('Справа у рядов', { exact: true }).click()
  const directItems = page.locator('.direct-legend-options .series-label-card')
  await expect(directItems.filter({ has: page.getByRole('checkbox', { name: '2024', exact: true }) }).getByRole('checkbox')).toBeChecked()
  const priorYear = directItems.filter({ has: page.getByRole('checkbox', { name: '2023', exact: true }) }).getByRole('checkbox')
  await expect(priorYear).not.toBeChecked()
  await setCheckbox(priorYear, true)
  await page.getByRole('button', { name: 'Отменить', exact: true }).click()
  await expect(priorYear).not.toBeChecked()
  await page.getByRole('button', { name: 'Повторить', exact: true }).click()
  await expect(priorYear).toBeChecked()
  await assertSeasonalExport(['2023', 'Текущий'], ['Остальные'])

  await page.getByText('Обычная', { exact: true }).click()
  await expect(currentCard.getByLabel('Подпись')).toHaveValue('Текущий год')
  await expect(othersCard.getByRole('checkbox')).not.toBeChecked()
  await page.getByText('Без легенды', { exact: true }).click()
  await expect(page.locator('.canvas-paper svg text').filter({ hasText: /^(Текущий год|Предыдущие годы)$/ })).toHaveCount(0)

  await page.getByText('Обычная', { exact: true }).click()
  await page.getByRole('button', { name: 'Сбросить легенду' }).click()
  await page.getByText('Обычная', { exact: true }).click()
  await expect(page.locator('.series-label-card').filter({ has: page.getByRole('checkbox', { name: 'Остальные', exact: true }) }).getByRole('checkbox')).toBeChecked()
  await expect(page.locator('.series-label-card').filter({ has: page.getByRole('checkbox', { name: '2024', exact: true }) }).getByLabel('Подпись')).toHaveValue('')

  await page.locator('summary').filter({ hasText: /^Сравнение по годам$/ }).click()
  const accent = page.locator('.line-variant-settings').getByRole('checkbox', { name: '2023', exact: true })
  await setCheckbox(accent, true)
  await page.locator('summary').filter({ hasText: /^Легенда$/ }).click()
  await expect(page.locator('.legend-settings .series-label-card').filter({ has: page.getByRole('checkbox', { name: '2023', exact: true }) })).toBeVisible()

  await page.locator('.legend-settings .legend-options:not(.direct-legend-options) .series-label-card').last().getByLabel('Подпись').fill('Сохранённая группа')
  await page.getByRole('button', { name: '← Тип графика' }).click()
  const line = page.locator('.chart-choice-grid button').filter({ has: page.locator('b').filter({ hasText: /^Линия$/ }) })
  await line.click()
  await expectRenderedChart(page)
  await seasonal.click()
  await expectRenderedChart(page)
  await page.getByRole('button', { name: /Настроить оформление/ }).click()
  await page.locator('summary').filter({ hasText: /^Легенда$/ }).click()
  await expect(page.locator('.legend-settings .legend-options:not(.direct-legend-options) .series-label-card').last().getByLabel('Подпись')).toHaveValue('Сохранённая группа')

  await page.getByText('Справа у рядов', { exact: true }).click()
  await setCheckbox(page.locator('.direct-legend-options .series-label-card').filter({ has: page.getByRole('checkbox', { name: '2023', exact: true }) }).getByRole('checkbox'), true)
  await page.getByRole('button', { name: '← Тип графика' }).click()
  await line.click()
  await seasonal.click()
  await page.getByRole('button', { name: /Настроить оформление/ }).click()
  await page.locator('summary').filter({ hasText: /^Легенда$/ }).click()
  await expect(page.locator('.direct-legend-options .series-label-card').filter({ has: page.getByRole('checkbox', { name: '2023', exact: true }) }).getByRole('checkbox')).toBeChecked()

  await page.getByRole('button', { name: '← Тип графика' }).click()
  await page.locator('.chart-choice-grid button').filter({ has: page.locator('b').filter({ hasText: /^Наклонный график$/ }) }).click()
  await expectRenderedChart(page)
  await seasonal.click()
  await expectRenderedChart(page)
  await page.locator('.chart-choice-grid button').filter({ has: page.locator('b').filter({ hasText: /^Столбцы$/ }) }).click()
  await expectRenderedChart(page)
  assertNoErrors()
})

test('special charts expose clear data roles and render with useful defaults', async ({ page }) => {
  await loadDemo(page)
  await page.getByRole('button', { name: 'Гантельная' }).click()
  await expect(page.getByLabel('Начальное значение')).not.toHaveValue('')
  await expect(page.getByLabel('Конечное значение')).not.toHaveValue('')
  await expect.poll(() => page.locator('.canvas-paper svg path, .canvas-paper svg line').count()).toBeGreaterThan(10)
  await page.getByRole('button', { name: /Настроить оформление/ }).click()
  await page.locator('summary').filter({ hasText: /^Оси, шкалы и подписи$/ }).click()
  await setCheckbox(page.getByRole('checkbox', { name: 'Заголовок оси Y', exact: true }), true)
  await page.locator('summary').filter({ hasText: /^Отступы и расстояния$/ }).click()
  await expect(page.getByLabel('График → Подписи оси Y')).toBeVisible()
  await expect(page.getByLabel('Подписи оси X → график')).toBeVisible()
  const axisTitle = page.locator('.canvas-paper svg text').filter({ hasText: /^(profit|revenue)$/ }).first()
  const comment = page.locator('.canvas-paper svg text').filter({ hasText: /^Комментарий к графику$/ }).first()
  const tickLabels = page.locator('.canvas-paper svg text').filter({ hasText: /^(0|50|100|150|200|250)$/ })
  await expect(axisTitle).toBeVisible()
  const [titleBox, commentBox, ticks] = await Promise.all([axisTitle.boundingBox(), comment.boundingBox(), tickLabels.evaluateAll((items) => items.map((item) => item.getBoundingClientRect().toJSON()))])
  const tickLeft = Math.min(...ticks.map((box) => box.left)), tickRight = Math.max(...ticks.map((box) => box.right))
  const tickBottom = Math.max(...ticks.map((box) => box.bottom))
  expect(Math.abs((titleBox!.x + titleBox!.width / 2) - (tickLeft + tickRight) / 2)).toBeLessThan(12)
  expect(titleBox!.y).toBeGreaterThan(tickBottom + 6)
  expect(commentBox!.y).toBeGreaterThan(titleBox!.y + titleBox!.height + 12)

  await page.getByRole('button', { name: '← Тип графика' }).click()
  await page.getByRole('button', { name: 'Диапазон между линиями' }).click()
  await expect(page.getByLabel('Нижняя граница')).not.toHaveValue('')
  await expect(page.getByLabel('Верхняя граница')).not.toHaveValue('')
  await expect.poll(() => page.locator('.canvas-paper svg path, .canvas-paper svg polygon').count()).toBeGreaterThan(10)
})

test('scatter and bubble defaults keep axis/grid controls available on the editor canvas', async ({ page }) => {
  const assertNoErrors = await failOnRuntimeErrors(page)
  await loadDemo(page)

  await page.getByRole('button', { name: 'Точечный' }).click()
  await expectRenderedChart(page)
  await page.getByRole('button', { name: /Настроить оформление/ }).click()
  await openExport(page)
  await expect(page.getByRole('button', { name: 'Скачать PNG' })).toBeVisible()

  await page.getByRole('button', { name: '← Тип графика' }).click()
  await page.getByRole('button', { name: 'Пузырьковая диаграмма' }).click()
  await expectRenderedChart(page)
  await page.getByRole('button', { name: /Настроить оформление/ }).click()
  await page.locator('summary').filter({ hasText: /^Оси, шкалы и подписи$/ }).click()
  await expect(page.getByLabel('Стиль заголовков осей')).toBeVisible()

  assertNoErrors()
})

test('chart choice and design inspector stay focused and keyboard accessible', async ({ page }) => {
  await loadDemo(page)
  await expect(page.locator('.chart-picker')).toBeVisible()
  await expect(page.locator('.settings-panel')).toBeHidden()

  await page.getByRole('button', { name: /^Линия$/ }).click()
  await expect(page.locator('.chart-picker')).toBeVisible()
  await expect(page.locator('.settings-panel')).toBeHidden()
  await page.getByRole('button', { name: /Настроить оформление/ }).click()
  await expect(page.locator('.chart-picker')).toBeHidden()
  await expect(page.locator('.settings-panel')).toBeVisible()

  const canvasSummary = page.locator('summary').filter({ hasText: /^Холст$/ })
  await canvasSummary.hover()
  await expect(canvasSummary).toHaveCSS('background-color', 'rgb(255, 255, 255)')
  await expect(canvasSummary).toHaveCSS('border-radius', '12px')
  await expect(canvasSummary.locator('xpath=..')).toHaveCSS('overflow', 'clip')

  const markers = page.getByRole('checkbox', { name: 'Показывать маркеры' })
  await markers.focus()
  await page.keyboard.press('Space')
  await expect(markers).toBeChecked()
  await expect(markers).toBeFocused()
})

test('text alignment controls apply reliably on the canvas', async ({ page }) => {
  await loadDemo(page)
  await page.getByRole('button', { name: /Настроить оформление/ }).click()
  await page.locator('.canvas-paper svg text').filter({ hasText: /^Заголовок графика$/ }).click()
  const editor = page.locator('.canvas-rich-text')
  await expect(editor).toBeVisible()
  await page.getByRole('button', { name: 'Выровнять по центру' }).click()
  await expect(editor).toHaveCSS('text-align', 'center')
  await page.getByRole('button', { name: 'Выровнять справа' }).click()
  await expect(editor).toHaveCSS('text-align', 'right')
  const size = page.locator('.text-size-field input')
  await expect(size).toHaveValue('42')
  await page.getByRole('button', { name: 'Уменьшить размер' }).click()
  await expect(size).toHaveValue('41')
})

test('selected heading fragment keeps its own font, size, emphasis and color', async ({ page }) => {
  await loadDemo(page)
  await page.getByRole('button', { name: /Настроить оформление/ }).click()
  await page.locator('.canvas-paper svg text').filter({ hasText: /^Подзаголовок графика$/ }).click()
  const editor = page.locator('.canvas-rich-text-content')
  await editor.evaluate((element) => {
    const text = element.firstChild
    if (!text) throw new Error('Subtitle text is missing')
    const start = text.textContent?.indexOf('графика') ?? -1
    const range = document.createRange()
    range.setStart(text, start)
    range.setEnd(text, start + 'графика'.length)
    const selection = window.getSelection()
    selection?.removeAllRanges()
    selection?.addRange(range)
    element.dispatchEvent(new MouseEvent('mouseup', { bubbles: true }))
  })

  await page.locator('select[title="Шрифт текста"]').selectOption('Georgia, serif')
  await page.getByRole('button', { name: 'Увеличить размер' }).click()
  await page.getByRole('button', { name: 'Жирный' }).click()
  await page.getByRole('button', { name: 'Курсив' }).click()
  await page.getByRole('button', { name: 'Цвет текста' }).click()
  await page.getByRole('button', { name: 'Цвет #6956e8' }).click()

  const styles = await editor.evaluate((element) => {
    const walker = document.createTreeWalker(element, NodeFilter.SHOW_TEXT)
    const textNodes: Text[] = []
    while (walker.nextNode()) textNodes.push(walker.currentNode as Text)
    const selected = textNodes.find((node) => node.textContent === 'графика')
    const regular = textNodes.find((node) => node.textContent?.includes('Подзаголовок'))
    if (!selected?.parentElement || !regular?.parentElement) throw new Error('Formatted fragments are missing')
    const selectedStyle = getComputedStyle(selected.parentElement)
    const regularStyle = getComputedStyle(regular.parentElement)
    return {
      selected: { family: selectedStyle.fontFamily, size: selectedStyle.fontSize, weight: selectedStyle.fontWeight, italic: selectedStyle.fontStyle, color: selectedStyle.color },
      regular: { family: regularStyle.fontFamily, size: regularStyle.fontSize, weight: regularStyle.fontWeight, italic: regularStyle.fontStyle, color: regularStyle.color },
    }
  })
  expect(styles.selected.family).toContain('Georgia')
  expect(styles.selected.size).toBe('26px')
  expect(Number(styles.selected.weight)).toBeGreaterThanOrEqual(600)
  expect(styles.selected.italic).toBe('italic')
  expect(styles.selected.color).toBe('rgb(105, 86, 232)')
  expect(styles.regular.family).not.toContain('Georgia')
  expect(styles.regular.size).toBe('25px')
  expect(styles.regular.italic).toBe('normal')
  expect(styles.regular.color).not.toBe('rgb(105, 86, 232)')
})

test('category label editor preserves explicit lines and adapts to horizontal bars', async ({ page }) => {
  await loadDemo(page)
  await page.getByRole('button', { name: 'Линейчатая', exact: true }).click()
  const label = page.locator('.canvas-paper svg text').filter({ hasText: /^01\.01\.2025$/ }).first()
  await label.click()
  await label.click()
  const editor = page.locator('.canvas-rich-text-content')
  await expect(editor).toBeVisible()
  await expect(editor).toHaveCSS('white-space', 'pre-wrap')
  await editor.fill('Центр мира\nэто я и моя подруга')
  await expect.poll(() => editor.evaluate((element) => (element as HTMLElement).innerText)).toBe('Центр мира\nэто я и моя подруга')
})

test('category label editor follows the vertical axis label position', async ({ page }) => {
  await loadDemo(page)
  await page.getByRole('button', { name: /^Столбцы$/ }).click()
  const label = page.locator('.canvas-paper svg text').filter({ hasText: /^01\.01\.2025$/ }).first()
  await label.click()
  await label.click()
  const editor = page.locator('.canvas-rich-text-content')
  await expect(editor).toBeVisible()
  await expect(editor).toHaveCSS('white-space', 'pre-wrap')
  await editor.fill('Подпись категории\nна второй строке')
  await expect.poll(() => editor.evaluate((element) => (element as HTMLElement).innerText)).toBe('Подпись категории\nна второй строке')
})

test('formatted title exports as native SVG text with its selected font', async ({ page }) => {
  await loadDemo(page)
  await page.getByRole('button', { name: /Настроить оформление/ }).click()
  await page.locator('.canvas-paper svg text').filter({ hasText: /^Заголовок графика$/ }).click()
  const editor = page.locator('.canvas-rich-text-content')
  await editor.evaluate((element) => {
    element.innerHTML = 'Заголовок <span style="background-color: #6956e8">графика</span>'
    element.dispatchEvent(new InputEvent('input', { bubbles: true, inputType: 'insertText' }))
  })
  await page.locator('select[title="Шрифт текста"]').selectOption('Onest, sans-serif')
  await openExport(page)
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Скачать SVG' }).click()
  const svg = await readFile(await (await download).path()!, 'utf8')
  expect(svg).toContain('Заголовок')
  expect(svg).toContain('графика')
  expect(svg).not.toContain('<foreignObject')
  expect(svg).toMatch(/font-family[=:]\s*['"]?Onest/i)
  expect(svg).toMatch(/@font-face\s*{[^}]*font-family:\s*['"]Onest/i)
  expect(svg).toMatch(/<rect[^>]*fill="(?:#6956e8|rgb\(105, 86, 232\))"/i)
  const backgrounds = [...svg.matchAll(/<rect[^>]*width="([^"]+)"[^>]*fill="(?:#6956e8|rgb\(105, 86, 232\))"/gi)]
  expect(backgrounds.some(([, width]) => Number(width) < 250)).toBe(true)
})

test('mobile chart choice keeps the preview before the long chart catalogue', async ({ page }) => {
  const assertNoErrors = await failOnRuntimeErrors(page)
  await page.setViewportSize({ width: 390, height: 844 })
  await loadDemo(page)
  await expect(page.locator('.chart-picker')).toBeVisible()
  await expect(page.locator('.stage')).toBeVisible()
  const preview = await page.locator('.stage').boundingBox()
  const firstCategory = await page.locator('.chart-category').first().boundingBox()
  expect(preview?.y).toBeLessThan(firstCategory?.y ?? Infinity)

  await page.getByRole('button', { name: /^Линия$/ }).click()
  await expect(page.locator('.stage')).toBeVisible()
  await expect(page.locator('.settings-panel')).toBeHidden()
  await page.getByRole('button', { name: /Настроить оформление/ }).click()
  await expect(page.locator('.settings-panel')).toBeVisible()
  await expect.poll(() => page.evaluate(() => window.scrollY)).toBe(0)
  assertNoErrors()
})

test('heatmap scale stays inside the canvas in every position and keeps its own settings', async ({ page }) => {
  const assertNoErrors = await failOnRuntimeErrors(page)
  await loadDemo(page)
  await page.getByRole('button', { name: 'Тепловая карта' }).click()
  await expectRenderedChart(page)
  await page.getByRole('button', { name: /Настроить оформление/ }).click()

  const scalePosition = page.getByLabel('Положение шкалы')
  await page.locator('summary').filter({ hasText: 'Ряды и пропуски' }).click()
  await page.getByLabel('Сортировка рядов').selectOption('average')
  await page.getByLabel('Направление').selectOption('ascending')
  await page.locator('summary').filter({ hasText: 'Цветовая шкала' }).click()

  const lowerBound = page.getByLabel('Нижняя граница')
  await lowerBound.fill('0003')
  await expect(lowerBound).toHaveValue('3')
  await lowerBound.clear()
  await expect(lowerBound).toHaveValue('')

  let previousRender: Buffer | undefined
  for (const position of ['right', 'left', 'top', 'bottom']) {
    await scalePosition.scrollIntoViewIfNeeded()
    await scalePosition.selectOption(position)
    await expect(scalePosition).toHaveValue(position)
    await expectRenderedChart(page)
    const render = await page.locator('.canvas-paper').screenshot()
    expect(render.byteLength).toBeGreaterThan(10_000)
    if (previousRender) expect(render.equals(previousRender)).toBe(false)
    previousRender = render
  }

  await page.getByRole('button', { name: '← Тип графика' }).click()
  await page.getByRole('button', { name: /^Линия$/ }).click()
  await expectRenderedChart(page)
  await page.getByRole('button', { name: /Настроить оформление/ }).click()
  await expect(page.getByLabel('Сортировка рядов')).toBeHidden()
  await page.getByRole('button', { name: '← Тип графика' }).click()
  await page.getByRole('button', { name: 'Тепловая карта' }).click()
  await page.getByRole('button', { name: /Настроить оформление/ }).click()
  await expect(page.getByLabel('Положение шкалы')).toHaveValue('bottom')
  assertNoErrors()
})

test('before-after demo exposes independent dumbbell labels and change styling', async ({ page }) => {
  const assertNoErrors = await failOnRuntimeErrors(page)
  await page.goto('/editor')
  await page.getByRole('button', { name: 'До → после' }).click()
  await page.getByRole('button', { name: /Выбрать график/ }).click()
  await page.getByRole('button', { name: 'Гантельная' }).click()
  await expect(page.getByLabel('Начальное значение')).toHaveValue('before')
  await expect(page.getByLabel('Конечное значение')).toHaveValue('after')
  await page.getByRole('button', { name: /Настроить оформление/ }).click()
  await page.locator('summary').filter({ hasText: 'Гантельная диаграмма' }).click()
  await setCheckbox(page.getByRole('checkbox', { name: 'Начальное значение' }), true)
  await expect(page.getByRole('checkbox', { name: 'Начальное значение' })).toBeChecked()
  await expect(page.getByRole('checkbox', { name: 'Конечное значение' })).toBeChecked()
  await setCheckbox(page.getByRole('checkbox', { name: 'Показывать изменение между точками' }), true)
  await page.getByLabel('Формат изменения').selectOption('percent')
  await page.getByLabel('Расположение подписи').selectOption('end')
  await setCheckbox(page.getByRole('checkbox', { name: 'Цвет по направлению изменения' }), true)
  await expect(page.getByLabel('Формат изменения')).toHaveValue('percent')
  await expect(page.getByLabel('Расположение подписи')).toHaveValue('end')
  await expect(page.getByRole('checkbox', { name: 'Цвет по направлению изменения' })).toBeChecked()
  await expectRenderedChart(page)
  assertNoErrors()
})

test('distribution demo opens directly as a distribution chart', async ({ page }) => {
  const assertNoErrors = await failOnRuntimeErrors(page)
  await page.goto('/editor')
  await page.getByRole('button', { name: 'Распределения' }).click()
  await expect(page.getByRole('heading', { name: 'Проверьте данные' })).toBeVisible()
  await page.getByRole('button', { name: /Выбрать график/ }).click()
  await expect(page.getByRole('heading', { name: 'Тип графика' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Box plot' })).toHaveClass(/active/)
  await expect(page.getByRole('checkbox', { name: 'profit', exact: true })).toBeChecked()
  await expect(page.getByRole('checkbox', { name: 'orders', exact: true })).toBeChecked()
  await expect(page.getByLabel('Разбить цветом по категории')).toHaveValue('')
  await expectRenderedChart(page)
  const renders: Buffer[] = []
  for (const name of ['Box plot', 'Violin plot', 'Raincloud plot', 'Histogram', 'KDE plot', 'Ridgeline plot', 'Beeswarm plot', 'Strip plot', 'Jitter plot', 'Counts plot', 'Barcode plot']) {
    await page.getByRole('button', { name }).click()
    await expect(page.getByRole('button', { name })).toHaveClass(/active/)
    await expectRenderedChart(page)
    await page.waitForTimeout(250)
    const render = await page.locator('.canvas-paper').screenshot()
    expect(render.byteLength).toBeGreaterThan(5_000)
    expect(renders.some((previous) => render.equals(previous))).toBe(false)
    renders.push(render)
  }
  await page.getByLabel('Разбить цветом по категории').selectOption('region')
  await expect(page.getByLabel('Разбить цветом по категории')).toHaveValue('region')
  await page.getByRole('button', { name: 'Raincloud plot' }).click()
  await page.getByRole('button', { name: /Настроить оформление/ }).click()
  await page.locator('summary').filter({ hasText: /^Форма распределения$/ }).click()
  await expect(page.getByLabel('Расположение точек')).toHaveValue('overlay')
  await page.getByLabel('Расположение точек').selectOption('separate')
  await expect(page.getByLabel('Расположение точек')).toHaveValue('separate')
  await expectRenderedChart(page)
  await page.getByRole('button', { name: '← Тип графика' }).click()
  await page.getByRole('button', { name: 'Jitter plot' }).click()
  await page.getByRole('button', { name: /Настроить оформление/ }).click()
  await page.locator('summary').filter({ hasText: /^Форма распределения$/ }).click()
  await expect(page.getByRole('checkbox', { name: 'Показывать центральную линию' })).toBeChecked()
  await page.getByLabel('Значение центральной линии').selectOption('mean')
  await expect(page.getByLabel('Значение центральной линии')).toHaveValue('mean')
  await expectRenderedChart(page)
  await page.getByRole('button', { name: '← Тип графика' }).click()
  await page.getByRole('button', { name: 'Violin plot' }).click()
  await page.getByRole('button', { name: /Настроить оформление/ }).click()
  await page.locator('summary').filter({ hasText: /^Форма распределения$/ }).click()
  await expect(page.getByLabel('Что расположить на оси')).toHaveValue('measures')
  await expect(page.getByLabel('Цвет категории Север')).toBeVisible()
  await page.getByLabel('Подпись категории Север').fill('Северный округ')
  await setCheckbox(page.getByLabel('Показывать категорию Юг'), false)
  await expect(page.getByText('3 из 4 отображаются')).toBeVisible()
  await page.getByLabel('Что расположить на оси').selectOption('categories')
  await expect(page.getByLabel('Что расположить на оси')).toHaveValue('categories')
  await expect(page.getByLabel('Ориентация')).toHaveValue('horizontal')
  await expect(page.getByLabel('Форма скрипки')).toHaveValue('full')
  await page.getByLabel('Форма скрипки').selectOption('half')
  await page.getByLabel('Сторона половины').selectOption('first')
  await expect(page.getByLabel('Сторона половины')).toHaveValue('first')
  await page.getByLabel('Форма скрипки').selectOption('split')
  await expect(page.getByLabel('Первая половина')).toHaveValue('profit')
  await expect(page.getByLabel('Вторая половина')).toHaveValue('orders')
  await page.getByLabel('Сглаживание плотности').fill('0.2')
  await setCheckbox(page.getByRole('checkbox', { name: 'Показывать наблюдения поверх формы' }), false)
  await expect(page.getByLabel('Сглаживание плотности')).toHaveValue('0.2')
  await expect(page.getByLabel('Форма скрипки')).toHaveValue('split')
  await page.getByLabel('Ориентация').selectOption('vertical')
  await expect(page.getByLabel('Ориентация')).toHaveValue('vertical')
  await expectRenderedChart(page)
  assertNoErrors()
})
