import { expect, test } from '@playwright/test'
import { readFile } from 'node:fs/promises'

for (const name of ['Карта мира', 'Плиточная карта мира']) test(`${name}: official 2023 life expectancy preview and export`, async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/editor')
  await expect(page.getByRole('button', { name: 'Продолжительность жизни — плиточная карта', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Продолжительность жизни', exact: true }).click()
  await expect(page.locator('.review-table')).toBeVisible()
  await expect(page.locator('.settings-panel')).toHaveCount(0)
  await expect(page.locator('.review-table')).toContainText('AFG')
  await page.getByRole('button', { name: /Выбрать график/ }).click()
  if (name === 'Плиточная карта мира') await page.getByRole('button', { name, exact: true }).click()
  await expect(page.getByRole('combobox', { name: 'Страна', exact: true })).toHaveValue(/^(Код|Страна)$/)
  await page.getByRole('button', { name: 'Настроить оформление →' }).click()
  const canvas = page.locator('.chart-canvas-shell')
  await expect(canvas).toHaveAttribute('data-render-status', 'settled')
  await expect(page.locator('.chart-error')).toHaveCount(0)
  for (const text of ['Ожидаемая продолжительность жизни', '(2023)', 'При рождении, лет', 'Источник: Our World in Data']) await expect(canvas.locator('svg text').filter({ hasText: text }).first()).toBeVisible()
  await expect(canvas).not.toContainText('условные данные')
  await canvas.screenshot({ path: `/tmp/viiiz-life-expectancy-${name === 'Карта мира' ? 'world' : 'tiles'}.png` })
  await page.locator('.export-menu > summary').click()
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Скачать SVG', exact: true }).click()
  const svg = await readFile((await (await download).path())!, 'utf8')
  expect(svg).toContain('Ожидаемая продолжительность жизни')
  expect(svg).toContain('(2023)')
  expect(svg).toContain('Источник: Our World in Data')
  expect(svg).not.toContain('условные данные')
})
