import { expect, test } from '@playwright/test'
import { readFile } from 'node:fs/promises'

test('respondent groups demo opens a complete editable composition and exports shared scales', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto('/editor')
  await page.getByRole('button', { name: 'Группы респондентов', exact: true }).click()
  await expect(page.locator('.multiples-cell.filled')).toHaveCount(4)
  await expect(page.locator('.multiples-paper')).toContainText('условные данные')
  await expect(page.locator('.multiples-paper')).toContainText('Числа придуманы')
  await expect(page.locator('.settings-panel .multiples-presets')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Вся композиция', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect.poll(async () => {
    const bars = await page.locator('.multiples-cell svg path[fill="#db5a5a"]').evaluateAll((paths) => paths.map((path) => path.getBoundingClientRect().height))
    return bars.length === 10 && bars.every((height) => height > 0 && Math.abs(height - bars[0]) < 1)
  }).toBe(true)
  for (const chart of await page.locator('.multiples-cell .chart-canvas-shell').all()) await expect(chart).toHaveAttribute('data-render-status', 'settled')
  await expect(page.locator('.multiples-cell svg text').filter({ hasText: /^100%$/ })).toHaveCount(1)
  await page.screenshot({ path: '/tmp/viiiz-respondent-groups-editor.png', fullPage: true })
  await page.locator('.export-menu > summary').click()
  const svgDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Скачать SVG' }).click()
  const downloadedSvg = await svgDownload
  await downloadedSvg.saveAs('/tmp/viiiz-respondent-groups.svg')
  const svg = await readFile((await downloadedSvg.path())!, 'utf8')
  const exported = await page.evaluate((content) => {
    const document = new DOMParser().parseFromString(content, 'image/svg+xml')
    return { bars: document.querySelectorAll('path[fill="#db5a5a"]').length, scaleLabels: [...document.querySelectorAll('text')].filter((text) => text.textContent === '100%').length, width: document.documentElement.getAttribute('width'), height: document.documentElement.getAttribute('height') }
  }, svg)
  expect(exported).toEqual({ bars: 10, scaleLabels: 1, width: '2000', height: '2560' })
  const pngDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Скачать PNG' }).click()
  await (await pngDownload).saveAs('/tmp/viiiz-respondent-groups.png')
  await page.locator('.export-menu > summary').click()
  await page.getByRole('button', { name: /Выбрать график 3: По возрасту/ }).click()
  await expect(page.locator('.settings-panel')).toContainText('График 3 · По возрасту')
  expect(errors).toEqual([])
})

test('category spacing gives taller rows to longer groups and keeps preview and export proportional', async ({ page }) => {
  await page.goto('/editor')
  await page.locator('.upload-card input').setInputFiles({ name: 'groups.csv', mimeType: 'text/csv', buffer: Buffer.from('Пол,Возраст,Доля\nМужчины,18–24,30\nЖенщины,25–34,20\nМужчины,35–44,10\nЖенщины,45–60,15') })
  await page.getByRole('button', { name: /Выбрать график/ }).click()
  await page.getByRole('button', { name: 'Сетка графиков', exact: true }).click()
  await page.getByRole('button', { name: '1 колонка, 3 ряда', exact: true }).click()
  await page.getByRole('spinbutton', { name: 'Ряды', exact: true }).fill('2')
  await page.getByRole('spinbutton', { name: 'Ряды', exact: true }).press('Tab')
  await page.getByRole('button', { name: 'Добавить график в ячейку 1' }).click()
  await page.getByRole('button', { name: 'Линейчатая', exact: true }).click()
  await page.getByRole('combobox', { name: 'Способ агрегации повторяющихся X' }).selectOption('average')
  await page.getByRole('button', { name: 'Добавить график в ячейку 2' }).click()
  await page.getByRole('button', { name: 'Линейчатая', exact: true }).click()
  await page.getByRole('combobox', { name: 'Период / ось X' }).selectOption('Возраст')
  const toggle = page.locator('.multiples-layout .settings-checkbox').filter({ hasText: 'Одинаковая высота столбцов и интервалы' })
  await toggle.click()
  const expectEqualBars = () => expect.poll(async () => {
    const heights = await page.locator('.multiples-cell svg path[fill="#9e0142"]').evaluateAll((paths) => paths.map((path) => path.getBoundingClientRect().height))
    return heights.length === 6 && heights.every((height) => height > 0 && Math.abs(height - heights[0]) < 1)
  }).toBe(true)
  await expectEqualBars()
  const heights = await page.locator('.multiples-cell').evaluateAll((cells) => cells.map((cell) => cell.getBoundingClientRect().height))
  expect(heights[1]).toBeGreaterThan(heights[0])
  await page.getByRole('button', { name: /Настроить оформление/ }).click()
  for (const chart of await page.locator('.multiples-cell .chart-canvas-shell').all()) await expect(chart).toHaveAttribute('data-render-status', 'settled')
  await expectEqualBars()
  await page.screenshot({ path: '/tmp/viiiz-multiples-row-heights.png', fullPage: true })
  await page.locator('.export-menu > summary').click()
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Скачать SVG' }).click()
  const svg = await readFile((await (await download).path())!, 'utf8')
  const exported = await page.evaluate((content) => [...new DOMParser().parseFromString(content, 'image/svg+xml').documentElement.children].filter((child) => child.localName === 'svg').map((child) => ({ height: Number(child.getAttribute('height')), y: Number(child.getAttribute('y')) })), svg)
  expect(exported).toHaveLength(2)
  expect(exported[1].height).toBeGreaterThan(exported[0].height)
  expect(exported[1].y).toBeGreaterThanOrEqual(exported[0].y + exported[0].height)
  await page.locator('.export-menu > summary').click()
  await page.getByRole('navigation', { name: 'Этапы создания графика' }).getByRole('button', { name: /Тип графика/ }).click()
  await toggle.click()
  await expect.poll(async () => {
    const restored = await page.locator('.multiples-cell').evaluateAll((cells) => cells.map((cell) => cell.getBoundingClientRect().height))
    return Math.abs(restored[0] - restored[1]) < 1
  }).toBe(true)
})

for (const scenario of [
  { label: 'Только слева', mode: 'left', kind: 'Линия', layout: '3 колонки, 1 ряд' },
  { label: 'Только снизу', mode: 'bottom', kind: 'Линейчатая', layout: '1 колонка, 3 ряда' },
]) test(`shared scale labels ${scenario.mode} stay aligned and export once`, async ({ page }) => {
  await page.goto('/editor')
  await page.locator('.upload-card input').setInputFiles({ name: 'scale.csv', mimeType: 'text/csv', buffer: Buffer.from('Категория,Показатель\nАльфа,30\nБета,20\nГамма,10') })
  await page.getByRole('button', { name: /Выбрать график/ }).click()
  await page.getByRole('button', { name: 'Сетка графиков', exact: true }).click()
  await page.getByRole('button', { name: scenario.layout, exact: true }).click()
  for (const index of [1, 3]) {
    await page.getByRole('button', { name: `Добавить график в ячейку ${index}` }).click()
    await page.getByRole('button', { name: scenario.kind, exact: true }).click()
  }
  await page.getByText('Общие шкалы и категории', { exact: true }).click()
  await page.locator('.multiples-shared .settings-checkbox').filter({ hasText: /^Общая шкала значений$/ }).click()
  await page.locator('.multiples-shared').getByLabel('Максимум', { exact: true }).fill('100')
  await page.locator('.multiples-shared').getByLabel('Шаг', { exact: true }).fill('20')
  const labels = page.locator('.multiples-cell svg text').filter({ hasText: /^100$/ })
  const selector = page.getByRole('combobox', { name: 'Подписи общих шкал', exact: true })
  await selector.selectOption('all')
  await expect(labels).toHaveCount(2)
  await selector.selectOption(scenario.mode)
  await expect(labels).toHaveCount(1)
  const labelledIndex = scenario.mode === 'left' ? 0 : 2
  await expect(page.locator('.multiples-cell').nth(labelledIndex).locator('svg text').filter({ hasText: /^100$/ })).toHaveCount(1)
  await page.getByRole('button', { name: /Настроить оформление/ }).click()
  await page.getByRole('button', { name: 'Вся композиция', exact: true }).click()
  await page.getByText('Общие шкалы и категории', { exact: true }).click()
  await page.locator('.export-menu > summary').click()
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Скачать SVG' }).click()
  const svg = await readFile((await (await download).path())!, 'utf8')
  expect(await page.evaluate((content) => [...new DOMParser().parseFromString(content, 'image/svg+xml').querySelectorAll('text')].filter((text) => text.textContent === '100').length, svg)).toBe(1)
  await page.locator('.export-menu > summary').click()
  await selector.selectOption('all')
  await expect(labels).toHaveCount(2)
})

test('settings keep their category, expanded section and scroll position when switching charts', async ({ page }) => {
  await page.goto('/editor')
  await page.getByRole('button', { name: 'Временной ряд', exact: true }).click()
  await page.getByRole('button', { name: /Выбрать график/ }).click()
  await page.getByRole('button', { name: 'Сетка графиков', exact: true }).click()
  await page.getByRole('button', { name: 'Добавить график в ячейку 1' }).click()
  await page.getByRole('button', { name: 'Линия', exact: true }).click()
  await page.getByRole('button', { name: 'Добавить график в ячейку 2' }).click()
  await page.getByRole('button', { name: 'Линейчатая', exact: true }).click()
  await page.getByRole('button', { name: /Настроить оформление/ }).click()
  const panel = page.locator('.settings-panel')
  await panel.evaluate((element) => { element.scrollTop = element.querySelector<HTMLElement>('.settings-category-title')!.offsetTop - element.offsetTop })
  await page.getByRole('tab', { name: 'Текст', exact: true }).click()
  await expect.poll(() => panel.evaluate((element) => element.scrollTop)).toBeGreaterThan(50)
  await panel.getByText('Заголовок и подзаголовок', { exact: true }).click()
  const heading = panel.locator('details').filter({ has: page.getByText('Заголовок и подзаголовок', { exact: true }) })
  await expect(heading).toHaveAttribute('open', '')
  await panel.evaluate((element) => { element.scrollTop += 100 })
  const before = await panel.evaluate((element) => element.scrollTop)
  // Select on the canvas so reaching a button at the top cannot scroll the menu.
  await page.locator('.multiples-cell.filled').first().click({ position: { x: 5, y: 5 } })
  await expect(panel).toContainText('График 1 ·')
  await expect(page.getByRole('tab', { name: 'Текст', exact: true })).toHaveAttribute('aria-selected', 'true')
  await expect(heading).toHaveAttribute('open', '')
  await expect.poll(async () => Math.abs(await panel.evaluate((element) => element.scrollTop) - before)).toBeLessThan(2)
  await page.locator('.multiples-cell.filled').nth(1).click({ position: { x: 5, y: 5 } })
  await expect(panel).toContainText('График 2 ·')
  await expect(page.getByRole('tab', { name: 'Текст', exact: true })).toHaveAttribute('aria-selected', 'true')
  await expect(heading).toHaveAttribute('open', '')
  await expect.poll(async () => Math.abs(await panel.evaluate((element) => element.scrollTop) - before)).toBeLessThan(2)
})

test('shared bar scale, one category rail and a composition font stay proportional in export', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto('/editor')
  await page.locator('.upload-card input').setInputFiles({ name: 'comparison.csv', mimeType: 'text/csv', buffer: Buffer.from('Категория,Все,Мужчины,Женщины\nДети нуждающиеся в лечении,30,15,45\nМалоимущие,20,10,30\nЖертвы насилия,2,1,3') })
  await page.getByRole('button', { name: /Выбрать график/ }).click()
  await page.getByRole('button', { name: 'Сетка графиков', exact: true }).click()
  await page.getByRole('button', { name: '3 колонки, 1 ряд', exact: true }).click()
  for (let index = 0; index < 3; index++) {
    await page.getByRole('button', { name: `Добавить график в ячейку ${index + 1}` }).click()
    if (index > 0) {
      await page.locator('.chart-data-section .y-field-list').getByText(['Все', 'Мужчины', 'Женщины'][index], { exact: true }).click()
      await page.locator('.chart-data-section .y-field-list').getByText('Все', { exact: true }).click()
    }
    await page.getByRole('button', { name: 'Линейчатая', exact: true }).click()
  }
  await page.getByText('Общие шкалы и категории', { exact: true }).click()
  await page.locator('.multiples-shared .settings-checkbox').filter({ hasText: /^Общая шкала значений$/ }).click()
  await page.locator('.multiples-shared').getByLabel('Максимум', { exact: true }).fill('60')
  await page.locator('.multiples-shared .settings-checkbox').filter({ hasText: /^Общие подписи категорий$/ }).click()
  await expect(page.locator('.multiples-category-label')).toHaveCount(3)
  for (const chart of await page.locator('.multiples-cell .chart-canvas-shell').all()) await expect(chart).toHaveAttribute('data-render-status', 'settled')
  await expect.poll(async () => {
    const widths = await page.locator('.multiples-cell').evaluateAll((cells) => cells.map((cell) => (cell.querySelector('svg path[fill="#9e0142"]') as SVGGraphicsElement | null)?.getBBox().width ?? 0))
    return widths.length === 3 && widths.every((width) => width > 0)
      && Math.abs(widths[0] / widths[1] - 2) < 0.05
      && Math.abs(widths[2] / widths[0] - 1.5) < 0.05
  }).toBe(true)
  await page.getByRole('button', { name: /Настроить оформление/ }).click()
  await page.getByRole('button', { name: /Вся композиция/ }).click()
  await page.getByText('Общий стиль всей композиции', { exact: true }).click()
  await page.getByRole('combobox', { name: 'Шрифт всех надписей', exact: true }).selectOption({ label: 'Georgia' })
  for (const chart of await page.locator('.multiples-cell .chart-canvas-shell').all()) await expect(chart).toHaveAttribute('data-render-status', 'settled')
  await expect(page.locator('.multiples-category-label').first()).toHaveAttribute('font-family', /Georgia/)
  await expect.poll(() => page.locator('.multiples-cell svg text').evaluateAll((texts) => texts.filter((text) => text.textContent?.trim()).every((text) => text.getAttribute('style')?.includes('Georgia') || text.getAttribute('font-family')?.includes('Georgia')))).toBe(true)
  await page.locator('.export-menu > summary').click()
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Скачать SVG' }).click()
  const content = await readFile((await (await download).path())!, 'utf8')
  const exported = await page.evaluate((svg) => {
    const root = new DOMParser().parseFromString(svg, 'image/svg+xml')
    return { categories: root.querySelectorAll('.multiples-category-label').length, fontSizes: [...root.querySelectorAll('svg svg text')].map((text) => text.getAttribute('style') ?? text.getAttribute('font-family') ?? '') }
  }, content)
  expect(exported.categories).toBe(3)
  expect(exported.fontSizes.every((style) => style.includes('Georgia'))).toBe(true)
  await page.locator('.export-menu > summary').click()
  await page.screenshot({ path: '/tmp/viiiz-multiples-shared.png', fullPage: true })
  expect(errors).toEqual([])
})

test('manually builds, edits, rearranges and exports a chart composition', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto('/editor')
  await page.getByRole('button', { name: 'Временной ряд', exact: true }).click()
  await page.getByRole('button', { name: /Выбрать график/ }).click()
  await page.getByRole('button', { name: 'Сетка графиков', exact: true }).click()
  await expect(page.locator('.multiples-cell.empty')).toHaveCount(4)
  await expect(page.getByRole('button', { name: /Настроить оформление/ })).toBeDisabled()
  await page.getByRole('button', { name: '3 колонки, 1 ряд', exact: true }).click()
  await expect(page.locator('.multiples-cell.empty')).toHaveCount(3)
  await page.getByRole('button', { name: 'Добавить график в ячейку 1' }).click()
  await page.getByRole('button', { name: 'Линия', exact: true }).click()
  await expect(page.locator('.multiples-cell.filled .chart-canvas-shell')).toHaveAttribute('data-render-status', 'settled')
  await page.getByRole('button', { name: 'Добавить график в ячейку 2' }).click()
  const fields = page.locator('.chart-data-section .y-field-list')
  await fields.getByText('orders', { exact: true }).click()
  await fields.getByText('revenue', { exact: true }).click()
  await expect(page.locator('.multiples-cell.filled')).toHaveCount(2)
  await page.getByRole('button', { name: /Выбрать график 1:/ }).click()
  await expect(page.getByRole('button', { name: 'Линия', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: 'Дублировать график 1' }).click()
  await expect(page.locator('.multiples-cell.filled')).toHaveCount(3)
  await page.getByRole('button', { name: '1 колонка, 3 ряда', exact: true }).click()
  await page.getByRole('button', { name: 'Переместить график 3 назад' }).click()
  await page.getByRole('button', { name: 'Удалить график 2' }).click()
  await expect(page.locator('.multiples-cell.filled')).toHaveCount(2)
  await page.getByRole('button', { name: /Настроить оформление/ }).click()
  await page.getByRole('button', { name: /Вся композиция/ }).click()
  await expect(page.locator('.settings-panel')).toBeVisible()
  await expect(page.locator('.multiples-cell.filled .chart-canvas-shell').nth(0)).toHaveAttribute('data-render-status', 'settled')
  await expect(page.locator('.multiples-cell.filled .chart-canvas-shell').nth(1)).toHaveAttribute('data-render-status', 'settled')
  await page.locator('.export-menu > summary').click()
  const svgDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Скачать SVG' }).click()
  const svgPath = await (await svgDownload).path()
  const svg = await readFile(svgPath!, 'utf8')
  expect(svg.match(/<svg\b/g)).toHaveLength(3)
  expect(svg).toContain('График 1')
  expect(svg).toContain('График 2')
  expect(svg).not.toContain('Добавить график')
  const pngDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Скачать PNG' }).click()
  const pngPath = await (await pngDownload).path()
  expect((await readFile(pngPath!)).subarray(1, 4).toString()).toBe('PNG')
  await page.locator('.export-menu > summary').click()
  await page.screenshot({ path: '/tmp/viiiz-multiples-desktop.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: '/tmp/viiiz-multiples-mobile.png', fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  expect(errors).toEqual([])
})

test('composition history restores panels, layout and independent settings', async ({ page }) => {
  await page.goto('/editor')
  await page.getByRole('button', { name: 'Временной ряд', exact: true }).click()
  await page.getByRole('button', { name: /Выбрать график/ }).click()
  await page.getByRole('button', { name: 'Сетка графиков', exact: true }).click()
  await page.getByRole('button', { name: 'Добавить график в ячейку 1' }).click()
  await page.getByRole('button', { name: 'Линия', exact: true }).click()
  await expect(page.locator('.multiples-cell.filled .chart-canvas-shell')).toHaveAttribute('data-render-status', 'settled')
  await page.getByRole('button', { name: 'Добавить график в ячейку 4' }).click()
  await expect(page.locator('.multiples-cell.filled')).toHaveCount(2)
  await page.getByRole('button', { name: '3 колонки, 1 ряд', exact: true }).click()
  await expect(page.locator('.multiples-cell')).toHaveCount(6)
  await page.getByRole('button', { name: 'Удалить график 4' }).click()
  await expect(page.locator('.multiples-cell.filled')).toHaveCount(1)
  await page.locator('.canvas-floating-menu').getByRole('button', { name: 'Отменить', exact: true }).click()
  await expect(page.locator('.multiples-cell.filled')).toHaveCount(2)
  await page.locator('.canvas-floating-menu').getByRole('button', { name: 'Отменить', exact: true }).click()
  await expect(page.locator('.multiples-cell')).toHaveCount(4)
  await page.locator('.canvas-floating-menu').getByRole('button', { name: 'Повторить', exact: true }).click()
  await expect(page.locator('.multiples-cell')).toHaveCount(6)
  await page.getByRole('button', { name: 'Один график', exact: true }).click()
  await expect(page.locator('.multiples-grid')).toHaveCount(0)
  await page.getByRole('button', { name: 'Сетка графиков', exact: true }).click()
  await expect(page.locator('.multiples-cell.filled')).toHaveCount(2)
  await page.getByRole('button', { name: /Выбрать график 1:/ }).click()
  await expect(page.getByRole('button', { name: 'Линия', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: /Настроить оформление/ }).click()
  await page.getByRole('tab', { name: 'Текст', exact: true }).click()
  await page.locator('.settings-panel').getByText('Заголовок и подзаголовок', { exact: true }).click()
  await page.locator('.settings-panel').getByRole('textbox', { name: 'Заголовок', exact: true }).fill('Выручка')
  await page.getByRole('button', { name: /Вся композиция/ }).click()
  await expect(page.locator('[data-composition-text=title]')).not.toContainText('Выручка')
  await page.getByRole('button', { name: 'Графики', exact: true }).click()
  await expect(page.locator('.multiples-panel-list')).toContainText('Выручка')
  await page.getByRole('button', { name: /Выбрать график 1: Выручка/ }).click()
  await expect(page.locator('.settings-panel')).toContainText('График 1 · Выручка')
})

test('design scope switch is sticky, omits grid setup and remembers the last chart', async ({ page }) => {
  await page.goto('/editor')
  await page.getByRole('button', { name: 'Группы респондентов', exact: true }).click()
  const settings = page.locator('.settings-panel')
  const scope = settings.getByRole('group', { name: 'Область настройки', exact: true })
  await expect(scope.getByRole('button', { name: 'Вся композиция', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(settings.getByText('Сетка графиков', { exact: true })).toHaveCount(0)
  await expect(settings.getByRole('spinbutton', { name: 'Колонки', exact: true })).toHaveCount(0)
  await scope.getByRole('button', { name: 'Графики', exact: true }).click()
  await expect(settings).toContainText('График 1 ·')
  await settings.locator('.multiples-panel-name').nth(2).click()
  await expect(settings).toContainText('График 3 · По возрасту')
  await page.getByRole('tab', { name: 'Текст', exact: true }).click()
  await settings.getByText('Заголовок и подзаголовок', { exact: true }).click()
  await settings.evaluate((element) => { element.scrollTop = 250 })
  const [panelBounds, switchBounds] = await Promise.all([settings.boundingBox(), scope.boundingBox()])
  expect(switchBounds!.y).toBeGreaterThanOrEqual(panelBounds!.y)
  expect(switchBounds!.y).toBeLessThan(panelBounds!.y + 25)
  await scope.getByRole('button', { name: 'Вся композиция', exact: true }).click()
  await expect(settings.locator('.multiples-panel-list')).toHaveCount(0)
  await scope.getByRole('button', { name: 'Графики', exact: true }).click()
  await expect(settings).toContainText('График 3 · По возрасту')
  await expect(page.getByRole('tab', { name: 'Текст', exact: true })).toHaveAttribute('aria-selected', 'true')
  await expect(settings.locator('.multiples-presets')).toHaveCount(0)
  await page.screenshot({ path: '/tmp/viiiz-design-scope.png', fullPage: true })
  await scope.getByRole('button', { name: 'Вся композиция', exact: true }).click()
  await page.getByRole('navigation', { name: 'Этапы создания графика' }).getByRole('button', { name: /Тип графика/ }).click()
  await expect(page.locator('.multiples-presets')).toBeVisible()
  await expect(page.getByRole('spinbutton', { name: 'Колонки', exact: true })).toBeVisible()
})


test('edits common composition texts on canvas and keeps panel text tools outside cells', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto('/editor')
  await page.getByRole('button', { name: 'Группы респондентов', exact: true }).click()
  // Start from an active panel: selecting a common text must switch the scope.
  await page.getByRole('button', { name: /Выбрать график 2: По полу/ }).click()
  for (const field of ['title', 'subtitle', 'note', 'source']) {
    const block = page.locator(`[data-composition-text="${field}"]`)
    await block.locator('.canvas-rich-text-display').click()
    await expect(page.getByRole('button', { name: 'Вся композиция', exact: true })).toHaveAttribute('aria-pressed', 'true')
    await block.locator('.canvas-rich-text-content').fill(`Общий ${field}`)
  }
  const source = page.locator('[data-composition-text="source"] .canvas-rich-text-content')
  await source.evaluate((element) => {
    element.innerHTML = '<b style="color:#ff3333">Общий</b> <i style="font-family:Georgia,serif">источник</i>'
    element.dispatchEvent(new InputEvent('input', { bubbles: true }))
  })
  const size = page.locator('.portal-text-toolbar .text-size-field input')
  const originalSize = Number(await size.inputValue())
  await page.getByRole('button', { name: 'Увеличить размер', exact: true }).click()
  await expect(size).toHaveValue(String(originalSize + 1))
  await page.getByRole('button', { name: 'Выровнять по центру', exact: true }).click()
  await expect(source.locator('..')).toHaveCSS('text-align', 'center')
  await page.locator('.export-menu > summary').click()
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Скачать SVG', exact: true }).click()
  const svg = await readFile((await (await download).path())!, 'utf8')
  const exported = await page.evaluate((content) => {
    const doc = new DOMParser().parseFromString(content, 'image/svg+xml')
    return { titles: ['title', 'subtitle', 'note'].map((field) => doc.querySelector(`[data-annotation-id="composition-${field}"]`)?.textContent), source: [...doc.querySelectorAll('[data-annotation-id="composition-source"] text')].map((node) => ({ text: node.textContent, fill: node.getAttribute('fill'), family: node.getAttribute('font-family') })) }
  }, svg)
  expect(exported.titles).toEqual(['Общий title', 'Общий subtitle', 'Общий note'])
  expect(exported.source[0]).toMatchObject({ text: 'Общий', fill: 'rgb(255, 51, 51)' })
  expect(exported.source.at(-1)?.family).toContain('Georgia')
  await page.locator('.export-menu > summary').click()
  await page.getByRole('button', { name: /Выбрать график 2: По полу/ }).click()
  await page.getByRole('tab', { name: 'Текст', exact: true }).click()
  await page.locator('.heading-settings > summary').click()
  const subtitle = page.getByRole('checkbox', { name: 'Показывать подзаголовок', exact: true })
  await page.locator('.settings-checkbox').filter({ hasText: 'Показывать подзаголовок' }).click()
  await expect(subtitle).toBeChecked()
  await expect(page.locator('.multiples-cell.selected')).toContainText('Подзаголовок графика')
  await page.locator('.credits-settings > summary').click()
  for (const label of ['Показывать комментарий', 'Показывать источник']) await page.locator('.settings-checkbox').filter({ hasText: label }).click()
  const panel = page.locator('.multiples-cell.selected')
  await expect(panel).toContainText('Комментарий к графику')
  await expect(panel).toContainText('Источник: данные пользователя')
  await expect(panel.locator('svg text').filter({ hasText: /^Подзаголовок графика$/ })).toHaveCSS('font-size', '14px')
  await expect(panel.locator('svg text').filter({ hasText: /^Комментарий к графику$/ })).toHaveCSS('font-size', '12px')
  await panel.locator('svg text').filter({ hasText: /^По полу$/ }).click()
  const toolbar = page.locator('.portal-text-toolbar')
  await expect(toolbar).toBeVisible()
  expect(await toolbar.evaluate((element) => element.parentElement === document.body)).toBe(true)
  const bounds = await toolbar.boundingBox()
  expect(bounds!.x).toBeGreaterThanOrEqual(0)
  expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(page.viewportSize()!.width)
  await page.getByRole('button', { name: 'Выровнять справа', exact: true }).click()
  await expect(panel.locator('.canvas-rich-text')).toHaveCSS('text-align', 'right')
  const panelTitle = panel.locator('.canvas-rich-text-content')
  const panelSize = Number(await page.locator('.portal-text-toolbar .text-size-field input').inputValue())
  await page.getByRole('button', { name: 'Увеличить размер', exact: true }).click()
  await expect(panelTitle).toHaveCSS('font-size', `${panelSize + 1}px`)
  await page.getByRole('button', { name: 'Снять выделение', exact: true }).click()
  await panel.locator('.canvas-rich-text-display').filter({ hasText: /^По полу$/ }).click()
  await expect(page.locator('.portal-text-toolbar .text-size-field input')).toHaveValue(String(panelSize + 1))
  await page.screenshot({ path: '/tmp/viiiz-composition-text-tools.png', fullPage: true })
  expect(errors).toEqual([])
})

for (const [key, count] of [['Enter', 1], ['Enter', 2], ['Shift+Enter', 1]] as const) {
  test(`panel text keeps ${count} ${key} line breaks in SVG export`, async ({ page }) => {
    await page.goto('/editor')
    await page.getByRole('button', { name: 'Группы респондентов', exact: true }).click()
    await page.getByRole('button', { name: /Выбрать график 2: По полу/ }).click()
    const panel = page.locator('.multiples-cell.selected')
    await panel.locator('svg text').filter({ hasText: /^По полу$/ }).click()
    const editor = panel.locator('.canvas-rich-text-content')
    await editor.fill('Первая')
    await editor.press('End')
    for (let index = 0; index < count; index++) await editor.press(key)
    await page.keyboard.insertText('Вторая')
    const lineHeight = await editor.evaluate((element) => Number.parseFloat(getComputedStyle(element).lineHeight))
    await expect(editor).toHaveText(/Первая.*Вторая/s)
    await expect(panel.locator('.chart-canvas-shell')).toHaveAttribute('data-render-status', 'settled')
    await page.locator('.export-menu > summary').click()
    const download = page.waitForEvent('download')
    await page.getByRole('button', { name: 'Скачать SVG', exact: true }).click()
    const svg = await readFile((await (await download).path())!, 'utf8')
    const lines = await page.evaluate((content) => [...new DOMParser().parseFromString(content, 'image/svg+xml').querySelectorAll('svg svg text')]
      .filter((node) => node.getAttribute('fill-opacity') !== '0' && (node.textContent === 'Первая' || node.textContent === 'Вторая'))
      .map((node) => ({ text: node.textContent, y: Number(node.getAttribute('y')) })), svg)
    expect(lines.map((line) => line.text)).toEqual(['Первая', 'Вторая'])
    expect(lines[1].y - lines[0].y).toBeCloseTo(count * lineHeight, 1)
  })
}

test('all panel text blocks retain Enter line breaks in composition export', async ({ page }) => {
  await page.goto('/editor')
  await page.getByRole('button', { name: 'Группы респондентов', exact: true }).click()
  await page.getByRole('button', { name: /Выбрать график 2: По полу/ }).click()
  await page.getByRole('tab', { name: 'Текст', exact: true }).click()
  await page.locator('.heading-settings > summary').click()
  await page.locator('.settings-checkbox').filter({ hasText: 'Показывать подзаголовок' }).click()
  await page.locator('.credits-settings > summary').click()
  for (const label of ['Показывать комментарий', 'Показывать источник']) await page.locator('.settings-checkbox').filter({ hasText: label }).click()
  const panel = page.locator('.multiples-cell.selected')
  const lineHeights: Record<string, number> = {}
  for (const [field, text] of [['title', 'По полу'], ['subtitle', 'Подзаголовок графика'], ['note', 'Комментарий к графику'], ['source', 'Источник: данные пользователя']]) {
    await panel.locator('svg text').filter({ hasText: new RegExp(`^${text}$`) }).click()
    const editor = panel.locator('.canvas-rich-text-content')
    await editor.fill(`${field}Первая`)
    await editor.press('End')
    await editor.press('Enter')
    await page.keyboard.insertText(`${field}Вторая`)
    await page.getByRole('button', { name: 'Снять выделение', exact: true }).click()
  }
  await expect(panel.locator('.chart-canvas-shell')).toHaveAttribute('data-render-status', 'settled')
  for (const field of ['title', 'subtitle', 'note', 'source']) lineHeights[field] = await panel.locator('.canvas-rich-text-display').filter({ hasText: new RegExp(`^${field}Первая`) }).evaluate((element) => Number.parseFloat(getComputedStyle(element).lineHeight))
  await page.locator('.export-menu > summary').click()
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Скачать SVG', exact: true }).click()
  const svg = await readFile((await (await download).path())!, 'utf8')
  const exported = await page.evaluate((content) => [...new DOMParser().parseFromString(content, 'image/svg+xml').querySelectorAll('svg svg text')]
    .filter((node) => node.getAttribute('fill-opacity') !== '0')
    .map((node) => ({ text: node.textContent, y: Number(node.getAttribute('y')) })), svg)
  for (const field of ['title', 'subtitle', 'note', 'source']) {
    const lines = exported.filter((node) => node.text === `${field}Первая` || node.text === `${field}Вторая`)
    expect(lines.map((line) => line.text)).toEqual([`${field}Первая`, `${field}Вторая`])
    expect(lines[1].y - lines[0].y).toBeCloseTo(lineHeights[field], 1)
  }
  const bounds = await page.evaluate((content) => {
    const root = new DOMParser().parseFromString(content, 'image/svg+xml').documentElement as unknown as SVGSVGElement
    root.style.cssText = 'position:fixed;left:0;top:0;visibility:hidden;pointer-events:none'
    document.body.append(root)
    const frame = root.getBoundingClientRect()
    const rectangles = [...root.querySelectorAll('text')].filter((node) => node.getAttribute('fill-opacity') !== '0' && /^(title|subtitle|note|source)(Первая|Вторая)$/.test(node.textContent ?? '')).map((node) => {
      const rect = node.getBoundingClientRect()
      return { text: node.textContent, x: (rect.x - frame.x) / frame.width, y: (rect.y - frame.y) / frame.height, width: rect.width / frame.width, height: rect.height / frame.height }
    })
    root.remove()
    return rectangles
  }, svg)
  expect(bounds).toHaveLength(8)
  const pngDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Скачать PNG', exact: true }).click()
  const png = await readFile((await (await pngDownload).path())!)
  const ink = await page.evaluate(async ({ data, rectangles }) => {
    const image = new Image()
    image.src = data
    await image.decode()
    const canvas = document.createElement('canvas')
    canvas.width = image.width; canvas.height = image.height
    const context = canvas.getContext('2d')!
    context.drawImage(image, 0, 0)
    return rectangles.map((rect) => {
      const pixels = context.getImageData(Math.floor(rect.x * image.width), Math.floor(rect.y * image.height), Math.max(1, Math.ceil(rect.width * image.width)), Math.max(1, Math.ceil(rect.height * image.height))).data
      let count = 0
      for (let index = 0; index < pixels.length; index += 4) if (pixels[index + 3] && pixels[index] < 190 && pixels[index + 1] < 190 && pixels[index + 2] < 190) count++
      return { text: rect.text, count }
    })
  }, { data: `data:image/png;base64,${png.toString('base64')}`, rectangles: bounds })
  for (const line of ink) expect(line.count, String(line.text)).toBeGreaterThan(10)
})
