import { expect, test } from '@playwright/test'
import { readFile } from 'node:fs/promises'

test('random palette changes the chart on every click and is retained in SVG export', async ({ page }) => {
  await page.goto('/editor')
  await page.locator('.upload-card input').setInputFiles({ name: 'palette.csv', mimeType: 'text/csv', buffer: Buffer.from('Категория,Значение\nА,50\nБ,30\nВ,20') })
  await page.getByRole('button', { name: /Выбрать график/ }).click()
  await page.getByRole('button', { name: 'Вафельная', exact: true }).click()
  await page.getByRole('button', { name: 'Настроить оформление →' }).click()
  await page.locator('.palette-settings > summary').click()
  const canvas = page.locator('.chart-canvas-shell')
  const colors = () => canvas.locator('svg path').evaluateAll((paths) => [...new Set(paths.map((path) => path.getAttribute('fill')).filter((color) => color?.startsWith('#')))].sort())
  const previous = await colors()
  const button = page.getByRole('button', { name: 'Случайная палитра', exact: true })
  await button.click()
  await expect(button).toHaveClass(/active/)
  await expect.poll(colors).not.toEqual(previous)
  const first = await colors()
  await button.click()
  await expect.poll(colors).not.toEqual(first)
  await expect(page.locator('.custom-palette > span')).toHaveCount(7)
  const palette = await colors()
  await page.screenshot({ path: '/tmp/viiiz-random-palette.png', fullPage: true })
  await page.locator('.export-menu > summary').click()
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Скачать SVG' }).click()
  const svg = await readFile((await (await download).path())!, 'utf8')
  palette.forEach((color) => expect(svg).toContain(color))
})
