import { expect, test } from '@playwright/test'
import { readFile } from 'node:fs/promises'

test('new palettes and optional middle gradient color update the chart and SVG export', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/editor')
  await page.getByRole('button', { name: 'Арсенал ZywOo', exact: true }).click()
  await page.getByRole('button', { name: /Выбрать график/ }).click()
  await page.getByRole('button', { name: 'Настроить оформление →' }).click()
  const panel = page.locator('.palette-settings')
  await panel.locator('summary').click()
  const canvas = page.locator('.chart-canvas-shell')
  await expect(panel.getByRole('button', { name: /Okabe|Tableau|Set2/ })).toHaveCount(0)
  for (const name of ['Сирень', 'Пламя', 'Закат', 'Океан', 'Spectral 11', 'Viridis', 'Монохромная', 'Градиент']) {
    await panel.getByRole('button', { name, exact: true }).click()
    await expect(panel.getByRole('button', { name, exact: true })).toHaveClass(/active/)
    await expect(canvas).toHaveAttribute('data-render-status', 'settled')
    if (name === 'Spectral 11') await expect(panel.locator('.custom-palette > span')).toHaveCount(11)
  }
  await expect(panel.locator('.palette-gradient-colors > label')).toHaveCount(2)
  await expect(panel.locator('.custom-palette > span')).toHaveCount(7)
  await panel.getByRole('button', { name: '＋ Добавить средний цвет', exact: true }).click()
  await expect(panel.locator('.palette-gradient-colors > label')).toHaveCount(3)
  await panel.locator('.palette-gradient-colors > label').filter({ hasText: 'Средний цвет' }).getByRole('button', { name: 'Выбрать цвет', exact: true }).click()
  await page.getByRole('button', { name: 'Цвет #ffffff', exact: true }).click()
  await page.keyboard.press('Escape')
  await expect(panel.locator('.palette-gradient-preview')).toHaveCSS('background-image', /rgb\(255, 255, 255\)/)
  await panel.getByRole('button', { name: 'Убрать средний цвет', exact: true }).click()
  await expect(panel.locator('.palette-gradient-colors > label')).toHaveCount(2)
  await expect(panel.locator('.palette-gradient-preview')).not.toHaveCSS('background-image', /rgb\(255, 255, 255\)/)
  const shadeCount = panel.getByRole('spinbutton', { name: 'Число оттенков', exact: true })
  for (const count of [2, 24, 4]) {
    await shadeCount.fill(String(count))
    await shadeCount.press('Tab')
    await expect(panel.locator('.custom-palette > span')).toHaveCount(count)
  }
  const colors = () => panel.locator('.custom-palette .color-swatch').evaluateAll((swatches) => swatches.map((swatch) => getComputedStyle(swatch).backgroundColor))
  const gradientColors = await colors()
  expect(gradientColors).toHaveLength(4)
  await panel.getByRole('button', { name: 'Развернуть цвета', exact: true }).click()
  expect(await colors()).toEqual(gradientColors.toReversed())
  await expect(shadeCount).toHaveValue('4')
  await panel.getByRole('button', { name: 'Развернуть цвета', exact: true }).click()
  expect(await colors()).toEqual(gradientColors)
  const grip = panel.getByRole('button', { name: 'Переместить цвет 1', exact: true })
  await grip.scrollIntoViewIfNeeded()
  const from = (await grip.boundingBox())!
  const to = (await panel.locator('.custom-palette > span').nth(2).boundingBox())!
  await page.mouse.move(from.x + from.width / 2, from.y + from.height / 2)
  await page.mouse.down()
  await page.mouse.move(to.x + to.width / 2, to.y + to.height / 2, { steps: 8 })
  await page.mouse.up()
  expect(await colors()).toEqual([gradientColors[1], gradientColors[2], gradientColors[0], gradientColors[3]])
  await panel.getByRole('button', { name: 'Переместить цвет 3', exact: true }).press('ArrowLeft')
  expect(await colors()).toEqual([gradientColors[1], gradientColors[0], gradientColors[2], gradientColors[3]])
  await panel.getByRole('button', { name: 'Градиент', exact: true }).click()
  await expect(shadeCount).toHaveValue('4')
  expect(await colors()).toEqual(gradientColors)
  await panel.getByRole('button', { name: 'Spectral 11', exact: true }).click()
  await expect(canvas).toHaveAttribute('data-render-status', 'settled')
  for (const color of ['#9e0142', '#d53e4f', '#f46d43', '#fdae61']) await expect(canvas.locator(`svg path[fill="${color}"]`).first()).toBeVisible()
  await page.screenshot({ path: '/tmp/viiiz-new-palettes.png' })
  await page.locator('.export-menu > summary').click()
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Скачать SVG', exact: true }).click()
  const svg = await readFile((await (await download).path())!, 'utf8')
  for (const color of ['#9e0142', '#d53e4f', '#f46d43', '#fdae61']) expect(svg).toContain(color)
})
