import { expect, test } from '@playwright/test'
import { readFile } from 'node:fs/promises'

test('Sankey orders branches when all endpoints are moved to the last stage', async ({ page }) => {
  await page.goto('/editor')
  await page.locator('.upload-card input').setInputFiles({ name: 'flows.csv', mimeType: 'text/csv', buffer: Buffer.from('Откуда,Куда,Значение\nВсе наборы данных,Обновляются,80\nВсе наборы данных,Исключены из плана,20\nОбновляются,Доступны,65\nОбновляются,Временно недоступны,15\nДоступны,Актуальны,42\nДоступны,Давно не обновлялись,23') })
  await page.getByRole('button', { name: /Выбрать график/ }).click()
  await page.getByRole('button', { name: 'Санкей', exact: true }).click()
  await page.getByRole('button', { name: 'Настроить оформление →' }).click()
  await page.getByRole('combobox', { name: 'Конечные узлы', exact: true }).selectOption('justify')
  const canvas = page.locator('.chart-canvas-shell[data-plot-kind="sankey"]')
  await expect(canvas).toHaveAttribute('data-render-status', 'settled')
  const labels = ['Актуальны', 'Давно не', 'Временно', 'Исключены из']
  const positions: number[] = []
  for (const label of labels) {
    const text = canvas.locator('svg text').filter({ hasText: label }).first()
    await expect(text).toBeVisible()
    positions.push((await text.boundingBox())!.y)
  }
  expect(positions).toEqual([...positions].sort((a, b) => a - b))
  await canvas.screenshot({ path: '/tmp/viiiz-sankey-ordered-endpoints.png' })
})

test('Sankey maps roles, renders multistage flows, edits nodes and exports SVG and PNG', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto('/editor')
  await page.getByRole('button', { name: 'Трамп · Санкей' }).click()
  await page.getByRole('button', { name: /Выбрать график/ }).click()
  const canvas = page.locator('.chart-canvas-shell[data-plot-kind="sankey"]')
  await expect(canvas).toHaveAttribute('data-render-status', 'settled')
  await expect(page.getByRole('combobox', { name: 'Куда', exact: true })).toHaveValue('Куда')
  await page.getByRole('button', { name: 'Настроить оформление →' }).click()
  await expect(canvas.locator('svg text').filter({ hasText: /^Хиллари 8$/ })).toBeVisible()
  await canvas.screenshot({ path: '/tmp/viiiz-trump-sankey-example.png' })
  const settings = page.locator('details').filter({ has: page.getByText('Потоки и подписи', { exact: true }) })
  if (!(await settings.evaluate((element) => element.hasAttribute('open')))) await settings.locator(':scope > summary').click()
  await page.getByRole('combobox', { name: 'Значения в подписях' }).selectOption('percent')
  await expect(canvas.locator('svg text').filter({ hasText: /^Хиллари 4,68%$/ }).first()).toBeVisible()
  await page.getByRole('spinbutton', { name: 'Непрозрачность потоков, %' }).fill('25')
  await page.getByRole('spinbutton', { name: 'Непрозрачность потоков, %' }).press('Tab')
  await expect(canvas.locator('svg path[fill-opacity="0.25"]')).toHaveCount(22)
  const ribbon = await canvas.locator('svg path[fill-opacity="0.25"]').first().boundingBox()
  if (!ribbon) throw new Error('Flow is missing')
  await page.mouse.click(ribbon.x + ribbon.width * .25, ribbon.y + ribbon.height * .1)
  await page.getByRole('spinbutton', { name: 'Непрозрачность потока, %', exact: true }).fill('10')
  await page.getByRole('spinbutton', { name: 'Непрозрачность потока, %', exact: true }).press('Tab')
  await expect(canvas.locator('svg path[fill-opacity="0.1"]')).toHaveCount(1)
  await page.getByRole('button', { name: 'Снять выделение', exact: true }).click()
  const caption = await canvas.locator('svg text').filter({ hasText: /^Хиллари 4,68%$/ }).boundingBox()
  if (!caption) throw new Error('Caption is missing')
  await page.mouse.click(caption.x + caption.width / 2, caption.y + caption.height / 2)
  await page.getByRole('textbox', { name: 'Текст подписи', exact: true }).fill('Хиллари\nСейчас')
  await expect(canvas.locator('svg text').filter({ hasText: /^Сейчас$/ })).toBeVisible()
  await page.getByRole('button', { name: 'Снять выделение', exact: true }).click()
  await canvas.screenshot({ path: '/tmp/viiiz-trump-sankey.png' })
  await page.screenshot({ path: '/tmp/viiiz-sankey-editor.png', fullPage: true })
  await page.getByRole('tab', { name: 'Холст', exact: true }).click()
  await page.locator('details.canvas-settings > summary').click()
  await page.getByRole('checkbox', { name: 'Тёмная тема холста', exact: true }).press('Space')
  await expect(canvas).toHaveAttribute('data-render-status', 'settled')
  await expect(canvas.locator('svg text').filter({ hasText: /^Сейчас$/ })).toHaveAttribute('fill', /^(#f4f4f5|rgb\(244,244,245\))$/)
  await page.screenshot({ path: '/tmp/viiiz-sankey-dark.png', fullPage: true })
  await page.locator('.export-menu > summary').click()
  const svgDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Скачать SVG' }).click()
  const svg = await readFile((await (await svgDownload).path())!, 'utf8')
  expect(svg).toContain('Сейчас')
  expect(svg).toContain('4,68%')
  expect(svg).toContain('fill-opacity="0.25"')
  const pngDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Скачать PNG' }).click()
  expect((await readFile((await (await pngDownload).path())!)).subarray(1, 4).toString()).toBe('PNG')
  expect(errors).toEqual([])
})

test('Sankey selection infers uploaded columns and reports a cycle', async ({ page }) => {
  await page.goto('/editor')
  await page.locator('.upload-card input').setInputFiles({ name: 'flows.csv', mimeType: 'text/csv', buffer: Buffer.from('Откуда,Куда,Значение\nА,Б,70\nБ,А,30') })
  await page.getByRole('button', { name: /Выбрать график/ }).click()
  await page.getByRole('button', { name: 'Санкей', exact: true }).click()
  await expect(page.getByRole('combobox', { name: 'Куда', exact: true })).toHaveValue('Куда')
  await expect(page.getByText(/Потоки не должны образовывать цикл/)).toBeVisible()
})

test('Sankey works in a composition and keeps multiline captions in exported panels', async ({ page }) => {
  await page.goto('/editor')
  await page.locator('.upload-card input').setInputFiles({ name: 'flows.csv', mimeType: 'text/csv', buffer: Buffer.from('Откуда,Куда,Значение\nВсего,Семьи,90\nВсего,Учреждения,10') })
  await page.getByRole('button', { name: /Выбрать график/ }).click()
  await page.getByRole('button', { name: 'Сетка графиков', exact: true }).click()
  await page.getByRole('button', { name: '1 колонка, 3 ряда', exact: true }).click()
  for (const index of [1, 2]) {
    await page.getByRole('button', { name: `Добавить график в ячейку ${index}` }).click()
    await page.getByRole('button', { name: 'Санкей', exact: true }).click()
  }
  await page.getByRole('button', { name: /Настроить оформление/ }).click()
  const panels = page.locator('.multiples-cell .chart-canvas-shell[data-plot-kind="sankey"]')
  await expect(panels).toHaveCount(2)
  for (const panel of await panels.all()) await expect(panel).toHaveAttribute('data-render-status', 'settled')
  const caption = await panels.nth(1).locator('svg text').filter({ hasText: /^Семьи$/ }).boundingBox()
  if (!caption) throw new Error('Panel caption is missing')
  await page.mouse.click(caption.x + caption.width / 2, caption.y + caption.height / 2)
  await page.getByRole('textbox', { name: 'Текст подписи', exact: true }).fill('В семьях\n90 человек')
  await expect(panels.nth(1).locator('svg text').filter({ hasText: /^90 человек$/ })).toBeVisible()
  await page.locator('.export-menu > summary').click()
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Скачать SVG' }).click()
  const svg = await readFile((await (await download).path())!, 'utf8')
  expect(svg).toContain('В семьях')
  expect(svg).toContain('90 человек')
  expect(await page.evaluate((content) => new DOMParser().parseFromString(content, 'image/svg+xml').querySelectorAll('svg svg').length, svg)).toBe(2)
})
