import { expect, test } from '@playwright/test'

test('home intro plays on the first visit and stays skipped on return visits', async ({ page }) => {
  await page.addInitScript(() => {
    const state = window as typeof window & { homeSkeletonShown?: boolean }
    state.homeSkeletonShown = false
    new MutationObserver(() => {
      if (location.pathname === '/' && document.querySelector('.route-skeleton')) state.homeSkeletonShown = true
    }).observe(document, { childList: true, subtree: true })
  })
  let release!: () => void
  const loading = new Promise<void>((resolve) => { release = resolve })
  await page.route('**/src/pages/HomePage.tsx', async (route) => { await loading; await route.continue() }, { times: 1 })
  await page.goto('/', { waitUntil: 'domcontentloaded' })
  try {
    const loader = page.getByRole('status', { name: 'Загрузка страницы' })
    await expect(loader).toBeVisible()
    await expect(loader.locator('.brand-logo--mark')).toBeVisible()
    await expect(loader).toHaveCSS('color', 'rgb(243, 243, 243)')
    await expect(loader.locator('header, main, section')).toHaveCount(0)
  } finally { release() }

  const intro = page.locator('.home-intro')
  const heroWordmark = page.locator('.hero-wordmark')
  await expect(intro).toBeVisible()
  await expect(intro).toHaveAttribute('data-stage', 'loading')
  await expect(heroWordmark).toHaveCSS('visibility', 'hidden')
  const loadingTransforms = await intro.locator('.brand-logo-letter').evaluateAll((letters) => letters.map((letter) => getComputedStyle(letter).transform))
  expect(loadingTransforms).toEqual(['none', 'none', 'none'])
  await expect(intro.locator('.brand-logo-added-stem')).toHaveCount(4)
  await expect(intro.locator('.brand-logo text')).toHaveCount(0)
  await expect(intro).toHaveAttribute('data-stage', 'expanded', { timeout: 6_000 })
  await page.waitForTimeout(1_300)
  const expandedTransforms = await intro.locator('.brand-logo-letter').evaluateAll((letters) => letters.map((letter) => getComputedStyle(letter).transform))
  expect(expandedTransforms[0]).not.toBe('none')
  expect(expandedTransforms[1]).toBe('none')
  expect(expandedTransforms[2]).not.toBe('none')
  await expect(intro).toHaveAttribute('data-stage', 'docking')
  await expect(intro).toHaveCount(0, { timeout: 3_000 })
  await expect(heroWordmark).toBeVisible()
  await expect(page.getByText('Из таблицы — в ясный график.')).toHaveCount(0)
  await page.reload()
  await expect(page.locator('.marketing-page')).toHaveAttribute('aria-busy', 'false')
  await expect(intro).toHaveCount(0)
  await expect(heroWordmark).toBeVisible()
  expect(await page.evaluate(() => (window as typeof window & { homeSkeletonShown?: boolean }).homeSkeletonShown)).toBe(false)
  await page.getByRole('navigation', { name: 'Основная навигация' }).getByRole('link', { name: 'Галерея', exact: true }).click()
  await page.getByRole('link', { name: 'виииз — главная', exact: true }).click()
  await expect(page.locator('.marketing-page')).toHaveAttribute('aria-busy', 'false')
  await expect(intro).toHaveCount(0)
  const secondTab = await page.context().newPage()
  await secondTab.goto('/')
  await expect(secondTab.locator('.marketing-page')).toHaveAttribute('aria-busy', 'false')
  await expect(secondTab.locator('.home-intro')).toHaveCount(0)
  await secondTab.close()
})

test('editorial redesign keeps the gallery and animated trails', async ({ page }) => {
  await page.goto('/')

  await expect(page.locator('.symbol-trail-canvas')).toBeAttached()
  await expect(page.locator('.process-stream')).toBeAttached()
  await expect(page.locator('.chart-gallery-section')).toBeVisible()
  await expect(page.locator('.chart-marquee-track').first()).toBeVisible()
  await expect(page.locator('.workflow-transition')).toHaveCount(0)
  await expect(page.locator('.site-header .brand-logo')).toBeVisible()
  await expect(page.locator('.site-header .brand-logo-part')).toHaveCount(3)
  await expect(page.locator('.site-header .brand-logo-added-stem')).toHaveCount(4)
  await expect(page.locator('.site-header .brand-logo-added-stem').first()).toHaveCSS('display', 'none')
  await expect(page.getByRole('link', { name: /Создать график/ }).first()).toHaveCSS('background-color', 'rgb(32, 32, 39)')
  await expect(page.getByRole('link', { name: 'Создать график' })).toHaveCount(1)
})

test('gallery page exposes examples and animated navigation states', async ({ page }) => {
  let release!: () => void
  const loading = new Promise<void>((resolve) => { release = resolve })
  await page.route('**/src/pages/GalleryPage.tsx', async (route) => { await loading; await route.continue() })
  await page.goto('/gallery', { waitUntil: 'domcontentloaded' })
  try {
    const loader = page.getByRole('status', { name: 'Загрузка страницы' })
    await expect(loader).toBeVisible()
    await expect(loader.locator('.brand-logo--mark')).toBeVisible()
    await expect(loader.locator('.brand-logo-letter')).toHaveCount(3)
    await expect(loader).toHaveCSS('color', 'rgb(243, 243, 243)')
    await expect(loader.locator('header, main, section')).toHaveCount(0)
  } finally { release() }
  await expect(page.locator('.route-loading')).toHaveCount(0)

  await expect(page.getByRole('heading', { name: 'Галерея', level: 1 })).toBeVisible()
  await expect(page.locator('.gallery-grid .chart-gallery-card')).toHaveCount(15)
  for (const title of ['ИИ и закон Мура', 'География выручки ASML']) {
    const link = page.getByRole('link', { name: `Открыть график «${title}» в полном размере` })
    await link.scrollIntoViewIfNeeded()
    await expect(link).toHaveAttribute('target', '_blank')
    await expect.poll(() => link.locator('img').evaluate((img: HTMLImageElement) => img.complete && img.naturalWidth > 0)).toBe(true)
    await expect(link.locator('img')).toHaveCSS('object-fit', 'contain')
  }
  const navigation = page.getByRole('navigation', { name: 'Основная навигация' })
  await expect(navigation.getByRole('link')).toHaveCount(2)
  const galleryLink = navigation.getByRole('link', { name: 'Галерея' })
  const blogLink = navigation.getByRole('link', { name: 'Блог' })
  await expect(galleryLink).toHaveClass(/active/)
  await expect(galleryLink).toHaveCSS('color', 'rgb(54, 164, 118)')
  await expect.poll(() => galleryLink.evaluate((element) => getComputedStyle(element, '::after').transform)).not.toBe('none')
  await blogLink.hover()
  await expect(blogLink).toHaveCSS('color', 'rgb(224, 51, 171)')
  await expect.poll(() => blogLink.evaluate((element) => getComputedStyle(element, '::after').transform)).toContain('1, 0, 0, 1')
  await expect(page.getByRole('link', { name: 'Поддержать проект' })).toBeVisible()
})

test('blog replaces projects and keeps the editorial card grid responsive', async ({ page }) => {
  await page.goto('/blog')

  await expect(page.getByRole('heading', { name: 'Блог', level: 1 })).toBeVisible()
  await expect(page.locator('body')).toHaveCSS('font-family', /Wix Madefor Text/)
  await expect(page.getByRole('heading', { name: 'Блог', level: 1 })).toHaveCSS('font-family', /Wix Madefor Display/)
  await page.evaluate(() => document.fonts.ready)
  expect(await page.evaluate(() => Array.from(document.fonts, (font) => `${font.family.replaceAll('"', '')}:${font.status}`))).toContain('Wix Madefor Text:loaded')
  expect(await page.evaluate(() => Array.from(document.fonts, (font) => `${font.family.replaceAll('"', '')}:${font.status}`))).toContain('Wix Madefor Display:loaded')
  await expect(page.getByRole('navigation').getByRole('link', { name: 'Блог' })).toHaveClass(/active/)
  const cards = page.locator('.blog-card')
  await expect(cards).toHaveCount(8)
  await expect.poll(() => cards.first().evaluate((element) => getComputedStyle(element, '::before').borderColor)).toBe('rgb(32, 32, 39)')
  await expect(cards.first()).toHaveCSS('border-radius', '0px')
  await expect(page.locator('.blog-grid')).toHaveCSS('grid-template-columns', /\S+ \S+ \S+ \S+/)
  expect((await cards.first().boundingBox())!.height).toBeLessThan(500)

  const firstArticle = page.getByRole('link', { name: 'Читать: Как выбрать график и не исказить данные' })
  const firstTitle = firstArticle.getByRole('heading', { level: 2 })
  const titleBeforeHover = await firstTitle.boundingBox()
  await firstArticle.hover()
  await expect.poll(() => cards.first().evaluate((element) => getComputedStyle(element, '::before').borderColor)).toBe('rgb(219, 90, 90)')
  await expect.poll(() => cards.first().evaluate((element) => getComputedStyle(element, '::before').transform)).not.toBe('none')
  await expect(firstTitle).toHaveCSS('text-decoration-line', 'none')
  const titleAfterHover = await firstTitle.boundingBox()
  expect(titleAfterHover).toEqual(titleBeforeHover)
  await firstArticle.click()
  await expect(page).toHaveURL('/blog/kak-vybrat-grafik')
  await expect(page.getByRole('heading', { name: 'Как выбрать график и не исказить данные', level: 1 })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Начните с вопроса' })).toBeVisible()
  await expect(page.locator('.article-body > header')).toHaveCSS('text-align', 'center')
  await expect(page.locator('.article-body > header .blog-card-meta')).toHaveCSS('justify-content', 'center')
  await page.getByRole('link', { name: 'Все статьи' }).click()
  await expect(page).toHaveURL('/blog')

  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.locator('.blog-grid')).toHaveCSS('grid-template-columns', /^\S+$/)

  await page.goto('/blog?edit=1')
  const uploads = page.locator('.blog-cover-upload input')
  await expect(uploads).toHaveCount(8)
  await uploads.first().setInputFiles('public/favicon.svg')
  await expect(page.locator('.blog-card').first().locator('img')).toBeVisible()

  await page.goto('/projects')
  await expect(page).toHaveURL('/')
  await expect(page.getByText('Мои проекты', { exact: true })).toHaveCount(0)
})
