import { expect, test } from '@playwright/test'

test('support page opens from the sticky header and fits narrow screens', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  await expect(page.locator('.site-header')).toBeVisible()
  await expect(page.locator('.home-intro')).toHaveCount(0)
  await page.evaluate(() => window.scrollTo(0, 1000))
  await page.getByRole('link', { name: 'Поддержать проект', exact: true }).click()
  await expect(page).toHaveURL(/\/support$/)
  await expect(page.locator('.header-support')).toHaveCSS('background-color', 'rgb(228, 165, 44)')
  await expect(page.getByRole('heading', { name: 'Поддержать донатом' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Подписаться на соцсети' })).toBeVisible()
  await expect.poll(() => page.evaluate(() => scrollY)).toBe(0)
  await expect(page.locator('.support-coming')).toHaveText(['Boosty · скоро', 'Соцсети проекта · скоро'])
  await expect(page.locator('.support-options a')).toHaveCount(0)
  await expect(page.getByText('Выберите удобный способ.', { exact: false })).toHaveCount(0)
  await expect(page.locator('.support-donate .lucide-russian-ruble')).toBeVisible()
  await expect(page.locator('.support-ruble-coin > circle')).toBeVisible()
  await expect(page.locator('.support-heading h1 span')).toHaveCSS('background-color', 'rgba(0, 0, 0, 0)')
  await expect(page.locator('.support-heading h1 span')).toHaveCSS('text-decoration-color', 'rgb(228, 165, 44)')
  await page.evaluate(() => document.fonts.ready)
  for (const [width, height] of [[1440, 900], [1280, 720], [1024, 768], [390, 844], [320, 900]]) {
    await page.setViewportSize({ width, height })
    await expect(page.getByRole('navigation', { name: 'Основная навигация' })).toBeVisible()
    const header = page.locator('.site-header')
    const navigation = await header.locator('nav').boundingBox()
    const button = await header.locator('.header-support').boundingBox()
    expect(navigation!.x + navigation!.width).toBeLessThanOrEqual(button!.x)
    expect(button!.x + button!.width).toBeLessThanOrEqual(width)
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(width)
    const main = await page.locator('.support-main').boundingBox()
    expect(main!.y + main!.height).toBeLessThanOrEqual(height + 1)
    await page.screenshot({ path: `/tmp/support-${width}.png`, fullPage: true })
    await page.evaluate(() => window.scrollTo(0, document.documentElement.scrollHeight))
    const footerBox = await page.locator('.site-footer').boundingBox()
    const headerBox = await header.boundingBox()
    expect(footerBox!.y).toBeLessThanOrEqual(headerBox!.y + headerBox!.height + 1)
    await page.screenshot({ path: `/tmp/support-footer-${width}.png` })
    await page.evaluate(() => window.scrollTo(0, 0))
  }
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  const supportButton = page.locator('.header-support')
  await supportButton.hover()
  await expect(supportButton).toHaveCSS('text-decoration-line', 'none')
  const letters = supportButton.locator('.support-label-full .support-letter')
  await expect(letters.first()).toHaveCSS('animation-name', 'support-letter-hop')
  const delays = await letters.evaluateAll((elements) => elements.map((element) => parseFloat(getComputedStyle(element).animationDelay)))
  expect(delays.every((delay, index) => index === 0 || delay > delays[index - 1])).toBe(true)
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await expect(letters.first()).toHaveCSS('animation-name', 'none')
  await page.getByRole('navigation', { name: 'Основная навигация' }).getByRole('link', { name: 'Блог', exact: true }).click()
  await expect(page).toHaveURL(/\/blog$/)
})
