import { expect, test } from '@playwright/test'
import { readFile } from 'node:fs/promises'

test('waffle renders proportions, adjusts the grid and exports SVG and PNG', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto('/editor')
  await page.locator('.upload-card input').setInputFiles({ name: 'shares.csv', mimeType: 'text/csv', buffer: Buffer.from('Категория,Значение\nПоддерживают,73\nНе поддерживают,27') })
  await page.getByRole('button', { name: /Выбрать график/ }).click()
  await page.getByRole('button', { name: 'Вафельная', exact: true }).click()
  await page.getByRole('button', { name: 'Настроить оформление →' }).click()
  const canvas = page.locator('.chart-canvas-shell[data-plot-kind="waffle"]')
  await expect(canvas).toHaveAttribute('data-render-status', 'settled')
  await expect(canvas.locator('svg text').filter({ hasText: '73%' })).toBeVisible()
  const settings = page.locator('details').filter({ has: page.getByText('Сетка и подписи', { exact: true }) })
  if (!(await settings.evaluate((element) => element.hasAttribute('open')))) await settings.locator(':scope > summary').click()
  await expect(page.locator('.legend-settings')).toHaveCount(0)
  const previousRevision = Number(await canvas.getAttribute('data-render-revision'))
  await page.getByRole('spinbutton', { name: 'Столбцов', exact: true }).fill('5')
  await page.getByRole('spinbutton', { name: 'Столбцов', exact: true }).press('Tab')
  await expect(canvas).toHaveAttribute('data-render-status', 'settled')
  await expect.poll(async () => Number(await canvas.getAttribute('data-render-revision'))).toBeGreaterThan(previousRevision)
  await expect(canvas).toHaveAttribute('data-render-status', 'settled')
  await expect(canvas.locator('svg path[fill="#0072b2"]')).toHaveCount(37) // Only grid cells; side captions have no markers or separate legend.
  const paths = canvas.locator('svg path[fill="#0072b2"]')
  const cellIndex = await paths.evaluateAll((elements) => elements.findIndex((element) => { const box = element.getBoundingClientRect(); return box.width > 15 && Math.abs(box.width - box.height) < 1 }))
  const cell = await paths.nth(cellIndex).boundingBox()
  if (!cell) throw new Error('Square is missing')
  await page.mouse.click(cell.x + cell.width / 2, cell.y + cell.height / 2)
  await expect(page.locator('.element-editor')).toContainText('Поддерживают')
  await page.getByRole('button', { name: 'Снять выделение', exact: true }).click()
  await page.screenshot({ path: '/tmp/viiiz-waffle-editor.png', fullPage: true })
  await page.locator('.export-menu > summary').click()
  const svgDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Скачать SVG' }).click()
  const svg = await readFile((await (await svgDownload).path())!, 'utf8')
  expect(svg).toContain('73%')
  expect(svg).toContain('27%')
  const pngDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Скачать PNG' }).click()
  const png = await readFile((await (await pngDownload).path())!)
  expect(png.subarray(1, 4).toString()).toBe('PNG')
  expect(errors).toEqual([])
})

test('waffle supports multiline category captions inside regions, colored side explanations and a top legend', async ({ page }) => {
  await page.goto('/editor')
  await page.locator('.upload-card input').setInputFiles({ name: 'captions.csv', mimeType: 'text/csv', buffer: Buffer.from('Категория,Значение\nПитьевая вода,57\nВоздух,28\nПочва,15') })
  await page.getByRole('button', { name: /Выбрать график/ }).click()
  await page.getByRole('button', { name: 'Вафельная', exact: true }).click()
  await page.getByRole('button', { name: 'Настроить оформление →' }).click()
  const canvas = page.locator('.chart-canvas-shell[data-plot-kind="waffle"]')
  await expect(canvas).toHaveAttribute('data-render-status', 'settled')
  const settings = page.locator('details').filter({ has: page.getByText('Сетка и подписи', { exact: true }) })
  if (!(await settings.evaluate((element) => element.hasAttribute('open')))) await settings.locator(':scope > summary').click()
  await page.getByRole('combobox', { name: 'Направление заполнения' }).selectOption('top')
  await page.getByRole('combobox', { name: 'Цвет подписей' }).selectOption('category')
  await page.getByRole('textbox', { name: 'Текст подписи', exact: true }).fill('Питьевая вода\n12,4 тыс. чел.')
  await page.getByRole('textbox', { name: 'Пояснение', exact: true }).fill('Железо, мышьяк, никель,\nнитриты, свинец и хлор.')
  await expect(canvas.locator('svg text').filter({ hasText: '12,4 тыс. чел.' })).toBeVisible()
  await expect(canvas.locator('svg text').filter({ hasText: 'Железо, мышьяк' })).toHaveAttribute('fill', '#0072b2')
  await page.screenshot({ path: '/tmp/viiiz-waffle-side-captions.png', fullPage: true })
  await page.getByRole('textbox', { name: 'Пояснение', exact: true }).fill('')
  await page.getByRole('combobox', { name: 'Расположение подписей' }).selectOption('inside')
  await page.getByRole('combobox', { name: 'Цвет подписей' }).selectOption('auto')
  await expect(canvas.locator('svg text').filter({ hasText: '12,4 тыс. чел.' })).toHaveAttribute('fill', '#ffffff')
  await expect(canvas.locator('svg text').filter({ hasText: '12,4 тыс. чел.' })).toHaveAttribute('stroke', '#0072b2')
  // SVG paint order must keep the letters above both the grid and their colored backing.
  await expect.poll(() => canvas.locator('svg text').filter({ hasText: '12,4 тыс. чел.' }).evaluate((text) => {
    const box = text.getBoundingClientRect()
    const backgrounds = [...text.closest('svg')!.querySelectorAll('path[fill="#0072b2"]')].filter((path) => {
      const rect = path.getBoundingClientRect()
      return rect.left < box.right && rect.right > box.left && rect.top < box.bottom && rect.bottom > box.top
    })
    return backgrounds.length > 0 && backgrounds.every((path) => Boolean(path.compareDocumentPosition(text) & Node.DOCUMENT_POSITION_FOLLOWING))
  })).toBe(true)
  await page.screenshot({ path: '/tmp/viiiz-waffle-inside-captions.png', fullPage: true })
  await page.locator('.export-menu > summary').click()
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Скачать SVG' }).click()
  const svg = await readFile((await (await download).path())!, 'utf8')
  expect(svg).toContain('12,4 тыс. чел.')
  expect(svg).toContain('stroke="#0072b2"')
  await page.locator('.export-menu > summary').click()
  await page.getByRole('combobox', { name: 'Расположение подписей' }).selectOption('legend')
  await page.getByRole('checkbox', { name: 'Цвет подписей как у категорий' }).press('Space')
  await expect(canvas.locator('svg text').filter({ hasText: '12,4 тыс. чел.' })).toHaveCount(0)
  await expect(canvas.locator('svg text').filter({ hasText: /^Питьевая вода$/ })).toHaveAttribute('fill', '#0072b2')
  await page.screenshot({ path: '/tmp/viiiz-waffle-colored-legend.png', fullPage: true })
  await page.getByRole('checkbox', { name: 'Цвет подписей как у категорий' }).press('Space')
  await expect(canvas.locator('svg text').filter({ hasText: /^Питьевая вода$/ })).toHaveAttribute('fill', '#2b2b2b')
  await page.getByRole('combobox', { name: 'Расположение подписей' }).selectOption('right')
  await expect(canvas.locator('svg path[fill="#0072b2"]')).toHaveCount(57)
  await expect(canvas.locator('svg text').filter({ hasText: '12,4 тыс. чел.' })).toBeVisible()
})
