import { expect, test } from '@playwright/test'
import { readFile } from 'node:fs/promises'

test('Marimekko opens ZywOo data with only translated counts and exports its shares', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/editor')
  await page.getByRole('button', { name: 'Арсенал ZywOo', exact: true }).click()
  const table = page.locator('.review-table')
  await expect(table).toBeVisible()
  for (const text of ['Год', 'Винтовки', 'Снайперские винтовки', 'Пистолеты-пулемёты', 'Пистолеты', 'Гранаты и прочее']) await expect(table).toContainText(text)
  await expect(table.locator('thead th').filter({ hasText: 'Год' })).toContainText('Текст')
  await expect(table).toContainText('2026*')
  await expect(table).not.toContainText(/kills_total|is_partial_year|rifle_share|https:\/\//)
  await expect(page.locator('.settings-panel')).toHaveCount(0)
  await page.getByRole('button', { name: /Выбрать график/ }).click()
  await page.getByRole('button', { name: 'Настроить оформление →' }).click()
  const canvas = page.locator('.chart-canvas-shell')
  await expect(canvas).toHaveAttribute('data-render-status', 'settled')
  await expect(page.locator('.chart-error')).toHaveCount(0)
  for (const text of ['Арсенал ZywOo: откуда берутся киллы', '* 2026 — неполный год', 'Источник: HLTV']) await expect(canvas.locator('svg text').filter({ hasText: text }).first()).toBeVisible()
  await expect(canvas.locator('svg text').filter({ hasText: /^36,51%$/ })).toBeVisible()
  await expect(canvas.locator('svg text').filter({ hasText: /^20\d{2}\*?$/ })).toHaveText([...Array.from({ length: 8 }, (_, index) => String(2018 + index)), '2026*'])
  await canvas.screenshot({ path: '/tmp/viiiz-zywoo-marimekko.png' })
  await page.locator('.export-menu > summary').click()
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Скачать SVG', exact: true }).click()
  const svg = await readFile((await (await download).path())!, 'utf8')
  expect(svg).toContain('ZywOo')
  expect(svg).toContain('Источник: HLTV')
  expect(svg).toContain('36,51%')
})
