import type { ChartConfig, DateLabelFormat, TimeFrequency } from '../core/types'
import { ColorControl, DateControl } from './PickerControls'
import { OptionalNumberInput } from './NumberInput'
import { SettingsCheckbox } from './SettingsCheckbox'

interface Props { config: ChartConfig; xKind: 'date' | 'number' | 'other'; frequency?: TimeFrequency; distributionOrientation?: 'horizontal' | 'vertical'; onChange(config: ChartConfig): void }
const years: Array<[DateLabelFormat, string]> = [['year-full', 'Только годы: 2015, 2016'], ['year-first-full', "Только годы: 2015, '16"], ['year-short', "Только годы: '15, '16"]]
const halves: Array<[DateLabelFormat, string]> = [['half-only-ru', 'П1, П2'], ['half-year-ru', 'П1 2015'], ['year-half-ru', '2015 · П1'], ['half-only', 'H1, H2'], ['half-year-en', 'H1 2015'], ['year-half-en', '2015 H1']]
const quarters: Array<[DateLabelFormat, string]> = [['quarter-context-ru', 'Кварталы, год под первым'], ['quarter-only-ru', 'К1, К2'], ['quarter-year', 'К1 2015'], ['year-quarter', '2015 · К1'], ['quarter-context-en', 'Q1–Q4, год под первым'], ['quarter-only', 'Q1, Q2'], ['quarter-year-en', 'Q1 2015'], ['year-quarter-en', '2015 Q1']]
const months: Array<[DateLabelFormat, string]> = [['month-context-ru', 'Месяцы, год под первым'], ['month-full-ru', 'январь, февраль'], ['month-only-ru', 'янв., февр.'], ['month-year', 'январь 2015'], ['month-short-year', "янв. '15"], ['year-month-ru', '2015 янв.'], ['month-number', '01, 02'], ['month-number-year', '01.2015'], ['year-month', '2015-01'], ['month-context-en', 'Months, year under first'], ['month-only-en', 'Jan, Feb'], ['month-en-year', 'Jan 2015'], ['year-month-en', '2015 Jan']]
const weeks: Array<[DateLabelFormat, string]> = [['week-context-ru', 'Недели, год под первой'], ['week-only-ru', 'Нед. 1, Нед. 2'], ['week-year', 'Нед. 1 · 2015'], ['year-week-ru', '2015 · нед. 1'], ['week-context-en', 'W01–W53, год под первой'], ['week-only', 'W01, W02'], ['week-year-en', 'W01 2015'], ['year-week-en', '2015-W01']]
const days: Array<[DateLabelFormat, string]> = [['day-context-month-ru', 'Дни, месяц под первой датой'], ['day-month-year', '01.01.2015'], ['date-dmy-ru', '01 апр. 2015'], ['day-month', '01.04'], ['day-context-month-en', 'Days, month under first date'], ['date-dmy-slash', '01/04/2015'], ['date-mdy-slash', '04/01/2015'], ['iso', '2015-04-01'], ['date-dmy-en', '01 Apr 2015'], ['date-mdy-en', 'Apr 01, 2015']]
const formats: Record<TimeFrequency, Array<[DateLabelFormat, string]>> = {
  annual: years,
  semiannual: [...halves, ...years],
  quarterly: [...quarters, ...halves, ...years],
  monthly: [...months, ...quarters, ...halves, ...years],
  weekly: [...days, ...weeks, ...months, ...quarters, ...halves, ...years],
  daily: [...days, ...weeks, ...months, ...quarters, ...halves, ...years],
  irregular: [...days, ...weeks, ...months, ...quarters, ...halves, ...years],
}
const formatGroups = [
  ['day', 'Дни и полные даты'], ['week', 'Недели'], ['month', 'Месяцы'], ['quarter', 'Кварталы'], ['half', 'Полугодия'], ['year', 'Годы'],
] as const
type FormatGroup = typeof formatGroups[number][0]
const formatGroup = (format: DateLabelFormat): FormatGroup => format.includes('week') ? 'week' : format.includes('month') ? 'month' : format.includes('quarter') ? 'quarter' : format.includes('half') ? 'half' : format.includes('year') && !format.startsWith('day-') && !format.startsWith('date-') ? 'year' : 'day'
const shortcuts: Record<TimeFrequency, Array<[DateLabelFormat, string]>> = {
  daily: [['day-context-month-ru', 'Дни'], ['week-context-ru', 'Недели'], ['month-context-ru', 'Месяцы'], ['year-first-full', 'Годы']],
  weekly: [['week-context-ru', 'Недели'], ['month-context-ru', 'Месяцы'], ['quarter-context-ru', 'Кварталы'], ['year-first-full', 'Годы']],
  monthly: [['month-context-ru', 'Месяцы'], ['quarter-context-ru', 'Кварталы'], ['year-first-full', 'Годы']],
  quarterly: [['quarter-context-ru', 'Кварталы'], ['year-first-full', 'Годы']],
  semiannual: [['half-year-ru', 'Полугодия'], ['year-first-full', 'Годы']],
  annual: [['year-full', 'Годы']],
  irregular: [['day-context-month-ru', 'Дни'], ['month-context-ru', 'Месяцы'], ['year-first-full', 'Годы']],
}
const shortcutPreview: Partial<Record<DateLabelFormat, string>> = {
  'day-context-month-ru': '1\nапр.', 'week-context-ru': 'Нед. 1\n2025', 'month-context-ru': 'янв.\n2025',
  'quarter-context-ru': 'К1\n2025', 'half-year-ru': 'П1 2025', 'year-first-full': "2025 · ’26", 'year-full': '2025',
}
export function AxisScaleFields({ config, xKind, frequency = 'irregular', distributionOrientation, onChange }: Props) {
  const set = (values: Partial<ChartConfig>) => onChange({ ...config, ...values })
  if (distributionOrientation) return <section className="axis-scale-fields">
    <strong>Шкала значений · {distributionOrientation === 'horizontal' ? 'горизонтальная ось' : 'вертикальная ось'}</strong>
    <div className="fred-grid"><label>Минимум<OptionalNumberInput value={config.yAxisMin} onValueChange={(yAxisMin) => set({ yAxisMin })}/></label><label>Максимум<OptionalNumberInput value={config.yAxisMax} onValueChange={(yAxisMax) => set({ yAxisMax })}/></label></div>
    <label>Шаг шкалы<OptionalNumberInput min={0} value={config.yAxisStep} onValueChange={(yAxisStep) => set({ yAxisStep: yAxisStep != null && yAxisStep > 0 ? yAxisStep : null })}/><small>Пустые поля — красивый диапазон и шаг по данным. Частота гистограммы и плотность KDE масштабируются автоматически.</small></label>
    <button type="button" className="reset-element" onClick={() => set({ yAxisMin: null, yAxisMax: null, yAxisStep: null, yAxisScaleType: 'linear', showZeroLine: false })}>Автоматический диапазон</button>
  </section>
  const selectedFormat = config.dateLabelFormat ?? 'auto'
  const availableFormats = formats[frequency].filter(([value]) => value !== 'auto')
  return <section className="axis-scale-fields">
    {xKind !== 'other' && <><strong>Ось X</strong>{xKind === 'date' ? <div className="date-range-control"><div className="date-range-title"><span>Диапазон данных</span>{(config.xAxisMin || config.xAxisMax) && <button type="button" onClick={() => set({ xAxisMin: '', xAxisMax: '' })}>Сбросить</button>}</div><div className="date-range-grid"><label><span>От</span><DateControl label="Дата начала диапазона" value={config.xAxisMin ?? ''} max={config.xAxisMax || undefined} onChange={(xAxisMin) => set({ xAxisMin })}/></label><i aria-hidden="true">→</i><label><span>До</span><DateControl label="Дата конца диапазона" value={config.xAxisMax ?? ''} min={config.xAxisMin || undefined} onChange={(xAxisMax) => set({ xAxisMax })}/></label></div><small>Пустые поля используют весь доступный период.</small></div> : <div className="fred-grid"><label>Минимум<input type="number" value={config.xAxisMin ?? ''} placeholder="Авто" onChange={(event) => set({ xAxisMin: event.target.value })}/></label><label>Максимум<input type="number" value={config.xAxisMax ?? ''} placeholder="Авто" onChange={(event) => set({ xAxisMax: event.target.value })}/></label></div>}{xKind === 'date' ? <><label>Единица интервала<select value={config.dateAxisStepUnit ?? 'auto'} onChange={(event) => set({ dateAxisStepUnit: event.target.value as ChartConfig['dateAxisStepUnit'], xAxisStep: event.target.value === 'auto' ? null : config.xAxisStep ?? 1 })}><option value="auto">Автоматически по формату</option><option value="day">День</option><option value="week">Неделя</option><option value="month">Месяц</option><option value="quarter">Квартал</option><option value="half">Полугодие</option><option value="year">Год</option></select></label><label>Показывать каждый N-й период<OptionalNumberInput min={1} value={config.xAxisStep} onValueChange={(value) => set({ xAxisStep: value == null ? null : Math.max(1, Math.round(value)) })}/><small>Например: «Год» и 2 — показывать каждый второй год.</small></label></> : <label>Шаг шкалы<OptionalNumberInput min={1} value={config.xAxisStep} onValueChange={(value) => set({ xAxisStep: value == null ? null : Math.max(1, value) })}/><small>Пустое поле — автоматический шаг.</small></label>}</>}
    {xKind === 'date' && <div className="date-axis-format">
      <div className="date-format-heading"><strong>Подписи дат</strong><small>Частота данных: {frequency === 'daily' ? 'дни' : frequency === 'weekly' ? 'недели' : frequency === 'monthly' ? 'месяцы' : frequency === 'quarterly' ? 'кварталы' : frequency === 'semiannual' ? 'полугодия' : frequency === 'annual' ? 'годы' : 'нерегулярная'}</small></div>
      <div className="date-format-shortcuts"><button type="button" className={selectedFormat === 'auto' ? 'active' : ''} aria-pressed={selectedFormat === 'auto'} onClick={() => set({ dateLabelFormat: 'auto' })}><span className="date-format-icon">A</span><span><strong>Авто</strong><small>По данным</small></span></button>{shortcuts[frequency].map(([value, label]) => <button type="button" className={selectedFormat === value ? 'active' : ''} aria-pressed={selectedFormat === value} onClick={() => set({ dateLabelFormat: value })} key={value}><span className="date-format-icon">{shortcutPreview[value]?.split('\n')[0] ?? 'Aa'}</span><span><strong>{label}</strong><small>{shortcutPreview[value]?.replace('\n', ' / ') ?? 'Формат периода'}</small></span></button>)}</div>
      <label>Точный формат<select value={selectedFormat} onChange={(event) => set({ dateLabelFormat: event.target.value as DateLabelFormat })}><option value="auto">Автоматически для этих данных</option>{formatGroups.map(([group, label]) => { const options = availableFormats.filter(([value]) => formatGroup(value) === group); return options.length ? <optgroup label={label} key={group}>{options.map(([value, optionLabel]) => <option value={value} key={value}>{optionLabel}</option>)}</optgroup> : null })}</select></label>
      <div className="date-anchor-control"><div><span>Начать подписи с</span><small>Точка отсчёта выбранного шага</small></div><div className="date-anchor-input"><DateControl label="Начать подписи с" value={config.dateAxisAnchor ?? ''} min={config.xAxisMin || undefined} max={config.xAxisMax || undefined} onChange={(dateAxisAnchor) => set({ dateAxisAnchor: dateAxisAnchor || undefined })}/></div><p>Если дата не задана, отсчёт начинается с первого значения ряда.</p></div>
    </div>}
    <div className="settings-divider"/><strong>Размещение подписей X</strong><div className="fred-grid"><label>Поворот, °<select value={config.xAxisLabelRotate ?? 'auto'} onChange={(event) => set({ xAxisLabelRotate: event.target.value === 'auto' ? 'auto' : Number(event.target.value) as Exclude<ChartConfig['xAxisLabelRotate'], 'auto'> })}><option value="auto">Автоматически</option>{[0, 30, 45, 60, 90].map((value) => <option value={value} key={value}>{value}°</option>)}</select></label><label>Длинный текст<select value={config.xAxisLabelOverflow ?? 'auto'} onChange={(event) => set({ xAxisLabelOverflow: event.target.value as ChartConfig['xAxisLabelOverflow'] })}><option value="auto">Не переносить</option><option value="wrap">Переносить</option><option value="truncate">Сокращать</option></select></label></div>
    <div className="settings-divider"/><strong>Ось Y</strong><div className="fred-grid"><label>Минимум<OptionalNumberInput disabled={config.yAxisScaleType === 'log'} value={config.yAxisMin} onValueChange={(value) => set({ yAxisMin: value })}/></label><label>Максимум<OptionalNumberInput disabled={config.yAxisScaleType === 'log'} value={config.yAxisMax} onValueChange={(value) => set({ yAxisMax: value })}/></label></div><label>Шаг шкалы<OptionalNumberInput disabled={config.yAxisScaleType === 'log'} min={0} value={config.yAxisStep} onValueChange={(value) => set({ yAxisStep: value != null && value > 0 ? value : null })}/><small>{config.yAxisScaleType === 'log' ? 'Диапазон и деления рассчитываются автоматически по положительным значениям.' : 'Пустые поля — красивый диапазон и шаг по данным.'}</small></label>
    <label>Тип шкалы<select value={config.yAxisScaleType ?? 'linear'} onChange={(event) => set({ yAxisScaleType: event.target.value as ChartConfig['yAxisScaleType'], ...(event.target.value === 'log' ? { yAxisMin: null, yAxisStep: null, showZeroLine: false } : {}) })}><option value="linear">Линейная</option><option value="log">Логарифмическая</option></select></label>
    <SettingsCheckbox isDisabled={config.yAxisScaleType === 'log'} isSelected={config.showZeroLine ?? false} onChange={(showZeroLine) => set({ showZeroLine })}>Выделить нулевую линию</SettingsCheckbox>
    {(config.showZeroLine ?? false) && <><div className="fred-grid"><label>Цвет нулевой линии<ColorControl value={config.zeroLineColor ?? '#8a8791'} onChange={(zeroLineColor) => set({ zeroLineColor })}/></label><label>Толщина<OptionalNumberInput min={0.5} value={config.zeroLineWidth ?? 1} onValueChange={(value) => set({ zeroLineWidth: value ?? 1 })}/></label></div><label>Тип нулевой линии<select value={config.zeroLineType ?? 'solid'} onChange={(event) => set({ zeroLineType: event.target.value as ChartConfig['zeroLineType'] })}><option value="solid">Сплошная</option><option value="dashed">Пунктирная</option><option value="dotted">Точечная</option></select></label></>}
    <button type="button" className="reset-element" onClick={() => set({ xAxisMin: '', xAxisMax: '', xAxisStep: null, dateAxisStepUnit: 'auto', dateAxisAnchor: undefined, yAxisMin: null, yAxisMax: null, yAxisStep: null })}>Автоматический диапазон</button>
  </section>
}
