import { getSeriesColor } from '../core/chartRegistry'
import { distributionVisualDefaults } from '../core/chartKinds'
import type { ChartConfig, DataTable } from '../core/types'
import { ColorControl } from './PickerControls'
import { NumberInput, OptionalNumberInput } from './NumberInput'
import { SettingsCheckbox } from './SettingsCheckbox'
import './DistributionSettings.css'

interface Props { config: ChartConfig; table: DataTable; onChange(config: ChartConfig): void }

export function DistributionSettings({ config, table, onChange }: Props) {
  const set = (values: Partial<ChartConfig>) => onChange({ ...config, ...values })
  const points = config.kind === 'strip-plot' || config.kind === 'jitter-plot' || config.kind === 'beeswarm' || config.kind === 'counts-plot'
  const density = config.kind === 'violinplot' || config.kind === 'raincloud' || config.kind === 'kde-plot' || config.kind === 'ridgeline'
  const rawMarks = points || config.kind === 'barcode-plot'
  const pointLayer = points || config.kind === 'violinplot' || config.kind === 'raincloud' || config.kind === 'boxplot'
  const labelsLayer = pointLayer || config.kind === 'barcode-plot'
  const labelsSupported = config.kind !== 'counts-plot'
  const groupField = config.distributionGroupField
  const discovered = groupField ? [...new Set(table.rows.flatMap((row) => config.yFields.some((field) => typeof row[field] === 'number' && Number.isFinite(row[field])) ? [String(row[groupField] ?? 'Без категории')] : []))] : []
  const categories = [...(config.distributionCategoryOrder ?? []).filter((category) => discovered.includes(category)), ...discovered.filter((category) => !(config.distributionCategoryOrder ?? []).includes(category))]
  const categoryStyles = config.distributionCategoryStyles ?? {}
  const visibleCategories = categories.filter((category) => categoryStyles[category]?.visible !== false)
  const layoutMode = config.distributionLayoutMode ?? 'measures'
  const splitOptions = layoutMode === 'measures' ? visibleCategories : config.yFields
  const optionLabel = (value: string) => layoutMode === 'measures' ? categoryStyles[value]?.label?.trim() || value : value
  const splitFirst = splitOptions.includes(config.distributionViolinSplitFirst ?? '') ? config.distributionViolinSplitFirst! : splitOptions[0] ?? ''
  const splitSecond = splitOptions.includes(config.distributionViolinSplitSecond ?? '') && config.distributionViolinSplitSecond !== splitFirst ? config.distributionViolinSplitSecond! : splitOptions.find((option) => option !== splitFirst) ?? ''
  const patchCategory = (category: string, values: Partial<NonNullable<ChartConfig['distributionCategoryStyles']>[string]>) => set({ distributionCategoryStyles: { ...categoryStyles, [category]: { ...categoryStyles[category], ...values } } })
  const moveCategory = (category: string, nextIndex: number) => {
    const order = [...categories], current = order.indexOf(category)
    if (current < 0 || nextIndex < 0 || nextIndex >= order.length) return
    order.splice(nextIndex, 0, ...order.splice(current, 1))
    set({ distributionCategoryOrder: order })
  }
  const setViolinMode = (distributionViolinMode: NonNullable<ChartConfig['distributionViolinMode']>) => set({ distributionViolinMode, ...(distributionViolinMode === 'split' ? { distributionViolinSplitFirst: splitFirst, distributionViolinSplitSecond: splitSecond } : {}) })

  return <details className="settings-group distribution-settings"><summary>Форма распределения</summary><div>
    {groupField && <label>Что расположить на оси<select value={layoutMode} onChange={(event) => set({ distributionLayoutMode: event.target.value as ChartConfig['distributionLayoutMode'] })}><option value="measures">Показатели — категории различаются цветом</option><option value="categories">Категории — показатели различаются цветом</option></select></label>}
    <label>Ориентация<select value={config.distributionOrientation ?? 'horizontal'} onChange={(event) => { const distributionOrientation = event.target.value as NonNullable<ChartConfig['distributionOrientation']>; set({ distributionOrientation, ...(distributionOrientation === 'horizontal' ? { showXAxisLine: true, showYAxisLine: false, showXTicks: true, showYTicks: false, showHorizontalGrid: true, showVerticalGrid: false } : { showXAxisLine: false, showYAxisLine: true, showXTicks: false, showYTicks: true, showHorizontalGrid: false, showVerticalGrid: true }) }) }}><option value="horizontal">Горизонтальная</option><option value="vertical">Вертикальная</option></select></label>
    {config.kind !== 'histogram' && config.kind !== 'kde-plot' && <label>Ширина ряда, %<NumberInput min="15" max="90" value={config.distributionWidth ?? 62} onValueChange={(distributionWidth) => set({ distributionWidth })}/></label>}
    {config.kind === 'histogram' && <><label>Количество интервалов<NumberInput min="3" max="80" step="1" value={config.distributionBinCount ?? 12} onValueChange={(distributionBinCount) => set({ distributionBinCount: Math.round(distributionBinCount) })}/></label><div className="settings-pair"><label>Начало диапазона<OptionalNumberInput value={config.distributionHistogramMin} onValueChange={(distributionHistogramMin) => set({ distributionHistogramMin })}/></label><label>Конец диапазона<OptionalNumberInput value={config.distributionHistogramMax} onValueChange={(distributionHistogramMax) => set({ distributionHistogramMax })}/></label></div><label>Прозрачность столбцов<NumberInput min="0.1" max="1" step="0.05" value={config.distributionPointOpacity ?? .4} onValueChange={(distributionPointOpacity) => set({ distributionPointOpacity })}/></label><label>Подписи столбцов<select value={config.distributionHistogramLabels ?? 'none'} onChange={(event) => set({ distributionHistogramLabels: event.target.value as ChartConfig['distributionHistogramLabels'] })}><option value="none">Не показывать</option><option value="count">Частота</option><option value="range">Диапазон</option></select></label>{config.distributionHistogramLabels === 'range' && <label>Знаков в границах<NumberInput min="0" max="6" step="1" value={config.distributionHistogramRangeDecimals ?? 1} onValueChange={(distributionHistogramRangeDecimals) => set({ distributionHistogramRangeDecimals: Math.round(distributionHistogramRangeDecimals) })}/></label>}</>}
    {density && <><label>Сглаживание плотности<NumberInput min="0.04" max="0.5" step="0.01" value={config.distributionBandwidth ?? .14} onValueChange={(distributionBandwidth) => set({ distributionBandwidth })}/></label><label>Прозрачность заливки<NumberInput min="0" max="1" step="0.05" value={config.distributionDensityFillOpacity ?? .2} onValueChange={(distributionDensityFillOpacity) => set({ distributionDensityFillOpacity })}/></label></>}
    {config.kind === 'ridgeline' && <label>Перекрытие рядов, %<NumberInput min="0" max="80" step="5" value={config.distributionRidgelineOverlap ?? 35} onValueChange={(distributionRidgelineOverlap) => set({ distributionRidgelineOverlap })}/></label>}
    {pointLayer && <><label>Размер точек, px<NumberInput min="3" max="30" value={config.distributionPointSize ?? 9} onValueChange={(distributionPointSize) => set({ distributionPointSize })}/></label><label>Прозрачность точек<NumberInput min="0.1" max="1" step="0.05" value={config.distributionPointOpacity ?? .4} onValueChange={(distributionPointOpacity) => set({ distributionPointOpacity })}/></label></>}
    {config.kind === 'barcode-plot' && <><label>Толщина штрихов, px<NumberInput min="0.5" max="8" step="0.5" value={config.distributionTickWidth ?? 2} onValueChange={(distributionTickWidth) => set({ distributionTickWidth })}/></label><label>Прозрачность штрихов<NumberInput min="0.1" max="1" step="0.05" value={config.distributionPointOpacity ?? .4} onValueChange={(distributionPointOpacity) => set({ distributionPointOpacity })}/></label></>}
    {config.kind === 'jitter-plot' && <label>Разброс точек<NumberInput min="0" max="0.45" step="0.05" value={config.distributionJitter ?? .32} onValueChange={(distributionJitter) => set({ distributionJitter })}/></label>}
    {config.kind === 'violinplot' && <><label>Форма скрипки<select value={config.distributionViolinMode ?? 'full'} onChange={(event) => setViolinMode(event.target.value as NonNullable<ChartConfig['distributionViolinMode']>)}><option value="full">Полная</option><option value="half">Половина</option><option value="split" disabled={splitOptions.length < 2}>Разделённая на две выбранные группы</option></select></label>
      <label>Медиана и IQR<select value={config.distributionViolinSummaryMode ?? 'box'} onChange={(event) => set({ distributionViolinSummaryMode: event.target.value as ChartConfig['distributionViolinSummaryMode'] })}><option value="box">Внутренний бокс</option><option value="lines">Поперечные линии Q1, медианы и Q3</option></select></label>
      <SettingsCheckbox isSelected={config.distributionViolinShowWhiskers ?? true} onChange={(distributionViolinShowWhiskers) => set({ distributionViolinShowWhiskers })}>Показывать диапазон 1,5 IQR</SettingsCheckbox>
      {config.distributionViolinMode === 'half' && <label>Сторона половины<select value={config.distributionViolinHalfSide ?? 'second'} onChange={(event) => set({ distributionViolinHalfSide: event.target.value as ChartConfig['distributionViolinHalfSide'] })}><option value="first">Слева / сверху</option><option value="second">Справа / снизу</option></select></label>}
      {config.distributionViolinMode === 'split' && splitOptions.length >= 2 && <div className="distribution-split-pair"><label>Первая половина<select value={splitFirst} onChange={(event) => set({ distributionViolinSplitFirst: event.target.value, distributionViolinSplitSecond: event.target.value === splitSecond ? splitOptions.find((option) => option !== event.target.value) : splitSecond })}>{splitOptions.filter((option) => option !== splitSecond).map((option) => <option value={option} key={option}>{optionLabel(option)}</option>)}</select></label><label>Вторая половина<select value={splitSecond} onChange={(event) => set({ distributionViolinSplitSecond: event.target.value })}>{splitOptions.filter((option) => option !== splitFirst).map((option) => <option value={option} key={option}>{optionLabel(option)}</option>)}</select></label></div>}
      {config.distributionViolinMode === 'split' && splitOptions.length < 2 && <small className="settings-note">Для разделённой скрипки оставьте видимыми как минимум две группы.</small>}
      <SettingsCheckbox isSelected={config.distributionShowPoints ?? true} onChange={(distributionShowPoints) => set({ distributionShowPoints })}>Показывать наблюдения поверх формы</SettingsCheckbox></>}
    {config.kind === 'raincloud' && <><label>Расположение точек<select value={config.distributionRaincloudPointMode ?? 'overlay'} onChange={(event) => set({ distributionRaincloudPointMode: event.target.value as ChartConfig['distributionRaincloudPointMode'] })}><option value="overlay">Поверх boxplot</option><option value="separate">Отдельной строкой</option></select></label><SettingsCheckbox isSelected={config.distributionViolinShowWhiskers ?? true} onChange={(distributionViolinShowWhiskers) => set({ distributionViolinShowWhiskers })}>Показывать диапазон 1,5 IQR</SettingsCheckbox><SettingsCheckbox isSelected={config.distributionShowPoints ?? true} onChange={(distributionShowPoints) => set({ distributionShowPoints })}>Показывать наблюдения</SettingsCheckbox></>}
    {config.kind === 'boxplot' && <><SettingsCheckbox isSelected={config.distributionShowAllPoints ?? false} onChange={(distributionShowAllPoints) => set({ distributionShowAllPoints })}>Показывать все наблюдения</SettingsCheckbox>{!(config.distributionShowAllPoints ?? false) && <SettingsCheckbox isSelected={config.distributionShowOutliers ?? true} onChange={(distributionShowOutliers) => set({ distributionShowOutliers })}>Показывать выбросы</SettingsCheckbox>}</>}
    {labelsLayer && <fieldset><legend>Подписи наблюдений</legend>{labelsSupported ? <>
      <label>Текст подписи<select value={config.distributionLabelField ?? ''} onChange={(event) => set({ distributionLabelField: event.target.value })}><option value="">Значение наблюдения</option>{table.columns.map((column) => <option value={column} key={column}>{column}</option>)}</select></label>
      <div className="settings-pair settings-pair--toggle"><SettingsCheckbox isSelected={config.distributionShowLabels ?? false} onChange={(distributionShowLabels) => set({ distributionShowLabels, ...(distributionShowLabels && config.kind === 'violinplot' ? { distributionShowPoints: true } : {}), ...(distributionShowLabels && config.kind === 'boxplot' ? { distributionShowAllPoints: true } : {}) })}>Показывать</SettingsCheckbox><label>Положение<select value={config.distributionLabelPosition ?? ((config.distributionOrientation ?? 'horizontal') === 'horizontal' ? 'right' : 'top')} onChange={(event) => set({ distributionLabelPosition: event.target.value as ChartConfig['distributionLabelPosition'] })}><option value="top">Сверху</option><option value="right">Справа</option><option value="bottom">Снизу</option><option value="left">Слева</option></select></label></div>
      <small className="settings-note">Стиль текста настраивается в разделе «Подписи значений».</small>
    </> : <small className="settings-note">Counts Plot объединяет совпадающие значения в одну точку, поэтому подписи отдельных строк здесь недоступны.</small>}</fieldset>}
    {rawMarks ? <><SettingsCheckbox isSelected={config.distributionShowMedian ?? true} onChange={(distributionShowMedian) => set({ distributionShowMedian })}>Показывать центральную линию</SettingsCheckbox>{(config.distributionShowMedian ?? true) && <label>Значение центральной линии<select value={config.distributionSummaryStatistic ?? 'median'} onChange={(event) => set({ distributionSummaryStatistic: event.target.value as ChartConfig['distributionSummaryStatistic'] })}><option value="median">Медиана</option><option value="mean">Среднее значение</option></select></label>}</> : <SettingsCheckbox isSelected={config.distributionShowMedian ?? true} onChange={(distributionShowMedian) => set({ distributionShowMedian })}>Показывать медиану</SettingsCheckbox>}
    {(config.distributionShowMedian ?? true) && <div className="settings-pair"><label>Толщина линии, px<NumberInput min="0.5" max="12" step="0.5" value={config.distributionSummaryWidth ?? 3} onValueChange={(distributionSummaryWidth) => set({ distributionSummaryWidth })}/></label><label>Длина линии, %<NumberInput min="20" max="200" step="5" value={config.distributionSummaryLength ?? 100} onValueChange={(distributionSummaryLength) => set({ distributionSummaryLength })}/></label></div>}

    {!!categories.length && <section className="distribution-category-editor"><header><div><strong>Категории</strong><small>{visibleCategories.length} из {categories.length} отображаются</small></div><span>{layoutMode === 'measures' ? 'Цвет категории' : 'Цвет задаётся показателем'}</span></header><div>{categories.map((category, index) => { const style = categoryStyles[category] ?? {}, count = table.rows.filter((row) => String(row[groupField!] ?? 'Без категории') === category && config.yFields.some((field) => typeof row[field] === 'number' && Number.isFinite(row[field]))).length, visible = style.visible !== false; return <div className={visible ? '' : 'is-hidden'} key={category}>
      <SettingsCheckbox className="distribution-category-toggle" ariaLabel={`Показывать категорию ${category}`} isSelected={visible} isDisabled={visible && visibleCategories.length === 1} onChange={(nextVisible) => patchCategory(category, { visible: nextVisible })}><span className="sr-only">Показывать</span></SettingsCheckbox>
      {layoutMode === 'measures' ? <ColorControl compact title={`Цвет категории ${category}`} value={style.color ?? getSeriesColor(config, category, index)} swatches={config.palette} onChange={(color) => patchCategory(category, { color })}/> : <i className="distribution-category-neutral"/>}
      <label><input aria-label={`Подпись категории ${category}`} value={style.label ?? ''} placeholder={category} onChange={(event) => patchCategory(category, { label: event.target.value })}/><small>строк с данными: {count}</small></label>
      <span><button type="button" aria-label={`Поднять категорию ${category}`} disabled={index === 0} onClick={() => moveCategory(category, index - 1)}>↑</button><button type="button" aria-label={`Опустить категорию ${category}`} disabled={index === categories.length - 1} onClick={() => moveCategory(category, index + 1)}>↓</button></span>
    </div> })}</div></section>}
    <small className="settings-note">В режиме показателей цвет обозначает категорию. В обратном режиме каждая категория становится позицией оси, а цвет обозначает показатель.</small>
    <button type="button" className="reset-element" onClick={() => set({ ...distributionVisualDefaults(config.kind), distributionLayoutMode: 'measures', distributionCategoryOrder: undefined, distributionCategoryStyles: undefined, distributionOrientation: 'horizontal', distributionPointOpacity: .4, distributionTickWidth: 2, distributionJitter: .32, distributionBandwidth: .14, distributionViolinMode: 'full', distributionViolinSummaryMode: 'box', distributionViolinShowWhiskers: true, distributionViolinHalfSide: 'second', distributionViolinSplitFirst: undefined, distributionViolinSplitSecond: undefined, distributionShowPoints: true, distributionShowAllPoints: false, distributionShowMedian: true, distributionSummaryStatistic: 'median', distributionShowOutliers: true, distributionBinCount: 12, distributionHistogramMin: null, distributionHistogramMax: null, distributionHistogramLabels: 'none', distributionHistogramRangeDecimals: 1, distributionDensityFillOpacity: .2, distributionRidgelineOverlap: 35, distributionLabelField: undefined, distributionShowLabels: false, distributionLabelPosition: 'right' })}>Сбросить параметры</button>
  </div></details>
}
