import type { ChartConfig } from '../core/types'
import { formatChartNumber } from '../core/numberFormat'

export function NumberFormatSettings({ config, onChange }: { config: ChartConfig; onChange(config: ChartConfig): void }) {
  const patch = (values: Partial<ChartConfig>) => onChange({ ...config, ...values })
  const operation = config.numberOperation ?? 'none'
  const preview = `${config.numberPrefix ?? ''}${formatChartNumber(1234567.89, config)}${config.numberSuffix ?? ''}`
  return <details className="settings-group number-format-settings">
    <summary>Формат чисел</summary>
    <div>
      <section className="number-format-card"><header><b>Запись числа</b><small>Как выглядят разделители и дробная часть</small></header><div className="fred-grid"><label>Разделители<select value={config.numberLocale ?? 'ru-RU'} onChange={(event) => patch({ numberLocale: event.target.value as ChartConfig['numberLocale'] })}><option value="ru-RU">1 234,5</option><option value="en-US">1,234.5</option></select></label><label>Знаков после запятой<select value={config.numberDecimals == null ? 'auto' : String(config.numberDecimals)} onChange={(event) => patch({ numberDecimals: event.target.value === 'auto' ? null : Number(event.target.value) })}><option value="auto">Автоматически</option>{[0, 1, 2, 3, 4].map((value) => <option value={value} key={value}>{value}</option>)}</select></label></div><label className="check"><input type="checkbox" checked={config.numberGrouping ?? true} onChange={(event) => patch({ numberGrouping: event.target.checked })}/>Разделять группы разрядов</label></section>
      <section className="number-format-card"><header><b>Преобразование значений</b><small>Исходные данные не изменяются</small></header><div className="number-operation" role="group" aria-label="Преобразование чисел">{([['none', 'Без изменений'], ['divide', 'Делить'], ['multiply', 'Умножать']] as const).map(([value, label]) => <button type="button" className={operation === value ? 'active' : ''} aria-pressed={operation === value} onClick={() => patch({ numberOperation: value })} key={value}>{label}</button>)}</div>{operation !== 'none' && <label>{operation === 'divide' ? 'Делить на' : 'Умножать на'}<input type="number" min="0.0000001" step="any" value={config.numberFactor ?? 1} onChange={(event) => patch({ numberFactor: Math.max(0.0000001, Math.abs(Number(event.target.value) || 1)) })}/><small>Например, деление на 1 000 покажет 1 500 как 1,5.</small></label>}</section>
      <section className="number-format-card number-affix-card"><header><b>Верхняя подпись оси Y</b><small>Аффиксы применяются только к верхнему делению</small></header><div className="fred-grid"><label>Перед числом<input className="text-input" value={config.numberPrefix ?? ''} placeholder="+" onChange={(event) => patch({ numberPrefix: event.target.value })}/></label><label>После числа<input className="text-input" value={config.numberSuffix ?? ''} placeholder=" % осуждённых" onChange={(event) => patch({ numberSuffix: event.target.value })}/></label></div><div className="number-affix-preview"><span>Предпросмотр</span><b>{preview}</b></div></section>
      <section className="number-format-card number-affix-card"><header><b>Крайние подписи числовой оси X</b><small>Единица измерения после первого или последнего числа</small></header><div className="fred-grid"><label>После первого значения<input className="text-input" value={config.xAxisStartLabel ?? ''} placeholder=" лет" onChange={(event) => patch({ xAxisStartLabel: event.target.value || undefined })}/></label><label>После последнего значения<input className="text-input" value={config.xAxisEndLabel ?? ''} placeholder=" лет" onChange={(event) => patch({ xAxisEndLabel: event.target.value || undefined })}/></label></div><p className="number-format-hint">Например: «6 лет» слева или «80 лет» справа. Для дат эти поля не применяются.</p></section>
      <section className="number-format-card"><header><b>Особое значение</b><small>Необязательная замена нуля</small></header><label>Подпись для нуля<input className="text-input" value={config.numberZeroLabel ?? ''} placeholder="0" onChange={(event) => patch({ numberZeroLabel: event.target.value || undefined })}/></label></section>
      <button type="button" className="reset-element" onClick={() => patch({ numberLocale: 'ru-RU', numberDecimals: null, numberOperation: 'none', numberFactor: 1, numberPrefix: '', numberSuffix: '', numberGrouping: true, numberZeroLabel: undefined, xAxisStartLabel: undefined, xAxisEndLabel: undefined })}>Вернуть стандартный формат</button>
    </div>
  </details>
}
