import { nativeGraphicTextStyle, renderNativeBarScene } from './renderBarScene'
import type { ResolvedHeatmapScene } from '../../chart-types/heatmap/layout'
import { measureTextWidth } from '../../../core/textMetrics'
import { verticalAxisLabelPlacement } from '../../chart-layout/axisLabelPlacement'

const escapeHtml = (value: unknown) => String(value ?? '').replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[character]!)

export function renderHeatmapScene(scene: ResolvedHeatmapScene): Record<string, unknown> {
  const hiddenValueAxis = { ...scene.plot.rowAxis, id: 'value', channel: 'value' as const, labels: { ...scene.plot.rowAxis.labels, visible: false }, line: { visible: false }, ticks: { ...scene.plot.rowAxis.ticks, visible: false }, title: scene.plot.rowAxis.title ? { ...scene.plot.rowAxis.title, visible: false } : undefined }
  const fake = { ...scene, guides: [], plot: { kind: 'bar' as const, categoryPlacement: 'band' as const, orientation: 'vertical' as const, stacking: 'none' as const, categories: scene.plot.categories, categoryAxis: scene.plot.categoryAxis, valueAxis: hiddenValueAxis, valueDomain: { min: 0, max: 1, step: 1 }, barWidth: 100, seriesGap: 0, series: [] } }
  const option = renderNativeBarScene(fake)
  const rowAxis = scene.plot.rowAxis, side = rowAxis.placement.kind === 'side' ? rowAxis.placement.side : 'left'
  const rowLabelPlacement = verticalAxisLabelPlacement(side as 'left' | 'right', rowAxis.labels.size, rowAxis.labels.gap, rowAxis.ticks.visible ? rowAxis.ticks.length : 0, scene.compatibilityConfig.categoryAxisLabelAlignment)
  const cells = scene.plot.rows.flatMap((row) => row.cells)
  const rect = (cell: typeof cells[number]) => scene.geometry.heatmap.cells[cell.id]
  const cellSeries = { id: 'heatmap-cells', name: 'Тепловая карта', type: 'custom', coordinateSystem: 'none', triggerEvent: true, clip: true, z: 5, data: cells.map((cell) => ({ value: [cell.columnIndex, cell.rowIndex, cell.value], elementId: cell.id, datumId: cell.datumId, seriesId: cell.seriesId, elementKey: cell.legacyKey, sourceSeriesName: scene.plot.rows[cell.rowIndex]?.name, displayCategory: cell.displayCategory, displayValue: cell.displayValue, displayColor: cell.color })), renderItem: (params: { dataIndex: number }) => { const cell = cells[params.dataIndex], bounds = rect(cell); if (!cell || !bounds) return null; const inset = scene.plot.cellGap / 2, shape = { x: bounds.x + inset, y: bounds.y + inset, width: Math.max(0, bounds.width - scene.plot.cellGap), height: Math.max(0, bounds.height - scene.plot.cellGap) }, labelWidth = Math.max(1, shape.width - 8), labelHeight = Math.max(1, shape.height - 6), lineHeight = Math.round(cell.label.style.size * cell.label.style.lineHeight / 100), naturalWidth = measureTextWidth(cell.label.text, cell.label.style.size, cell.label.style.fontFamily, cell.label.style.weight), labelVisible = cell.label.visible && labelWidth >= 8 && labelHeight >= lineHeight; return { type: 'group', info: { elementId: cell.id, datumId: cell.datumId, seriesId: cell.seriesId, elementKey: cell.legacyKey }, clipPath: { type: 'rect', shape }, children: [{ type: 'rect', shape, style: { fill: cell.color }, emphasis: { style: { stroke: scene.compatibilityConfig.axisLineColor, lineWidth: 1 } } }, ...(labelVisible ? [{ type: 'text', style: { x: bounds.x + bounds.width / 2, y: bounds.y + bounds.height / 2, text: cell.label.text, ...nativeGraphicTextStyle(cell.label.style), fill: cell.label.color, align: 'center', verticalAlign: 'middle', ...(naturalWidth > labelWidth ? { width: labelWidth, height: labelHeight, overflow: 'break', lineOverflow: 'truncate', ellipsis: '…' } : {}) } }] : [])] } } }
  const guide = scene.guides.find((item) => item.kind === 'color-scale'), scale = scene.geometry.heatmap.scale
  const scaleGraphics = !guide?.visible || !scale ? [] : [{ id: 'heatmap-scale-bar', type: 'rect', silent: true, z: 90, shape: scale.bar, style: { fill: { type: 'linear', x: 0, y: 0, x2: guide.position === 'left' || guide.position === 'right' ? 0 : 1, y2: guide.position === 'left' || guide.position === 'right' ? 1 : 0, colorStops: (guide.stops ?? []).map((stop) => guide.position === 'left' || guide.position === 'right' ? { offset: 1 - stop.offset, color: stop.color } : stop).sort((a, b) => a.offset - b.offset) } } }, ...scale.ticks.flatMap((tick, index) => [{ id: `heatmap-scale-tick-${index}`, type: 'line', silent: true, z: 91, shape: guide.position === 'left' || guide.position === 'right' ? { x1: scale.bar.x - 3, y1: tick.y, x2: scale.bar.x + scale.bar.width + 3, y2: tick.y } : { x1: tick.x, y1: scale.bar.y - 3, x2: tick.x, y2: scale.bar.y + scale.bar.height + 3 }, style: { stroke: guide.style?.color, lineWidth: 1 } }, { id: `heatmap-scale-label-${index}`, type: 'text', silent: true, z: 91, style: { x: tick.x, y: tick.y, text: tick.label, ...(guide.style ? nativeGraphicTextStyle(guide.style) : {}), align: tick.align, verticalAlign: tick.verticalAlign } }])]
  const rowGrid = !scene.compatibilityConfig.showHorizontalGrid ? [] : scene.plot.rows.map((row, index) => { const y = scene.geometry.plot.y + (index + .5) * scene.geometry.plot.height / Math.max(1, scene.plot.rows.length); return { id: `heatmap-row-grid:${row.id}`, type: 'line', silent: true, z: 1, shape: { x1: scene.geometry.plot.x, y1: y, x2: scene.geometry.plot.x + scene.geometry.plot.width, y2: y }, style: { stroke: scene.compatibilityConfig.gridColor, lineWidth: scene.compatibilityConfig.gridWidth, lineDash: scene.compatibilityConfig.gridType === 'dashed' ? [6, 4] : scene.compatibilityConfig.gridType === 'dotted' ? [2, 3] : undefined } } })
  const rowLineHeight = Math.round(rowAxis.labels.style.size * rowAxis.labels.style.lineHeight / 100)
  const rowLayouts = scene.plot.rows.flatMap((row) => { const bounds = scene.geometry.elements[`row-label:${row.id}`]; return bounds ? [{ axis: 'y' as const, category: row.sourceKey, left: bounds.x, top: bounds.y + (bounds.height - rowLineHeight) / 2, width: bounds.width, size: rowAxis.labels.style.size, rotation: 0, style: { ...rowAxis.labels.style, align: rowLabelPlacement.align } }] : [] })
  const rowHits = scene.plot.rows.flatMap((row) => { const bounds = scene.geometry.elements[`row-label:${row.id}`]; return bounds ? [{ rect: bounds, info: { elementKey: `category-label:y:${row.sourceKey}`, sourceSeriesName: '', displayCategory: row.sourceKey, displayValue: row.name, selectionTarget: 'category-label' as const, axis: 'y' as const } }] : [] })
  return { ...option, legend: { show: false }, tooltip: { trigger: 'item', formatter: (params: { dataIndex?: number }) => { const cell = cells[params.dataIndex ?? -1]; return cell ? `<b>${escapeHtml(scene.plot.rows[cell.rowIndex]?.name ?? '')}</b><br/>${escapeHtml(scene.plot.categories[cell.columnIndex]?.label ?? '')}: <b>${escapeHtml(cell.displayValue)}</b>` : '' } }, yAxis: { type: 'category', data: scene.plot.rows.map((row) => row.name), inverse: true, position: side, name: '', axisLabel: { show: rowAxis.labels.visible, ...rowLabelPlacement, color: rowAxis.labels.style.color, fontFamily: rowAxis.labels.style.fontFamily, fontSize: rowAxis.labels.style.size, fontWeight: rowAxis.labels.style.weight }, axisLine: { show: rowAxis.line.visible }, axisTick: { show: rowAxis.ticks.visible, length: rowAxis.ticks.length, alignWithLabel: true }, splitLine: { show: false }, triggerEvent: true }, series: [cellSeries], graphic: [...((option.graphic as unknown[]) ?? []), ...rowGrid, ...scaleGraphics], nativeCategoryLayouts: [...((option.nativeCategoryLayouts as unknown[]) ?? []), ...rowLayouts], nativeSelectionHits: [...((option.nativeSelectionHits as unknown[]) ?? []), ...rowHits] }
}
