import { nativeGraphicTextStyle, renderNativeBarScene } from './renderBarScene'
import type { ResolvedHeatmapScene } from '../../chart-types/heatmap/layout'

const escapeHtml = (value: unknown) => String(value ?? '').replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[character]!)

export function renderHeatmapScene(scene: ResolvedHeatmapScene): Record<string, unknown> {
  const hiddenValueAxis = { ...scene.plot.rowAxis, id: 'value', channel: 'value' as const, labels: { ...scene.plot.rowAxis.labels, visible: false }, line: { visible: false }, ticks: { ...scene.plot.rowAxis.ticks, visible: false }, title: scene.plot.rowAxis.title ? { ...scene.plot.rowAxis.title, visible: false } : undefined }
  const fake = { ...scene, guides: [], plot: { kind: 'bar' as const, categoryPlacement: 'band' as const, orientation: 'vertical' as const, stacking: 'none' as const, categories: scene.plot.categories, categoryAxis: scene.plot.categoryAxis, valueAxis: hiddenValueAxis, valueDomain: { min: 0, max: 1, step: 1 }, barWidth: 100, seriesGap: 0, series: [] } }
  const option = renderNativeBarScene(fake)
  const rowAxis = scene.plot.rowAxis, side = rowAxis.placement.kind === 'side' ? rowAxis.placement.side : 'left'
  const cells = scene.plot.rows.flatMap((row) => row.cells)
  const rect = (cell: typeof cells[number]) => scene.geometry.heatmap.cells[cell.id]
  const cellSeries = { id: 'heatmap-cells', name: 'Тепловая карта', type: 'custom', coordinateSystem: 'none', triggerEvent: true, clip: true, z: 5, data: cells.map((cell) => ({ value: [cell.columnIndex, cell.rowIndex, cell.value], elementId: cell.id, datumId: cell.datumId, seriesId: cell.seriesId, elementKey: cell.legacyKey, sourceSeriesName: scene.plot.rows[cell.rowIndex]?.name, displayCategory: cell.displayCategory, displayValue: cell.displayValue, displayColor: cell.color })), renderItem: (params: { dataIndex: number }) => { const cell = cells[params.dataIndex], bounds = rect(cell); if (!cell || !bounds) return null; const inset = scene.plot.cellGap / 2, shape = { x: bounds.x + inset, y: bounds.y + inset, width: Math.max(0, bounds.width - scene.plot.cellGap), height: Math.max(0, bounds.height - scene.plot.cellGap) }; return { type: 'group', info: { elementId: cell.id, datumId: cell.datumId, seriesId: cell.seriesId, elementKey: cell.legacyKey }, children: [{ type: 'rect', shape, style: { fill: cell.color }, emphasis: { style: { stroke: scene.compatibilityConfig.axisLineColor, lineWidth: 1 } } }, ...(cell.label.visible ? [{ type: 'text', style: { x: bounds.x + bounds.width / 2, y: bounds.y + bounds.height / 2, text: cell.label.text, ...nativeGraphicTextStyle(cell.label.style), fill: cell.label.color, align: 'center', verticalAlign: 'middle' } }] : [])] } } }
  const guide = scene.guides.find((item) => item.kind === 'color-scale'), scale = scene.geometry.heatmap.scale
  const scaleGraphics = !guide?.visible || !scale ? [] : [{ id: 'heatmap-scale-bar', type: 'rect', silent: true, z: 90, shape: scale.bar, style: { fill: { type: 'linear', x: 0, y: 0, x2: guide.position === 'left' || guide.position === 'right' ? 0 : 1, y2: guide.position === 'left' || guide.position === 'right' ? 1 : 0, colorStops: (guide.stops ?? []).map((stop) => guide.position === 'left' || guide.position === 'right' ? { offset: 1 - stop.offset, color: stop.color } : stop).sort((a, b) => a.offset - b.offset) } } }, ...scale.ticks.flatMap((tick, index) => [{ id: `heatmap-scale-tick-${index}`, type: 'line', silent: true, z: 91, shape: guide.position === 'left' || guide.position === 'right' ? { x1: scale.bar.x - 3, y1: tick.y, x2: scale.bar.x + scale.bar.width + 3, y2: tick.y } : { x1: tick.x, y1: scale.bar.y - 3, x2: tick.x, y2: scale.bar.y + scale.bar.height + 3 }, style: { stroke: guide.style?.color, lineWidth: 1 } }, { id: `heatmap-scale-label-${index}`, type: 'text', silent: true, z: 91, style: { x: tick.x, y: tick.y, text: tick.label, ...(guide.style ? nativeGraphicTextStyle(guide.style) : {}), align: tick.align, verticalAlign: 'middle' } }])]
  return { ...option, legend: { show: false }, tooltip: { trigger: 'item', formatter: (params: { dataIndex?: number }) => { const cell = cells[params.dataIndex ?? -1]; return cell ? `<b>${escapeHtml(scene.plot.rows[cell.rowIndex]?.name ?? '')}</b><br/>${escapeHtml(scene.plot.categories[cell.columnIndex]?.label ?? '')}: <b>${escapeHtml(cell.displayValue)}</b>` : '' } }, yAxis: { type: 'category', data: scene.plot.rows.map((row) => row.name), inverse: true, position: side, name: '', axisLabel: { show: rowAxis.labels.visible, margin: rowAxis.labels.gap, color: rowAxis.labels.style.color, fontFamily: rowAxis.labels.style.fontFamily, fontSize: rowAxis.labels.style.size, fontWeight: rowAxis.labels.style.weight }, axisLine: { show: rowAxis.line.visible }, axisTick: { show: rowAxis.ticks.visible, length: rowAxis.ticks.length }, splitLine: { show: scene.compatibilityConfig.showHorizontalGrid, lineStyle: { color: scene.compatibilityConfig.gridColor, width: scene.compatibilityConfig.gridWidth, type: scene.compatibilityConfig.gridType } }, triggerEvent: true }, series: [cellSeries], graphic: [...((option.graphic as unknown[]) ?? []), ...scaleGraphics] }
}
