import { formatYAxisNumber } from '../../../core/numberFormat'
import type { ChartTextStyle } from '../../../core/types'
import type { ResolvedDistributionMarkPlacement, ResolvedDistributionScene } from '../../chart-types/distribution/layout'

const textStyle = (style: ChartTextStyle) => ({ color: style.color, fontFamily: style.fontFamily, fontSize: style.size, fontWeight: style.weight, fontStyle: style.italic ? 'italic' : 'normal', lineHeight: Math.round(style.size * style.lineHeight / 100), align: style.align })
const graphicTextStyle = (style: ChartTextStyle) => { const { color, ...rest } = textStyle(style); return { ...rest, fill: color } }
const labelPlacement = (position: 'top' | 'right' | 'bottom' | 'left') => ({ align: position === 'left' ? 'right' : position === 'right' ? 'left' : 'center', verticalAlign: position === 'top' ? 'bottom' : position === 'bottom' ? 'top' : 'middle', opacity: 1 })
const escapeHtml = (value: unknown) => String(value ?? '').replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[character]!)
const lineDash = (type: 'solid' | 'dashed' | 'dotted') => type === 'dashed' ? [6, 4] : type === 'dotted' ? [2, 3] : undefined
const axisSide = (axis: ResolvedDistributionScene['plot']['valueAxis']) => axis.placement.kind === 'side' ? axis.placement.side : undefined

function shape(placement: ResolvedDistributionMarkPlacement) {
  const mark = placement.mark, info = { elementId: mark.id, datumId: mark.datumId, elementKey: mark.legacyKey }
  if ('stroke' in mark && placement.line) return { type: 'line', info, shape: placement.line, style: { stroke: mark.stroke.color, lineWidth: mark.stroke.width, opacity: mark.stroke.opacity } }
  if (!('marker' in mark)) return { type: 'group', children: [] }
  const size = placement.markerDiameter, half = size / 2, common = { fill: mark.marker.fill, stroke: mark.marker.stroke, lineWidth: mark.marker.strokeWidth, opacity: mark.marker.opacity }
  if (mark.marker.shape === 'rect' || mark.marker.shape === 'roundRect') return { type: 'rect', info, shape: { x: placement.x - half, y: placement.y - half, width: size, height: size, r: mark.marker.shape === 'roundRect' ? size * .22 : 0 }, style: common }
  if (mark.marker.shape === 'diamond') return { type: 'polygon', info, shape: { points: [[placement.x, placement.y - half], [placement.x + half, placement.y], [placement.x, placement.y + half], [placement.x - half, placement.y]] }, style: common }
  if (mark.marker.shape === 'triangle') return { type: 'polygon', info, shape: { points: [[placement.x, placement.y - half], [placement.x + half, placement.y + half], [placement.x - half, placement.y + half]] }, style: common }
  return { type: 'circle', info, shape: { cx: placement.x, cy: placement.y, r: half }, style: common }
}

function markSeries(scene: ResolvedDistributionScene) {
  const elements = new Map(scene.elements.filter((item) => item.role === 'mark').map((item) => [item.id, item]))
  return scene.plot.groups.flatMap<Record<string, unknown>>((group, groupIndex) => {
    const placements = scene.distributionGeometry.marks.filter((item) => item.groupId === group.id)
    if (!placements.length) return []
    const data = placements.map((placement) => { const mark = placement.mark, element = elements.get(mark.id); return { value: scene.plot.orientation === 'horizontal' ? [mark.value, placement.laneCoordinate] : [placement.laneCoordinate, mark.value], rawValue: mark.value, count: 'count' in mark ? mark.count : undefined, elementId: mark.id, datumId: mark.datumId, seriesId: element?.role === 'mark' ? element.seriesId : group.id, elementKey: mark.legacyKey, sourceSeriesName: group.sourceSeriesName, groupName: group.displayName, displayCategory: mark.displayCategory, displayValue: mark.displayValue, displayLabel: mark.displayLabel, displayColor: group.color, ...('marker' in mark ? { symbol: mark.marker.shape, symbolSize: mark.marker.size, itemStyle: { color: mark.marker.fill, borderColor: mark.marker.stroke, borderWidth: mark.marker.strokeWidth, opacity: mark.marker.opacity }, label: { show: mark.label.visible, formatter: mark.label.text, position: mark.label.position, distance: 5, ...textStyle(mark.label.style), ...labelPlacement(mark.label.position) } } : {}) } })
    if (scene.plot.variant !== 'beeswarm' && scene.plot.variant !== 'barcode') { const first = placements[0].mark; return [{ id: group.id, name: group.sourceSeriesName, type: 'scatter', clip: true, triggerEvent: true, z: 40 + scene.plot.groups.length - groupIndex, symbol: 'circle', symbolSize: 'marker' in first ? first.marker.size : 0, itemStyle: 'marker' in first ? { color: first.marker.fill, borderColor: first.marker.stroke, borderWidth: first.marker.strokeWidth, opacity: first.marker.opacity } : undefined, emphasis: { disabled: true, scale: false }, label: { show: first.label.visible, formatter: '{b}' }, data }] }
    return [{ id: group.id, name: group.sourceSeriesName, type: 'custom', coordinateSystem: 'cartesian2d', clip: false, triggerEvent: true, z: 40 + scene.plot.groups.length - groupIndex,
      data,
      renderItem: (params: { dataIndex: number } | null) => { const placement = placements[params?.dataIndex ?? 0], mark = placement.mark, label = mark.label, gap = ('stroke' in mark && placement.line ? Math.hypot(placement.line.x2 - placement.line.x1, placement.line.y2 - placement.line.y1) / 2 : placement.markerDiameter / 2) + 5; const labelX = placement.x + (label.position === 'right' ? gap : label.position === 'left' ? -gap : 0), labelY = placement.y + (label.position === 'bottom' ? gap : label.position === 'top' ? -gap : 0); return { type: 'group', info: { elementId: mark.id, datumId: mark.datumId, elementKey: mark.legacyKey }, children: [shape(placement), ...(label.visible && label.text ? [{ type: 'text', info: { elementId: mark.id, datumId: mark.datumId, elementKey: mark.legacyKey }, style: { x: labelX, y: labelY, text: label.text, ...graphicTextStyle(label.style), ...labelPlacement(label.position) } }] : [])] } },
    }]
  })
}

function derivedShapeSeries(scene: ResolvedDistributionScene) {
  const box = scene.distributionGeometry.boxShapes.map((shape) => ({ id: shape.layerId, name: scene.plot.groups.find((group) => group.id === shape.groupId)?.sourceSeriesName, type: 'custom', coordinateSystem: 'cartesian2d', z: 20, data: [{ value: [0, 0], summary: shape.mark.tooltip }], renderItem: () => ({ type: 'group', children: [shape.lowerWhisker, shape.upperWhisker, shape.lowerCap, shape.upperCap].map((line) => ({ type: 'line', shape: line, style: { stroke: shape.mark.whiskerStyle.color, lineWidth: shape.mark.whiskerStyle.width } })).concat([{ type: 'rect', shape: shape.box, style: { fill: shape.mark.boxStyle.fillColor, opacity: shape.mark.boxStyle.fillOpacity, stroke: shape.mark.boxStyle.strokeColor, lineWidth: shape.mark.boxStyle.strokeWidth } }] as never[], shape.median ? [{ type: 'line', shape: shape.median, style: { stroke: shape.mark.medianStyle.color, lineWidth: shape.mark.medianStyle.width } }] as never[] : []) }) }))
  const density = scene.distributionGeometry.densityShapes.map((shape, index) => ({ id: shape.layerId, name: scene.plot.groups.find((group) => group.id === shape.groupId)?.sourceSeriesName, type: 'custom', coordinateSystem: 'cartesian2d', z: 10 + index, data: [{ value: [0, 0], summary: shape.tooltip }], renderItem: () => ({ type: 'group', children: [{ type: 'polygon', shape: { points: shape.polygon }, style: { fill: shape.fillColor, opacity: shape.fillOpacity } }, { type: 'polyline', shape: { points: shape.outline }, style: { fill: 'none', stroke: shape.stroke.color, lineWidth: shape.stroke.width } }, ...(shape.baseline ? [{ type: 'line', shape: shape.baseline, style: { stroke: shape.stroke.color, lineWidth: 1.25 } }] : [])] }) }))
  return [...density, ...box]
}

function frequencySeries(scene: ResolvedDistributionScene) {
  const bins = scene.plot.groups.flatMap((group, groupIndex) => { const placements = scene.distributionGeometry.frequencyBins.filter(({ mark }) => mark.groupId === group.id); if (!placements.length) return []; return [{ id: `frequency:${group.id}`, name: group.sourceSeriesName, type: 'custom', coordinateSystem: 'cartesian2d', z: 3 + groupIndex, data: placements.map(({ mark }) => ({ value: scene.plot.orientation === 'horizontal' ? [mark.center, mark.amount] : [mark.amount, mark.center], elementId: mark.id, datumId: mark.datumId, seriesId: group.id, frequencyTooltip: mark.tooltip })), renderItem: (params: { dataIndex: number }) => { const placement = placements[params.dataIndex], mark = placement.mark, info = { elementId: mark.id, datumId: mark.datumId }; return { type: 'group', info, children: [{ type: 'rect', info, shape: placement.rect, style: { fill: mark.fill.color, opacity: mark.fill.opacity, stroke: mark.fill.stroke, lineWidth: mark.fill.strokeWidth } }, ...(mark.label && placement.label ? [{ type: 'text', silent: true, style: { x: placement.label.x, y: placement.label.y, text: mark.label.text, ...graphicTextStyle(mark.label.style), align: placement.label.align, verticalAlign: placement.label.verticalAlign } }] : [])] } } }] })
  const curves = scene.distributionGeometry.frequencyCurves.map((curve, index) => ({ id: curve.layerId, name: scene.plot.groups.find((group) => group.id === curve.groupId)?.sourceSeriesName, type: 'custom', coordinateSystem: 'cartesian2d', z: 3 + index, data: curve.samples.map((sample) => ({ value: scene.plot.orientation === 'horizontal' ? [sample.value, sample.density] : [sample.density, sample.value], kdeTooltip: { ...curve.tooltip, ...sample } })), renderItem: (params: { dataIndex: number }) => params.dataIndex ? { type: 'group', children: [] } : { type: 'group', children: [{ type: 'polygon', shape: { points: curve.polygon }, style: { fill: curve.fill.color, opacity: curve.fill.opacity } }, { type: 'polyline', shape: { points: curve.points }, style: { fill: 'none', stroke: curve.stroke.color, lineWidth: curve.stroke.width } }] } }))
  return [...bins, ...curves]
}

function distributionAxis(scene: ResolvedDistributionScene, screen: 'x' | 'y') {
  const horizontal = scene.plot.orientation === 'horizontal', valueAxis = horizontal === (screen === 'x'), frequency = scene.plot.variant === 'histogram' || scene.plot.variant === 'kde', axis = valueAxis ? scene.plot.valueAxis : scene.plot.laneAxis, config = scene.compatibilityConfig, secondary = scene.plot.frequencyDomain ?? scene.plot.laneDomain
  const nameGap = (axis.ticks.visible ? axis.ticks.length : 0) + (axis.labels.visible ? axis.labels.gap + axis.labels.size : 0) + (axis.title?.gap ?? 0)
  return { type: 'value', data: valueAxis || frequency ? undefined : scene.plot.lanes.map((lane) => lane.label), position: axisSide(axis), min: valueAxis ? scene.plot.valueDomain.min : secondary.min, max: valueAxis ? scene.plot.valueDomain.max : secondary.max, interval: valueAxis ? scene.plot.valueDomain.step : 'step' in secondary ? secondary.step : secondary.interval, inverse: !frequency && !valueAxis && horizontal, triggerEvent: true,
    name: axis.title?.visible && axis.orientation === 'horizontal' ? axis.title.text : '', nameLocation: 'middle', nameGap, nameTextStyle: axis.title ? textStyle(axis.title.style) : undefined,
    axisLine: { show: axis.line.visible, onZero: false, lineStyle: { color: config.axisLineColor, width: config.axisLineWidth, type: config.axisLineType } }, axisTick: { show: axis.ticks.visible, length: axis.ticks.length, lineStyle: { color: config.axisLineColor, width: config.axisLineWidth, type: config.axisLineType } },
    axisLabel: { show: axis.labels.visible, margin: axis.labels.gap, rotate: axis.labels.rotation ?? 0, hideOverlap: false, ...textStyle(axis.labels.style), formatter: valueAxis || frequency ? (value: number) => formatYAxisNumber(value, config) : (value: number) => Number.isInteger(value) ? scene.plot.lanes[value]?.label ?? '' : '' },
    splitLine: { show: valueAxis ? scene.plot.grid.valueVisible : frequency && scene.plot.grid.laneVisible, lineStyle: { color: scene.plot.grid.color, width: scene.plot.grid.width, type: scene.plot.grid.type } },
  }
}

export function renderDistributionScene(scene: ResolvedDistributionScene): Record<string, unknown> {
  const config = scene.compatibilityConfig, plot = scene.geometry.plot, canvas = scene.geometry.canvas
  const title = scene.frameElements.find((item) => item.role === 'title'), subtitle = scene.frameElements.find((item) => item.role === 'subtitle')
  const footer = scene.frameElements.filter((item) => item.role === 'note' || item.role === 'source').map((item, index, items) => ({ id: `chart-${item.role}`, type: 'text', left: scene.geometry.content.x, bottom: canvas.height - scene.geometry.content.y - scene.geometry.content.height + (items.length - index - 1) * (Math.round(item.style.size * item.style.lineHeight / 100) + scene.document.composition.noteSource), style: { text: item.text, width: scene.geometry.content.width, overflow: 'break', ...graphicTextStyle(item.style) } }))
  const verticalAxes = [scene.plot.valueAxis, scene.plot.laneAxis].filter((axis) => axis.orientation === 'vertical' && axis.title?.visible && axis.title.text).map((axis) => ({ id: `chart-${axis.id}-axis-title`, type: 'text', left: axisSide(axis) === 'left' ? scene.geometry.content.x : undefined, right: axisSide(axis) === 'right' ? canvas.width - scene.geometry.content.x - scene.geometry.content.width : undefined, top: 'middle', rotation: axisSide(axis) === 'right' ? -Math.PI / 2 : Math.PI / 2, style: { text: axis.title!.text, ...graphicTextStyle(axis.title!.style), align: 'center', verticalAlign: 'middle' } }))
  const gridGraphics = scene.distributionGeometry.laneGrid.map((line) => ({ id: `distribution-grid:${line.laneId}`, type: 'line', silent: true, z: 1, shape: { x1: line.x1, y1: line.y1, x2: line.x2, y2: line.y2 }, style: { stroke: line.stroke.color, lineWidth: line.stroke.width, lineDash: lineDash(line.stroke.type) } }))
  const summaries = scene.distributionGeometry.summaries.map((line) => ({ id: line.id, type: 'line', silent: true, z: 60, shape: { x1: line.x1, y1: line.y1, x2: line.x2, y2: line.y2 }, style: { stroke: line.color, lineWidth: line.width, lineCap: line.cap } }))
  const frequencySummaries = scene.distributionGeometry.frequencySummaries.map((line) => ({ id: line.id, type: 'line', silent: true, z: 60, shape: { x1: line.x1, y1: line.y1, x2: line.x2, y2: line.y2 }, style: { stroke: line.color, lineWidth: line.width, lineCap: line.cap } }))
  const densitySummaries = scene.distributionGeometry.densitySummaries.flatMap((summary) => [...summary.boxes.map((box, index) => ({ id: `${summary.id}:box:${index}`, type: 'rect', silent: true, z: 30, shape: { x: box.x, y: box.y, width: box.width, height: box.height }, style: { fill: box.fill, opacity: box.opacity, stroke: box.stroke, lineWidth: box.strokeWidth } })), ...summary.lines.map((line, index) => ({ id: `${summary.id}:line:${index}`, type: 'line', silent: true, z: 35, shape: { x1: line.x1, y1: line.y1, x2: line.x2, y2: line.y2 }, style: { stroke: line.color, lineWidth: line.width, lineDash: line.dash } }))])
  const legend = scene.guides.find((guide) => guide.kind === 'categorical-legend'), rail = scene.geometry.reservations['guide:legend'], items = legend?.kind === 'categorical-legend' ? legend.items.filter((item) => item.visible) : []
  return { animation: true, animationDuration: 180, animationDurationUpdate: 180, backgroundColor: scene.document.canvas.background, color: scene.plot.groups.map((group) => group.color), textStyle: { fontFamily: scene.document.theme.fontFamily },
    title: { text: title?.text ?? '', subtext: subtitle?.text ?? '', left: scene.geometry.content.x, top: Math.max(0, scene.geometry.content.y - 8), textStyle: title ? textStyle(title.style) : undefined, subtextStyle: subtitle ? textStyle(subtitle.style) : undefined, itemGap: scene.document.composition.titleSubtitle, triggerEvent: true },
    tooltip: { trigger: scene.plot.variant === 'kde' ? 'axis' : 'item', formatter: (input: unknown) => { type TooltipItem = { data?: { groupName?: string; displayLabel?: string; displayValue?: string; count?: number; frequencyTooltip?: { group: string; range: string; amount: number }; kdeTooltip?: { group: string; value: number; density: number }; summary?: { group: string; count: number; median: string; mean: string; quartiles: string } } }; const entries = (Array.isArray(input) ? input : [input]) as TooltipItem[], item = entries[0]; if (item.data?.frequencyTooltip) { const value = item.data.frequencyTooltip; return `<b>${escapeHtml(value.group)}</b><br/>${escapeHtml(value.range)}<br/>Наблюдений: <b>${value.amount}</b>` } if (item.data?.kdeTooltip) return [`<b>${escapeHtml(formatYAxisNumber(item.data.kdeTooltip.value, config))}</b>`, ...entries.flatMap((entry) => entry.data?.kdeTooltip ? [`${escapeHtml(entry.data.kdeTooltip.group)}: <b>${entry.data.kdeTooltip.density.toLocaleString('ru-RU', { maximumFractionDigits: 4 })}</b>`] : [])].join('<br/>'); if (item.data?.summary) { const summary = item.data.summary; return `<b>${escapeHtml(summary.group)}</b><br/>n = ${summary.count}<br/>Медиана: ${escapeHtml(summary.median)}<br/>Среднее: ${escapeHtml(summary.mean)}<br/>Q1–Q3: ${escapeHtml(summary.quartiles)}` } const label = config.distributionLabelField && item.data?.displayLabel ? `<b>${escapeHtml(item.data.displayLabel)}</b><br/>` : ''; return `${label}${escapeHtml(item.data?.groupName ?? '')}<br/>${escapeHtml(item.data?.displayValue ?? '')}${item.data?.count ? `<br/>Наблюдений: <b>${item.data.count}</b>` : ''}` } },
    legend: { show: Boolean(legend?.visible && items.length), data: [...new Set(scene.plot.groups.map((group) => group.sourceSeriesName))].map((name) => ({ name, icon: config.legendMarker === 'triangle' ? 'triangle' : config.legendMarker === 'diamond' ? 'diamond' : config.legendMarker === 'square' ? 'rect' : config.legendMarker === 'line' || scene.plot.variant === 'kde' ? 'path://M0 4H24V7H0Z' : scene.plot.variant === 'histogram' ? 'rect' : 'circle', itemStyle: { color: scene.plot.groups.find((group) => group.sourceSeriesName === name)?.color } })), formatter: (name: string) => items.find((item) => scene.plot.groups.some((group) => group.sourceSeriesName === name && item.color === group.color))?.label ?? name, orient: legend?.kind === 'categorical-legend' && (legend.position === 'left' || legend.position === 'right') ? 'vertical' : 'horizontal', left: rail?.x ?? scene.geometry.content.x, top: rail?.y, itemWidth: config.legendMarker === 'line' || scene.plot.variant === 'kde' ? 24 : 10, itemHeight: 10, itemGap: 18, textStyle: textStyle(config.legendText) },
    grid: { left: plot.x, top: plot.y, right: canvas.width - plot.x - plot.width, bottom: canvas.height - plot.y - plot.height, containLabel: false }, xAxis: distributionAxis(scene, 'x'), yAxis: distributionAxis(scene, 'y'), series: [...frequencySeries(scene), ...derivedShapeSeries(scene), ...markSeries(scene)], graphic: [...verticalAxes, ...gridGraphics, ...summaries, ...frequencySummaries, ...densitySummaries, ...footer] }
}
