import type { ChartConfig, ChartTextStyle } from '../../../core/types'

const textStyle = (size: number, weight = 400, color = '#2b2b2b'): ChartTextStyle => ({ fontFamily: 'Onest, sans-serif', size, color, weight, italic: false, lineHeight: 120, align: 'left' })
const defaultPalette = ['#0072b2', '#e69f00', '#009e73', '#d55e00', '#cc79a7', '#56b4e9', '#f0e442']

export function createDefaultChartConfig(): ChartConfig {
  return {
    canvasPreset: 'presentation-standard', canvasWidth: 1000, canvasHeight: 750, canvasBackground: '#ffffff', autoFitCanvas: true, canvasMarginTop: 24, canvasMarginRight: 24, canvasMarginBottom: 24, canvasMarginLeft: 32, titleSubtitleGap: 12, headerPlotGap: 28, headerLegendGap: 20, legendPlotGap: 24, plotFooterGap: 24, noteSourceGap: 10,
    kind: 'bar', xField: 'month', yField: 'revenue', yFields: ['revenue'], seriesField: '', aggregation: 'none', valueMode: 'absolute', missingMode: 'gap', title: 'Заголовок графика', showTitle: true, showSubtitle: true, showNote: true, showSource: true,
    subtitle: 'Подзаголовок графика', note: 'Комментарий к графику', source: 'Источник: данные пользователя', titleText: textStyle(42, 700), subtitleText: textStyle(25, 400, '#666666'), axisTitleText: textStyle(20, 600), axisLabelText: textStyle(18, 400, '#555555'), xAxisTitleText: textStyle(20, 600), yAxisTitleText: textStyle(20, 600), xAxisLabelText: textStyle(18, 400, '#555555'), yAxisLabelText: textStyle(18, 400, '#555555'), legendText: textStyle(19), valueText: textStyle(17, 600), noteText: textStyle(18, 400, '#666666'), sourceText: textStyle(18, 400, '#666666'), showValues: false, numberLocale: 'ru-RU', numberDecimals: null, numberOperation: 'none', numberFactor: 1, numberPrefix: '', numberSuffix: '', yAxisAffixScope: 'all', xAxisNumberPrefix: '', xAxisNumberSuffix: '', xAxisAffixScope: 'all', valueLabelAffixesLinked: true, numberGrouping: true, valueLabelPosition: 'auto', valueLabelAutoContrast: true, valueLabelHideOverlap: false, barValueLabelAbsorption: false, barValueLabelInsidePosition: 'end', barValueLabelOutsidePosition: 'end', barValueLabelAbsorptionPadding: 10, xAxisTitle: 'Подпись оси X', yAxisTitle: 'Подпись оси Y', xAxisTitleGap: 14, yAxisTitleGap: 14, xAxisLabelGap: 8, yAxisLabelGap: 8, xAxisPosition: 'bottom', yAxisPosition: 'left', showXAxisTitle: false, showYAxisTitle: false, showXAxisLabels: true, showYAxisLabels: true, showXAxisLine: true, showYAxisLine: false, axisLineColor: '#55515e', axisLineWidth: 1, axisLineType: 'solid', showXTicks: true, showYTicks: false, tickLength: 6, yAxisScaleType: 'linear', showZeroLine: false, zeroLineColor: '#8a8791', zeroLineWidth: 1, zeroLineType: 'solid', xAxisLabelRotate: 'auto', xAxisLabelOverflow: 'auto', elementStyles: {}, seriesStyles: {}, annotations: [],
    color: defaultPalette[0], paletteName: 'okabe-ito', palette: [...defaultPalette], paletteGradientColors: ['#3b4cc0', '#f7f7f7', '#b40426'], barWidth: 68, barFillOpacity: 1, barBorderColor: defaultPalette[0], barBorderWidth: 0, barBorderRadius: 0, barSeriesGap: 30, barOrientation: 'vertical', barCategorySort: 'none', barCategorySortSeries: '', areaFillOpacity: .32, stepPosition: 'end', intervalFillOpacity: .18, showLegend: false, legendPosition: 'top', showDirectLabels: false, directLabelText: textStyle(19, 600), directLabelGap: 16, showDirectLabelLines: false, directLabelLineWidth: 1, directLabelLineType: 'solid',
    scatterPointSize: 10, scatterSizeMin: 6, scatterSizeMax: 42, scatterSizeLegend: true, scatterSizeLegendTitle: 'Размер', scatterSizeLegendPosition: 'top-left', scatterOpacity: .78, scatterBorderWidth: 1, scatterHollow: false, scatterShowLabels: false, scatterLabelPosition: 'right', scatterTrendline: false, scatterTrendColor: '#77727f', scatterTrendWidth: 2, scatterTrendType: 'dashed', scatterTrendBand: false, scatterTrendBandOpacity: .12, scatterXReference: null, scatterYReference: null, scatterReferenceColor: '#8a8791', scatterReferenceWidth: 1.5, scatterReferenceType: 'dashed', scatterQuadrants: false, scatterQuadrantColors: ['#dfeee8', '#e7eef8', '#f8e5e3', '#f2eadb'], scatterQuadrantLabels: ['', '', '', ''], scatterDiagonal: false, scatterDiagonalColor: '#8a8791', scatterDiagonalWidth: 1.5, scatterDiagonalType: 'dashed', axisTitleMode: 'standard',
    showHorizontalGrid: true, showVerticalGrid: false, gridColor: '#d9d7df', gridWidth: 1, gridType: 'solid', categoryLabelOverrides: {}, legendMarker: 'auto',
    xAxisMin: '', xAxisMax: '', xAxisStep: null, dateAxisStepUnit: 'auto', yAxisMin: null, yAxisMax: null, yAxisStep: null, dateLabelFormat: 'auto',
    distributionLayoutMode: 'measures', distributionCategoryOrder: [], distributionCategoryStyles: {}, distributionOrientation: 'horizontal', distributionPointSize: 8, distributionPointOpacity: .4, distributionTickWidth: 2, distributionJitter: .32, distributionWidth: 72, distributionBandwidth: .14, distributionViolinMode: 'full', distributionViolinSummaryMode: 'box', distributionViolinShowWhiskers: true, distributionViolinHalfSide: 'second', distributionRaincloudPointMode: 'overlay', distributionShowPoints: true, distributionShowAllPoints: false, distributionShowMedian: true, distributionSummaryStatistic: 'median', distributionSummaryWidth: 3, distributionSummaryLength: 100, distributionShowOutliers: true, distributionBinCount: 12, distributionHistogramMin: null, distributionHistogramMax: null, distributionHistogramLabels: 'none', distributionHistogramRangeDecimals: 1, distributionDensityFillOpacity: .2, distributionRidgelineOverlap: 35, distributionShowLabels: false, distributionLabelPosition: 'right',
    slopeShowValues: true, slopeShowSeriesNames: true, slopeShowYAxis: false, movingAverageWindow: 12, movingAverageRawOpacity: .22, heatmapScaleMode: 'diverging', heatmapLowColor: '#2c6aa8', heatmapMidColor: '#f5f5f2', heatmapHighColor: '#c83e4d', heatmapMidpoint: 0, heatmapShowScale: true, heatmapScalePosition: 'right', heatmapCellGap: 1, heatmapRowSort: 'none', heatmapRowSortDirection: 'descending', heatmapMissingColor: '#e8e7eb', heatmapMissingLabel: '—', treemapGap: 2, treemapGroupGap: 5, treemapShowGroupLabels: true, treemapShowLeafLabels: true, treemapShowGroupValues: true, treemapShowLeafValues: false, treemapGroupLabelPosition: 'top-left', treemapLabelPosition: 'bottom-right', treemapGroupText: textStyle(16, 700), treemapLeafText: textStyle(14, 400), treemapHiddenCategories: [], treemapValueFormat: 'absolute',
  }
}
